### PR TITLE
Slovenian

### PR DESCRIPTION
**Pull request by beernarrd**
Hello, 
another update for slovenian translation files. Please check if bpisoj's commit stays untouched.

### CODE REVIEW

**Comment by dsblank** [comment]
@beernarrd Thanks!

@bpisoj Josip, does this look good to you?

**Comment by bpisoj** [comment]
Never mind my commit but i will more like rebased and squashed pl

**Comment by dsblank** [comment]
@bpisoj Can you either rebase and squash, or talk @beernarrd through it? Thanks!

**Comment by beernarrd** [comment]
give me a day or two. I'll try it. thanks for patience.
how should i do it? close this PR and open another, the squashed one?

**Comment by beernarrd** [comment]
Closing this one. Will open a squashed one.

**Pull request closed without merging**
