### PR TITLE
Milotype 19 01

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by prculley** [comment]
This needs to be rebased before pushing to the PR branch.  If you are working off of the gramps50 branch, make sure you are up to date with the main Gramps repo.  Some variation of a "git pull --rebase" and then force push back to your personal repo.  If you meant to work on master, get it rebased there before pushing and select 'master' at the top of the Github page.
There should really be only one or two commits in the listing above.

**Comment by milotype** [comment]
Hi Paul,
sorry I can't follow your instructions. I only work per internet on GitHub, nothing local. And I don't understand where all the other stuff came from. These I my steps I did:
- forked gramps anew
- generated my branch "milotype-19-01"
- uploaded my new .po file into the branch's po folder
- pulled the request
And I still don't unerstand where to send my pull requests in general - to "master" or to "maintenance/gramps50" branch.

**Comment by prculley** [comment]
Ok.  I did not realize you were only working on Github.  Most people use the various git commands locally and only push the results to github when finished.

It seems that you made your changes to master branch, and when you submitted the PR, you selected maintenance/gramps50 as the branch to potentially merge.  These have to match.

I changed the selected branch to master at the top of the PR and it seems to have cleaned it up.

If you want to make changes to gramps50 branch, you have to select that before downloading your po file prior to editing.

At them moment, we are requesting that po file changes be made first to gramps50 (so that people get the updates sooner).  These get merged into master periodically, so they end up in master anyway.  Eventually we will end up with significant differences on master with a lot of new strings to translate, and will call for updates to be made there.  Probably late summer or fall this year.  There are some changes there now, if you are already up to date with gramps50, then go ahead and get started on master, but know that there will be a lot more to do later on.

I just looked at your changes, it appears that most of them would be appropriate in the gramps50 branch.  I don't know if the tool you have will allow you to easily copy your changes to the gramps50 branch, if you cannot figure it out, let me know as I might be able to find a way to do this without a lot of manual editing.

**Comment by milotype** [comment]
Just to understand things right:
after your change, my branch "milotype:milotype-19-01" will now get merged into "gramps-project:master" (btw. with "milotype:milotype-19-01" I only wanted to change the croatian .po file). The gramps50 branch won't have the new croatian po file.

Can I simply do another pull request for my po file to the gramps50 branch like this: 
- create on my account a new branch from gramps50 branch
- upload my po file in the appropirate subfolder
- pull request to the gramps-account's "gramps50" branch

This way my translation would become available with the next update/release of Gramps app.

**Comment by prculley** [comment]
Yes, but please check your translation against the gramps50 gramps.pot file, to make sure that no strings were removed in master that are still needed in gramps50.
See https://www.gramps-project.org/wiki/index.php/Translating_Gramps#Updating_your_translation

**Comment by milotype** [comment]
ok, will do. thank you!

**Comment by sam-m888** [comment]
Resubmitted as https://github.com/gramps-project/gramps/pull/803 by @milotype Thank you

**Pull request closed without merging**
