### PR TITLE
Fix 'References' Gramplet for issue when activated during an import

### PR DESCRIPTION
**Pull request by prculley**
Fixes [#10507](https://gramps-project.org/bugs/view.php?id=10507) ... Maybe

I noticed that the active_handle was being returned as empty string, not None so changed test for that.
Based on Nick's observation that you cannot do a backlinks lookup and other things during an import, I disabled input to the main window during the import.

The popup from Gedcom import for Ansel character sets still works.  Other main window input seems to be locked out.  The progress bar still updates.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Certainly a possibility.  The import will run in a batch transaction so a call to `find_backlink_handles` will fail because the _references_ table will be closed.

**Comment by Nick-Hall** [comment]
> I do have to wonder if allowing GUI activities during import is a really good idea... Didn't test since I did not want to find more bugs ;-)

Allowing GUI activities during any batch transaction is not a good idea with our current BSDDB backend.  So this will also be a problem when running certain tools.

During a batch transaction, the reference table is closed so the `find_backlinks_handle` method will be unavailable.  This will affect three gramplets and also the participants information in the event view.

The secondary tables, which are like indexes in BSDDB, will also be closed.  So I expect problems with anything that attempts to get an object from a Gramps ID, such as certain filters and reports.

I seem to remember discussing this with @ennoborg in the past.  We thought about making all batch tool dialogs modal, but that obviously doesn't provide a complete solution.  The new backends which don't have the same design constraint are another consideration.

**Comment by prculley** [comment]
@Nick-Hall @sam-m888 So instead of patching the various elements to deal with non-functional backlinks, I stopped allowing input during the import.  I think this should finally fix this issue...

**Comment by sam-m888** [comment]
@prculley Much better 👍  Unfortunately I worked out a way to crash Gramps while importing from the menus :(

**Comment by Nick-Hall** [comment]
@prculley Yes, that it a better approach.

**Comment by prculley** [comment]
@sam-m888 I still don't understand how you were able to access the menus when I cannot.  However, I looked at the code again and realized that the original code attempted to solve this problem by keeping the filechooserdialog (a modal dialog) around, but hiding it during the import.  In theory, this should have prevented access to the main window as well.  But something must have changed in Gtk since that was coded, since it did not work.  So, on the off chance that this was interfering with my patch to set the main window insensitive, I eliminate that bit of original code.  This also works fine for me, I hope it works for your system.

**Comment by sam-m888** [comment]
@prculley Must be something to do with either Gtk or the desktop
environments for Ubuntu I'm testing against  as when I test on Win 10 with
the AIO I get the results you see and on ubuntu I get a different!  I've
added my latest test result to the bug report.  Thanks for persevering.

**Comment by prculley** [comment]
@Nick-Hall @sam-m888 I understand now.  I am using KDE on Ubuntu, and you are using Gnome.  I did not realize until now that the menus under Gnome are not part of the Gramps main window, they are somewhere else, so setting the main window insensitive is not enough.  I've been looking around for a while now and have not yet found how to disable these; I suspect I have to somehow disable the specific Application menu widget.  But I have not yet found where it is.  Nick, if you can give advice I would appreciate it.

**Comment by prculley** [comment]
I thought I figured out how to disable the menus, but it did not work...

**Comment by Nick-Hall** [comment]
@prculley You need to use the `set_sensitive` method of either a Gtk [Action](https://developer.gnome.org/gtk3/unstable/GtkAction.html#gtk-action-set-sensitive) or [ActionGroup](https://developer.gnome.org/gtk3/stable/GtkActionGroup.html#gtk-action-group-set-sensitive).

This reminds me that the `UIManager` code needs to be re-written to avoid using deprecated methods.

**Comment by prculley** [comment]
@sam-m888 @Nick-Hall So I tried several other approaches to getting the menus disabled.  They all worked on my Windows installation and under KDE but failed under Gnome.  So I used Nick's suggestion to set the 'ActionGroup's insensitive.  It is not as clean or surgical as I would like since it leaves the menus visible, under Gnome but it does seem to prevent their activation while an import is in progress.

I looked into updating UIManager, Actions, ActionGroup etc. a while ago, and concluded that this would be a pretty big job, with changes all over the place.  I think the modern idea is to use Gtk.Application.  Maybe we need to make this a GEPS to keep it on our radar?

**Comment by Nick-Hall** [comment]
> I looked into updating UIManager, Actions, ActionGroup etc. a while ago, and concluded that this would be a pretty big job, with changes all over the place. I think the modern idea is to use Gtk.Application. Maybe we need to make this a GEPS to keep it on our radar?

Yes, it is a big job.  I have added it to the v5.1 roadmap.

**Comment by sam-m888** [comment]
Tested and works perfectly.

On ubuntu 16.04 with gnome/unity all menus that can create an action are greyed out.

menus-greyedout

**Comment by Nick-Hall** [comment]
@prculley Did you consider making the import progress dialog modal?  That might also work.

**Comment by prculley** [comment]
I tried a modal "please wait" dialog; which failed because the importers pop up other modal dialogs and they conflict.  On Gnome, it actually locked up Gramps, since I could not dismiss the "please wait" and that was the only one which had focus, so the other ones could not be dismissed.  We could probably redesign each importer to use its own progress dialog, rather than the callback dialog used now; that would avoid the conflicts.  But, as usual, I was trying to keep the changes more limited.

**Comment by Nick-Hall** [comment]
@prculley Yes.  Keep the changes limited.  I only mentioned the modal dialog because I thought that it might have offered a simpler solution.

**Comment by sam-m888** [comment]
Thank you

**Pull request merged**
