### PR TITLE
NarrativeWeb: add enclosed by and encloses (place)

### PR DESCRIPTION
**Pull request by SNoiraud**
Fixes #10743

### CODE REVIEW

**Comment by lordemannd** [comment]
I can reproduce the failure with this DB
[test-PR 679.zip](https://github.com/gramps-project/gramps/files/2469854/test-PR.679.zip)
 . It runs without errors under a clean version of 5.0.0, but with PR 679 and the current changes on the gramps50 branch. I get the above failure.

**Comment by prculley** [comment]
The particular place that is crashing the Narrative Web report is marked 'Private'.  So when it is loaded from the db, it returns 'None'.
Need to test for 'None' on every db get operation; to deal with filtered objects like this.
The report runs if you check off "Include objects marked Private'.

**Comment by lordemannd** [comment]
Yes, I see it now. Always more conditions to test. 
(now I wish I had left myself a note as to why I had that marked as private)

**Comment by SNoiraud** [comment]
Must be applied on master and not on gramps 5.0
I'll add a test for the Private place.

**Pull request closed without merging**
