### PR TITLE
Fix 'Extract Info from names' tool

### PR DESCRIPTION
**Pull request by prculley**
It left an unclosed window, if you cancelled instead of run.
It had a bad transient parent issue, it ignored the ManagedWindow setting because the glade file made it visible too soon.
Fixed Gtk deprecation warnings
Added window size/position config.
Also did a pylint, in separate commit.

-----------
https://gramps-project.org/wiki/index.php?title=Gramps_4.2_Wiki_Manual_-_Tools#Extract_Information_from_Names

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
I wonder if you want to get rid of the show_all() also?

**Comment by Paul-Franklin** [comment]
And maybe the default sizes in the Glade file as well
as the resize(700,100) ?

**Comment by Paul-Franklin** [comment]
Or perhaps I am getting confused, with one dialog vs the second.

**Comment by prculley** [comment]
@Nick-Hall The 'show_all' and 'resize(700,100)' are both necessary, as they are for the manually created initial dialog.  I did realize that the resize should have been before the show_all otherwise the dialog would end up not centered on the parent.
I did remove the extraneous size in the glade file, as that was covered by the config option.

**Comment by Paul-Franklin** [comment]
I think what confused me is the fact that both dialogs
are getting a set_window call, but once I'd read as far
as the "display" method it became obvious.  Sorry.

**Comment by sam-m888** [comment]
Worked for me on Example.gramps and my personal Family Tree.

Thank you

**Pull request merged**
