### PR TITLE
Change to git.

### PR DESCRIPTION
**Pull request by daleathan**

### CODE REVIEW

**Comment by dsblank** [comment]
No you know what this XML id is for? Or should it just be removed?

**Comment by Nick-Hall** [comment]
The uid is a SourceForge username.  It was used by the svn2cl utility to generate a change log.  I think that we can remove it now.

The authors.xml file is also used by the About dialog, so we need to make sure it still works after the uid is removed.

**Comment by dsblank** [comment]
@daleathan Can you remove these lines completely and see if the dialog still works?

**Comment by daleathan** [comment]
I gather you meant that I should only removed the content of the field?

**Comment by daleathan** [comment]
Looks like the build failed because of the last commit.

**Comment by sam-m888** [comment]
@daleathan I've tested your PR against master and the About box does work.

**Comment by daleathan** [comment]
@sam-m888 Thanks, but I can not merge the PR, that's up to you guys :)

**Comment by dsblank** [comment]
@daleathan Thanks for checking the dialog. Can these UID's just be removed?

**Comment by daleathan** [comment]
@dsblank It will be a few weeks before I can check.

**Comment by daleathan** [comment]
No idea, I'll let you guys work this one out.

**Comment by sam-m888** [comment]
Done:  by Nick-Hall  who  committed: Remove SourceForge username from authors file (This was used by the svn2cl utility to generate a change log.) commit f125a982d65c02885ba110a3613e15b3ace34557 

https://github.com/gramps-project/gramps/commit/f125a982d65c02885ba110a3613e15b3ace34557

**Pull request closed without merging**
