### PR TITLE
Add spouses to the child listing in DAR and DDR

### PR DESCRIPTION
**Pull request by bertcarnell**
Add spouses to the child listing in the Detailed Ancestor Report (DAR) and the Detailed Descendant Report (DDR) for issues #9926, #8941, and #5698.

### CODE REVIEW

**Comment by sam-m888** [comment]
Tested both reports and works, Thank you 👍 

I've attached test results to the relevant issues.

DAR:
dar_content_tab_list-spouses-of-children-gramps-master

dar-comparison-of-results

DDR:
ddr_content_tab_list-spouses-of-children-gramps-master

ddr-comparison-of-results

**Comment by sam-m888** [comment]
Waiting on results of both:
-----------
* test/det_ancestor_report.sh 

-----------
* test/det_descendant_report.sh

**Comment by bertcarnell** [comment]
I will fix the "Ignoring unknown options".

**Comment by prculley** [comment]
I'll bet you waited (or are still waiting) a long time!  Looked to me like
those scripts would run Gramps over 8000 times, and produce as many files
to be examined.  Hope you have some time to do so 😀.

**Comment by sam-m888** [comment]
>> I will fix the "Ignoring unknown options".

Thank you.

>> I'll bet you waited (or are still waiting) a long time!

@prculley Yes it took all night! :)

BTW had worked out before running that it was going thru all possible
combinations of the report, but not that it was that many combinations!

**Comment by bertcarnell** [comment]
I am working on unit tests that will make checking the files easier for some subset of the 8000 cases and improve the code coverage I hope.  The purpose of the shell script seems to be a mostly operational check since no output is checked.  I may be able to make that better as well.  Once I have better unit test coverage, I'd like to refactor out the common parts of the DAR and the DDR to make maintenance easier.  Should I continue that work under this pull request, or would you rather just accept these simple changes first?

**Comment by prculley** [comment]
I think it would not be too hard to add an 'options' list using the
gramps/plugins/test/test_reports addreport method.  It would then be easy
to adjust options in the report_list for your report, perhaps to add a
couple of variations (all options, every even option, and every opp
option), that would give pretty darn good coverage.

The way it is now, the only default options are tested...

Paul Culley

**Comment by sam-m888** [comment]
>  Should I continue that work under this pull request, or would you rather just accept these simple changes first?

Lets keep it simple and accept this PR.

Thank you

**Pull request merged**
