### PR TITLE
Enhance information dialog to display simple tables

### PR DESCRIPTION
**Pull request by Nick-Hall**
* Enhance `InfoDialog` to display simple tables.
* Provide better formatting for the Import Statistics.
* Fix concatenation bug in Import Statistics.

### CODE REVIEW

**Comment by PushKK** [comment]
Can you add '\t' before every word and between colon and digit?

As example old code (in ru.po):
```
#: ../gramps/plugins/importer/importxml.py:283
#, python-format, python-brace-format
msgid "Families{colon}\t%d"
msgstr "Семей{colon}**\t\t\t**%d"

#: ../gramps/plugins/importer/importxml.py:284
#, python-format, python-brace-format
msgid "Sources{colon}\t%d"
msgstr "Источников{colon}**\t**%d"
```
In new code it may be:
`strng = '\t{label}:\t{new:d} ({unknown:d})\n'
`
Tabulation can align text for nice view:
Снимок экрана_2021-06-05_16-06-58

P,S. For me not work function 'need merge?':
```
        merge = False
        for key in self.keyorder:
            if self.data_mergecandidate[self.key2data[key]]:
                merge = True
                break
```

**Comment by Nick-Hall** [comment]
> Can you add '\t' before every word and between colon and digit?

I could put a tab before every word, but putting a tab between the colon and digits isn't going to work.  The number of tabs required will depend on the font.

> P,S. For me not work function 'need merge?'

Start with an empty family tree and then import the example database twice.

**Comment by PushKK** [comment]
1. Yes, in your new code tab not work...
2. Yes, in your new code Merge function work fine.

**Comment by PushKK** [comment]
I change for new code:
```
    def _extract_mergeinfo(self, key, obj, sec_obj):
...
        if key == PERSON_KEY :
            return _("  %(text)s - %(id)s with %(id2)s\n") % {
                        'text' : name_displayer.display(obj),
                        'id': obj.gramps_id,
                        'id2': sec_obj.gramps_id
                        }
        elif key == TAG_KEY :
            pass # Tags can't be merged

        else:
            return _("  %(text)s - %(id)s with %(id2)s\n") % {
                        'text' : self.key2string[key],
                        'id': obj.gramps_id,
                        'id2': sec_obj.gramps_id}
```
For this code

```
    key2string = {
        PERSON_KEY      : _('People'),
        FAMILY_KEY      : _('Families'),
...
```
must be move to 'class ImportInfo:' and add 'self.' to 'key2string[key]'.

**Comment by Nick-Hall** [comment]
I decided to enhance the `InfoDialog` class to display simple tables.  The result is the following:

ImportScreenshot

**Comment by PushKK** [comment]
Very nice.
I groupped object by type and change order of strings:
Person - 'old_ID' with 'new_ID'

Снимок экрана_2021-06-07_17-43-24

**Comment by PushKK** [comment]
Very nice.
I change order of strings. Now:
Person - 'old_ID' with 'new_ID'

Снимок экрана_2021-06-07_19-13-37

And groupped object by type:
Снимок экрана_2021-06-07_19-13-54

**Pull request merged**
