### PR TITLE
Show note type in the Notes plugin

### PR DESCRIPTION
**Pull request by Mattkmmr**
Show note type in Notes plugin (requested in [#0012402](https://gramps-project.org/bugs/view.php?id=12402))

### CODE REVIEW

**Comment by emyoulation** [comment]
I don't know if all of these are from the NoteGramplet but the one about Positional Arguments seems to be. When I looked at the .gpr.py file, it has a detached height & width parameter that I don't recall seeing elsewhere

Also, when you update the .gpr.py for version, could you also add author lines? (Some people opt to omit the email.)
Here are some samples:
```
authors = ["Donald N. Allingham", "Doug Blank"],
authors_email = ["don@gramps-project.org", "doug.blank@gmail.com"],
```

Warnings received when running Gramps from the Command Line
```
C:\Program Files\GrampsAIO64-5.1.4\gramps\plugins\gramplet\persondetails.py:64: DeprecationWarning: Gtk.Widget.override_font is deprecated
  self.name.override_font(Pango.FontDescription('sans bold 12'))
C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\NoteGramplet\NoteGramplet.py:67: DeprecationWarning: Gtk.Misc.set_alignment is deprecated
  label.set_alignment(0.0, 0.5)
C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\NoteGramplet\NoteGramplet.py:81: DeprecationWarning: Gtk.Image.set_from_stock is deprecated
  image.set_from_stock(icon, size)
C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\NoteGramplet\NoteGramplet.py:135: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  self.texteditor.modify_font(Pango.FontDescription("normal"))
C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\NoteGramplet\NoteGramplet.py:111: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  button = Gtk.Button(_("Save"))
C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\NoteGramplet\NoteGramplet.py:114: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  button = Gtk.Button(_("Abandon"))
```

**Comment by Mattkmmr** [comment]
@emyoulation The taceback is from the addon [NoteGramplet](https://github.com/gramps-project/addons-source/blob/master/NoteGramplet/NoteGramplet.py) not the built-in note gramplets which I'm changing here. The NoteGramplet addon is using 'detached_width' and 'detached_height' in its [gpr.py file](https://github.com/gramps-project/addons-source/blob/master/NoteGramplet/NoteGramplet.gpr.py#L11), but I don't know how things are handled with GTK and how to fix the DeprecationWarnings.

It's probably best to create an issue in Mantis Bug Tracker. Maybe it isn't even the addon that needs a change, but code handling gramplet detachment in Gramps.

**Comment by Nick-Hall** [comment]
I've added a commit that puts the page number next to the forward and back buttons?  What do you think?

I need to investigate the build failure.  It isn't related to this PR.

**Comment by Mattkmmr** [comment]
> I've added a commit that puts the page number next to the forward and back buttons? What do you think?

@Nick-Hall Good idea! 👍

**Comment by Nick-Hall** [comment]
OK.  I'll use my new version.

**Pull request merged**
