### PR TITLE
Note editor enhancements

### PR DESCRIPTION
**Pull request by Nick-Hall**
Add strikethrough and superscript/subscript support

### CODE REVIEW

**Comment by emyoulation** [comment]
image

Adds Superscript and Subscript controls to the Note Editor toolbar. Completing the feature will require adding icon files for these controls. (These 'actions' are not part of the Adwaita theme.)

Missing kde icons from base #580
https://github.com/numixproject/numix-icon-theme/issues/580

format-text-subscript
format-text-superscript

**Comment by emyoulation** [comment]
attached is a ZIP (since SVG is not a supported upload filetype) of the gnome-stencils-legacy.svg 
[gnome-stencils-legacy(super-sub).zip](https://github.com/gramps-project/gramps/files/6841798/gnome-stencils-legacy.super-sub.zip)

It has possibilities for format-text-subscript and format-text-superscript (2 variants for each)

image

Source of original SVG is [gitlab.gnome.org/GNOME/adwaita-icon-theme permalink](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/720b4c23046368a5ebb963f47349f4fbc01fda6e/src/symbolic/gnome-stencils-legacy.svg) :

**Comment by emyoulation** [comment]
I noticed that the patched Note Editor version has Subscript set to the ctrl-c keybinding!  Very weird and annoying?

**Comment by emyoulation** [comment]
When opening multiple Note Editors (such as when there is a Note gramplet and you open a normal Note Editor), then errors are echoed to the console:
```
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\GrampsAIO64 5.1.4>gramps~2.lnk
2021-07-28 15:12:20.213: WARNING: dummydb.py: line 1420: database is closed
2021-07-28 15:13:26.525: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>i
2021-07-28 15:13:26.527: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>b
2021-07-28 15:13:26.529: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>u
2021-07-28 15:13:26.529: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary>z
2021-07-28 15:13:26.530: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary><shift>z
2021-07-28 15:14:03.163: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>i
2021-07-28 15:14:03.164: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>b
2021-07-28 15:14:03.166: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>u
2021-07-28 15:14:03.167: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary>z
2021-07-28 15:14:03.168: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary><shift>z
```

**Comment by prculley** [comment]
The duplicate accelerator warning is not related to this PR.  It is due to the reuse of accel keys between the main window and the note editor.

**Comment by emyoulation** [comment]
I thought that might be the case but then wondered....

Should (and could) an add-on check to see if the hotkeys are already allocated and and not try to write over them? 

I hope VERY VERY much to find a way to change the Ctrl-C binding to the add objects to the Gramps Clipboard.  The use of Ctrl-C to grab selected text to the OS clipboard is so ingrained that the conflict causes constant productivity loss.

So if I found how to reassign the Gramps Object Clipboarding keybinding (to something like Ctrl-Shift-C), I'd hope that Gramps wouldn't step on that reassignment every time a gramplet launched.

**Comment by emyoulation** [comment]
Since GitHub has readme.md files (with its own extension of markdown) for many addons, maybe that should be the direction for markdown in Gramps Notes?

Maybe use an existing python library for our notes viewer with an extension for Gramps internal links.

Perhaps extend the .gpr to allow relative path help_url to point at local readme.md files... which open those files with the Note Editor. (I was going to mention the possibility of setting the help_url to the GitHub repository. But that might drive Traffic that would get the project in trouble with GitHub.)

Or, instead of distorting the .gpr, extend the Registration to detect Readme.md files in the plugins folder and offer available docs in 
the Plugin Manager. It might be easier to offer help there than to figure out how to interface help buttons for all the various add-on types. (Noting that even for Gramplet addon type, the Help buttons are only accessible when undocked.)

**Comment by geggi** [comment]
Any update on this enhancement? Back in 2021 emyoulation had commented about missing icons, which are now available:
https://github.com/numixproject/numix-icon-theme/pull/1425

**Comment by Nick-Hall** [comment]
I've modified the code to use the "format-text-subscript" and "format-text-superscript" icons if they are available in the icon theme.  If not "go-down" and "go-up" are used as fallbacks.

This is not ideal.  It would be nice if someone would create Adwaita style subscript and super script icons.

**Comment by geggi** [comment]
Adwaita style icons are now available: [239934](https://gitlab.gnome.org/Teams/Design/icon-development-kit/-/issues/87)

**Comment by Nick-Hall** [comment]
@geggi Thank you.  I've tested with the Numix icon themes.  When using Numix-Light the subscript and superscript icons are blue instead of grey.  Perhaps you could test this and raise an issue for us.

**Comment by emyoulation** [comment]
> I noticed that the patched Note Editor version has Subscript set to the ctrl-c keybinding! Very weird and annoying?

resolved in https://github.com/gramps-project/gramps/pull/1560

**Comment by emyoulation** [comment]
> When using Numix-Light the subscript and superscript icons are blue instead of grey. Perhaps you could test this and raise an issue for us.

2 variants of grey superscript and subscript icons were submitted in a zipped SVG template 2 years ago for evaluation. They were layered  into the gnome template. Using 2 of their icons (an 'a' and an 'ab' with a superscript/subscript '2' text.) 

https://github.com/gramps-project/gramps/pull/1266#issuecomment-882606754

**Pull request merged**
