### PR TITLE
Update Spanish translations

### PR DESCRIPTION
**Pull request by jcsaaver**
Update Spanish translations for Gramps 5.1.3 es.po

### CODE REVIEW

**Comment by sam-m888** [comment]
> Update Spanish translations for Gramps 5.1.3 es.po

Is this actually for Gramps 5.1.3 and Gramps master?

**Comment by jcsaaver** [comment]
Originally I translated the es.po file for version 5.1.2, but as 5.1.3 became available, I upeated the file and created this pull request.
If I did something wrong please let me know

**Comment by Nick-Hall** [comment]
The pull request should really be based on the _gramps51_ branch, but don't worry about it.  I'll merge it into both branches.

We currently don't have a Spanish translator, so let us know if you would like to volunteer for the role.

Do you have any experience of any web-based translation platforms such as Weblate or Transifex?

**Comment by jcsaaver** [comment]
I would like to help in what I can.
But I have not used those platforms.

**Comment by Nick-Hall** [comment]
@jcsaaver Thanks for the translation.  I have added you to the [Team](https://gramps-project.org/wiki/index.php/Team) page in our wiki.

**Pull request merged**
