### PR TITLE
Fixes for errors opening family tree when a backend is unavailable

### PR DESCRIPTION
**Pull request by Nick-Hall**
When the default backend is unavailable disable the new and
convert buttons.

When the selected tree backend is unavailable disable the connect
and convert buttons.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
The logic in this commit needs tidying up.

**Comment by sam-m888** [comment]
* Clean Gramps profile (no addons)
* Create a new (empty) BSDDB family tree (do not load it only "Close Window" on the FTM)
* In Edit>Preferences - "Family Tree" tab set SQLite as the default Database backend.
* Bring up the FTM and highlight the BSDDB family tree and press the "Convert" button
* Load the newly converted SQLite Family tree
* Attempting to bring up the FTM shows the Error Report Assistant.

> 58063: ERROR: grampsapp.py: line 143: Unhandled exception
> Traceback (most recent call last):
>   File "/home/grampsdev/aaSandbox/gramps/gramps/gui/dbman.py", line 274, in __selection_changed
>     self.__update_buttons(selection)
>   File "/home/grampsdev/aaSandbox/gramps/gramps/gui/dbman.py", line 348, in __update_buttons
>     if backend_type == _('Unavailable'):
> UnboundLocalError: local variable 'backend_type' referenced before assignment
>

**Comment by Nick-Hall** [comment]
@sam-m888 Thanks.  I have simplified the code and decided to set the default backend to 'bsddb' if unavailable.  The code which produced the error you reported has been removed.

Opening a database from the recent files list or on startup when "Automatically load last Family Tree" preference is set can still give an error.

**Comment by sam-m888** [comment]
Thanks. That's a better behaviour. +1

Related to issue [10465](https://gramps-project.org/bugs/view.php?id=10465)

**Comment by sam-m888** [comment]
The MongoDB addons gpr.py[1] file probably needs to be updated like the
postgresql[2] to check for the presence of Mongodb etc or else the addon
crashes with

66468: ERROR: grampsapp.py: line 143: Unhandled exception
Traceback (most recent call last):
  File "/home/grampsdev/aaSandbox/gramps/gramps/gui/dbman.py", line 987, in
__new_db
    self._create_new_db(dbid=dbid)
  File "/home/grampsdev/aaSandbox/gramps/gramps/gui/dbman.py", line 999, in
_create_new_db
    new_path, title = self.create_new_db_cli(title, create_db, dbid)
  File "/home/grampsdev/aaSandbox/gramps/gramps/cli/clidbman.py", line 310,
in create_new_db_cli
    newdb = make_database(dbid)
  File "/home/grampsdev/aaSandbox/gramps/gramps/gen/db/utils.py", line 81,
in make_database
    raise Exception("can't load database backend: '%s'" % plugin_id)
Exception: can't load database backend: 'mongodb'

[1]
https://github.com/gramps-project/addons-source/blob/maintenance/gramps50/MongoDB/mongodb.gpr.py
[2]
https://github.com/gramps-project/addons-source/blob/maintenance/gramps50/PostgreSQL/postgresql.gpr.py

**Comment by Nick-Hall** [comment]
> The MongoDB addons gpr.py[1] file probably needs to be updated like the postgresql[2] to check for the presence of Mongodb etc

Yes.  The MongoDB backend is not finished yet.  It is not suitable for production use.

**Comment by johnbickmore** [comment]
Travis build failing https://travis-ci.org/gramps-project/gramps/builds/359501495#L2012

> Yes. The MongoDB backend is not finished yet. It is not suitable for production use

Then why is it marked [stable](https://github.com/gramps-project/addons-source/blob/maintenance/gramps50/MongoDB/mongodb.gpr.py#L27) with a [download](https://github.com/gramps-project/addons/blob/master/gramps50/download/MongoDB.addon.tgz) available?

**Comment by Nick-Hall** [comment]
@johnbickmore Thanks.  I have fixed the build and removed MongoDB from the listing.

**Pull request merged**
