### PR TITLE
Error when checking option to add Quit to Taskbar

### PR DESCRIPTION
**Pull request by SNoiraud**
Fixes [#11290](https://gramps-project.org/bugs/view.php?id=11290)

### CODE REVIEW

**Comment by lordemannd** [comment]
when I clear or check the box for this feature I get these warnings in the Gramps log:
Warning: DisplayState: Exception occurred in callback function.
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.0-WORK\gramps\gen\utils\callback.py", line 405, in emit
    fn(*args)
  File "C:\Program Files\GrampsAIO64-5.1.0-WORK\gramps\gui\widgets\grampletbar.py", line 406, in cb_close_changed
    tablabel.use_close(config.get('interface.grampletbar-close'))
AttributeError: 'Label' object has no attribute 'use_close'
Warning: DisplayState: Exception occurred in callback function.
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.0-WORK\gramps\gen\utils\callback.py", line 405, in emit
    fn(*args)
  File "C:\Program Files\GrampsAIO64-5.1.0-WORK\gramps\gui\widgets\grampletbar.py", line 406, in cb_close_changed
    tablabel.use_close(config.get('interface.grampletbar-close'))
AttributeError: 'Label' object has no attribute 'use_close'

**Comment by SNoiraud** [comment]
You got this error for a specific gramplet or for all gramplets ?

**Comment by SNoiraud** [comment]
I can't reproduce this on linux

**Comment by lordemannd** [comment]
I don't see it on debian either,
this was on Windows and I was only clearing or marking the check box on the preferences dialog.

the box does get cleared or checked. but I happened to check the log file and found those messages.

I did not get the Error Reporting Wizard in the Gramps UI. No error reported to the user, only these messages in the log file.

**Comment by lordemannd** [comment]
Ah, I see, on Windows, Start Gramps, select Chart View and then edit preferences, then the messages go to the log file

**Comment by lordemannd** [comment]
And also on debian, starting Gramps from console, no DB loaded, select Charts View and then edit preferences.

**Comment by lordemannd** [comment]
excellent, tested on debian and windows, issue solved.

**Pull request merged**
