### PR TITLE
Fix creating new PostgreSQL database

### PR DESCRIPTION
**Pull request by dermoth**
1. Use all parameters from settings.ini as keyword arguments for PostgreSQL (port was missing, and other can be useful such as `sslmode='verify-full'`)
2. Fix Collation on PostgreSQL (Name each collation to prevent users form clobbering each other's collation)

### CODE REVIEW

**Comment by dermoth** [comment]
NB: this replaces PR #434

**Comment by Nick-Hall** [comment]
Updated to remove the character encoding from collation names as @jralls suggested.  Now the same names can be used in sqlite and postgres.

@dermoth Do we still need to create extra collations in postgres?

**Comment by Nick-Hall** [comment]
Merged parameter change in commit fd2af705e78d416995740360e4a3ef0db9ee65d7.

**Comment by Nick-Hall** [comment]
Merged fix for creating new PostgreSQL database in commit 8f69201a70a2cad039d01028edd23fd3a739e50f.

**Comment by Nick-Hall** [comment]
@dermoth I have added your latest changes to PR #434

**Pull request closed without merging**
