### PR TITLE
10049: tabs reorganization in narrative web.

### PR DESCRIPTION
**Pull request by SNoiraud**

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
This looks like a good idea to me.  I think it should be committed.

**Comment by SNoiraud** [comment]
Is it a good idea to backport it to 5.0 ?

**Comment by prculley** [comment]
I would think that this is not in the category of bug fixes; rather it
looks to me like an enhancement.  So by our new rules, it doesn't belong in
Gramps50...

My opinion of course.

Paul C.

**Comment by Paul-Franklin** [comment]
I was assuming that it was going into gramps50.  It never
occurred me to think otherwise.

As far as I'm concerned it's a bug fix, since it came about
after a user didn't see the options in the Privacy tab (since
that tab was not visible in the default report dialog), then
filed a bug report (10049) about people not being there.

So I'd say it belongs in gramps50.

My opinion of course.  8-)

**Pull request merged**
