### PR TITLE
Ru.po: small fix

### PR DESCRIPTION
**Pull request by PushKK**
1. Capitalize all first letter "семейное древо" > "Семейное древо",
2. Old words from Tips.xml:
Database Processing  > Family Tree Processing
Compare and Merge... > Merge...
3. Change:
"Местоположение" > "Место"
"граф" > "график"
4. Other small fix.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Please use [Weblate](https://hosted.weblate.org/projects/gramps-project) for translations in the _master_ branch.

**Comment by PushKK** [comment]
Thank you.

**Comment by Nick-Hall** [comment]
> Can you use Crowdin? It have good interface and very usefull.

In a recent mailing list [post](https://sourceforge.net/p/gramps/mailman/message/37280401/), I asked our translators for their opinions on online translation services.  None of them said that they preferred Crowdin.

> Weblate say me about many errors.

These look like problems in the source strings.

> Nontranslated words for translate - Gramps, GEDCOM.

Weblate provides a glossary for these.  Words can be specified as non-translatable.

**Comment by PushKK** [comment]
> These look like problems in the source strings.

Before on-line translating source strings must be checked.
I had see small errors in this string. As example - using "eg", "e.g.", ", eg", "Eg". I know it can write as "e.g." only (https://www.aje.com/arc/editing-tip-using-eg-and-ie/).
Whitespaces before word, two words "Gramps" in one string - this errors can fix developers only.

Can you or other developers check source string?

P.S. Crowdin have chat with developers and other translators, have TM and autotranslator, vocabulary:
Снимок экрана_2021-05-21_22-36-30

**Comment by Nick-Hall** [comment]
> Can you or other developers check source strings?

Yes.  We can change source strings if necessary.  They are often written by developers who don't speak English as their first language.

> P.S. Crowdin have chat with developers and other translators, have TM and autotranslator, vocabulary:

Weblate has similar features.

**Pull request closed without merging**
