### PR TITLE
Update and fix CSV import

### PR DESCRIPTION
**Pull request by dsblank**
This might be too late for gramps52, but this does fix the bug (overwrites firstname) and adds tags to all import types (in CSV), both mentioned in:

https://gramps.discourse.group/t/how-can-people-be-deleted-according-to-a-list/4511/13?u=dsblank

It is ok to apply to master.

### CODE REVIEW

**Comment by dsblank** [comment]
Looks like I broke a test. Fixing...

**Comment by emyoulation** [comment]
May I ask why the CSV parser allows adding a Source, but not a Citation? (Or maybe it does and the Wiki overlooks documenting it?)

**Comment by emyoulation** [comment]
Is it possible that the import was originally intended to parse a Full Name ("Surname, Given name")? If so, that would be a useful functionality to keep.

The date is passed through the Date string validator. Perhaps the Place was expected to be a Place Title? From before the Place hierarchy was implemented.

**Comment by dsblank** [comment]
> Is it possible that the import was originally intended to parse a Full Name ("Surname, Given name")? 

No, I don't think I every allowed that as it would be too complicated considering this is CSV.

> May I ask why the CSV parser allows adding a Source, but not a Citation? 

I can add that in the future if it isn't urgent for now.

> The date is passed through the Date string validator. Perhaps the Place was expected to be a Place Title? From before the Place hierarchy was implemented.

Is there a bug related to this?

**Comment by emyoulation** [comment]
No bug. It works fine. Just trying to discover the design approach. So I can determine whether it makes more sense to leverage it... or to embed functions if it is likely to evolve in an opposite direction.

**Comment by dsblank** [comment]
| May I ask why the CSV parser allows adding a Source, but not a Citation?

Looking at the code, I guess for simplicity (or was just based on my workflow). It does create a default citation, but doesn't allow you to use an existing one, or to provide values.

**Comment by dsblank** [comment]
All tests passing now.

**Comment by emyoulation** [comment]
> Looking at the code, I guess for simplicity (or was just based on my workflow). It does create a default citation, but doesn't allow you to use an existing one, or to provide values.

My common case when flowing data from a source via CSV is that they share the same citation. i.e., all the data was transcribed from pages 7-12 of that source. 

So maybe there could be an option to create a single shared citation for the source as an alternative to serialized citations?

**Comment by dsblank** [comment]
| So maybe there could be an option to create a single shared citation for the source as an alternative to serialized citations?

Good idea! I'll do this for an updated 5.2 once it is out.

**Comment by emyoulation** [comment]
please add 'tags' into the recognized headers.  This is what is used for export.

It outputs a CSV string. e.g. "ToDo, Complete, Imported 2024/01/11 10:18:02, Another tag"

Import by relabeling the 'Tags' to "tag" creates Tag named for the various combination. Such as named "ToDo, Complete, Imported 2024/01/11 10:18:02, Another tag" and "ToDo, Another tag"

**Review by Nick-Hall — APPROVED** [review]

**Pull request merged**
