### PR TITLE
fix Place Format Editor file save/load for difficult names

### PR DESCRIPTION
**Pull request by prculley**
Fixes [#10949](https://gramps-project.org/bugs/view.php?id=10949)

Bug Submitter noticed that when the place format editor name field contained international characters or non-safe for XML characters that Gramps would save it to place_formats.xml but fail (crash) when restarting Gramps.

The place format load routine was not robust against bad XML (so Gramps crashed) and the save routine would create bad XML.

I decided to use the minidom to create the XML file instead of doing manually (the standard Python library dealt with the name escaping).  I also wrote the file with 'utf-8' encoding (not standard on all systems).

P.s. the new error string is already in the .pot file.

### CODE REVIEW

**Comment by lordemannd** [comment]
looks good to me, tested on Windows with many of the problem characters. No start up failures!
good job!

**Comment by Nick-Hall** [comment]
@prculley Two pylint issues, but otherwise it looks good.  Using minidom provides a neat solution for small xml files.

**Comment by prculley** [comment]
Grrr...  The one thing I didn't change was the variable name for the file handle, and of course it is too short.
What do I use for an exception when I don't have any idea what error might be generated?  I tried a couple of ways to make the XML invalid, in addition to the original failure on bad encoding, and got wildly different exceptions.

**Comment by sam-m888** [comment]
Thank you

**Pull request merged**
