### PR TITLE
Openspan to rebase

### PR DESCRIPTION
**Pull request by janskarvall**
Superseded by Added support for open spans. #1124 PR.

Added open span support.

I chose to add separate phrases in gramps.pot rather than make complicated patterns in DateParser, and as I thought it be more safe, being unsure if the open span phrases always are sub phrases of the closed span phrase, see [line 1949](https://github.com/janskarvall/gramps/blob/openspan_to_rebase/po/gramps.pot#L1949) and  [line 1954](https://github.com/janskarvall/gramps/blob/openspan_to_rebase/po/gramps.pot#L1954).

Changed DateHandlerTest to [run tests for a static list of languages](https://github.com/janskarvall/gramps/blob/openspan_to_rebase/gramps/gen/datehandler/test/datehandler_test.py#L85) and to not stop at first failure.
Doing this required changes in the DateParser to accept date strings as output by DateDisplay. Thus I added the [_qual_match_str](https://github.com/janskarvall/gramps/blob/openspan_to_rebase/gramps/gen/datehandler/_dateparser.py#L411), [_mod_match_str](https://github.com/janskarvall/gramps/blob/openspan_to_rebase/gramps/gen/datehandler/_dateparser.py#L415), and [_cal_match_str](https://github.com/janskarvall/gramps/blob/openspan_to_rebase/gramps/gen/datehandler/_dateparser.py#L426).

Most languages passes the test, but some failes due to lacking _date_XX.py files in combination with that DateParser does not adapt to the target language (as DateDisplay does), and thus expects dates in 'en' language.
Some of the languages that lacks _date_XX.py should possibly fail, but as is they passes they are included among the tested languages.

The change affected all _date__XX.py and XX.po files. _date_ja.py also failed to match calendar names as the re.compile truncated the match at 200 characters, so I added [match_calendar](https://github.com/janskarvall/gramps/blob/openspan_to_rebase/gramps/gen/datehandler/_date_ja.py#L197).

I also had to make a small change to uk.po due to a clash for 'before date' and 'from date'.

### CODE REVIEW

**Comment by prculley** [comment]
Do any of the  date comparison functions in gen.lib.date need to be modified to deal with these?  And should we expand the gen.lib.test.date_test to check for comparisons with the new open spans?

**Comment by jralls** [comment]
This is even worse than before. @janskarvall you *must not* have any merge commits in a PR branch. A PR branch should have only the commits relevant to that PR.

More generally you shouldn't ever merge master into anything else: Master only gets maintenance and feature branches merged into it, and maintenance branches should be merged only into master. Never merge tags into anything, nor anything into feature branches. Doing otherwise turns history into spaghetti that's difficult to understand when using it to track down bugs.

With the master merge you've made this branch unrecoverable. You'll need to create a new branch off of maintenance/gramps51 and cherry-pick your two commits onto it, delete this branch, rename the new branch to openspan_to_rebase, and force-push to github. The following assumes that your personal github repo is remote `origin` and this one is remote `upstream`. Change the remote names in the pull and push commands as appropriate.
```sh
git checkout maintenance/gramps51
git pull --rebase upstream maintenance/gramps51
git checkout -b new_openspan
git cherry-pick 1589a05
git cherry-pick 41fd46a
git branch -D openspan_to_rebase
git branch mv new_openspan openspan_to_rebase
git push -f origin openspan_to_rebase
```

Once you've gotten this PR sorted out I highly recommend that you study [Professional Git](https://git-scm.com/book/en/v2) by Scott Chacun.

**Comment by QuLogic** [comment]
> With the master merge you've made this branch unrecoverable.

That is rarely true. It can be untangled with an interactive rebase (if you really believe it's tangled.)



> `git checkout maintenance/gramps51`

But this PR targets `master`?

**Comment by janskarvall** [comment]
Yes, it is targeting the master branch.

This is my first PR, and I really want to correct any mistakes I made.

I am currently assuming that the best commit history for a PR would be:

        master  ...-A-B-C
                                   \
        openspan           D

and that a less optimal could be:

        master  ...-A-B-C
                             \
        openspan      D-E

    in which case I should rebase resulting in:

        master  ...-A-B-C
                                   \
        openspan           D'-E'

    and which I believe could be simplified by squashing to:

        master  ...-A-B-C
                                   \
        openspan           E''

Now, I am not that lucky with the openspan branch, as I started out with 
branching of from the commit tagged v5.1.2. I did not understand at that 
time that this commit lived on the maintenance/gramps51 branch.

Preparing for the PR i merged master into openspan, made the final 
changes and committed. In order to not loose the history on the openspan 
branch, I made an openspan_to_rebase branch which points at the last 
commit on the openspan branch. After that I issued the PR, hoping that 
if it was accepted, most, if not all of the commit history could be 
removed by you.

What I could do, to clean up things, is to scrap all that work and start 
over, branching out openspan from master, make my changes, commit, and 
create a new PR.

By the way, I hope I did right when I forked gramps on GitHub into my 
GitHub account and pushed the openspan(_to_rebase) branch.

All git operations I made, I have done using Egit in eclipse (not the 
latest eclipse version though). This has worked for me so far.

And I am not that interested anymore to keep the old openspan branch 
history.

Jan

**Comment by janskarvall** [comment]
I'll have a closer look at that. /Jan

**Comment by jralls** [comment]
@QuLogic Yes, it's true that an expert git user can always rearrange and remove commits. Beginners like @janskarvall are another matter entirely.

**Comment by jralls** [comment]
@janskarvall,
```
   ...A--B--C
        \
         D--E
```
is fine because B and C are moving targets: Other people will commit as your PR is reviewed and as long as nobody else is working on the same stuff you are it's straightforward and normal to merge your commits into the mainline branch:
```
...A--B--C--F--G
    \         /
     D--E-----
```
> Preparing for the PR i merged master into openspan, made the final
changes and committed. In order to not loose the history on the openspan
branch,  I made an openspan_to_rebase branch which points at the last commit on the openspan branch. 

Was the last commit of `openspan` the merge from 5.1.3? That's history you want to lose, see my previous remarks.  Aside from that there's no history, just the one commit `1589a05` whose parent is a master commit from May 15th.

> After that I issued the PR, hoping that if it was accepted, most, if not all of the commit history could be
removed by you.

That's not nice. It's your job to create a branch that's ready to merge.

> What I could do, to clean up things, is to scrap all that work and start
over, branching out openspan from master, make my changes, commit, and
create a new PR.

It's not necessary to scrap anything except the extra merges. As @QuLogic points out there are several ways to get a clean branch--and you can certainly experiment with them on your own to help you learn git--but the procedure I provided above is the most direct. Just branch `new_openspan` off of master instead of gramps51:
```
git checkout master
git pull
git checkout -b new_openspan
...
```

I'm not an eclipse user so I can't help much with Egit. If it's not obvious what are the Egit equivalents to the procedure I've given you just open a terminal window and paste in the commands. Eclipse will recognize the changes and update itself.

After all of that, though, it looks like you have more work to do as this branch doesn't pass the date tests. Expand the checks and click the TravisCI details link to open the test output which includes the details of the failing tests.

**Comment by sam-m888** [comment]
closing as mentioned at top Superseded by Added support for open spans. #1124 PR.

**Pull request closed without merging**
