### PR TITLE
Update ukrainian translation

### PR DESCRIPTION
**Pull request by astappiev**
Hi,

I have updated translation to the Ukrainian language.

Unfortunately, some terms are ambiguous and to translate them better I need more context. I didn't find an easy way to use an updated translation file with Gramps (and I don't want to build it from sources). Maybe I will take a look after the next version is released and improve the translation.

Also some terms I can't understand how to properly translate them, e.g.:
* `manual|Merge_Families`, I do not understand how they used, do we need to translate them in the same way, like `manual|Об'єднати_родини`?
* `occupationplace`, we already have `Occupation place` and `occupation place` why do we need third term, how is it used and how we need to translate it?

Also with some terms, like `Ahnentafel` I'm not familiar. I left these strings not translated. May be someone with more experience in genealogy can do that later.

Best regards,
Oleh

### CODE REVIEW

**Comment by astappiev** [comment]
And for some reason, it looks like my PoEdit is using different line width, so it updated more lines than needed. If you know what I'm doing wrong I can update (the version I used is 2.2.4 free).

**Comment by Fedik** [comment]
hi, thanks for contribution,
please have a look the wiki page https://www.gramps-project.org/wiki/index.php?title=Translating_Gramps

> manual|Merge_Families

it not need to translate, since we do not have Ukrainian manual for now:
"these strings should only be translated if a wiki user manual is available in your language"

> Also with some terms, like Ahnentafel I'm not familiar

that is ok, there many strange terms :smile: 

> And for some reason, it looks like my PoEdit is using different line width, so it updated more lines than needed. If you know what I'm doing wrong I can update

Check this section https://www.gramps-project.org/wiki/index.php?title=Translating_Gramps#Updating_your_translation

Try update your translation with `--no-wrap` parameter, eg:
`msgmerge --no-wrap my-translation.po uk.po -o uk.po`

so it will be like this https://github.com/gramps-project/gramps/commit/8ccfa43e56f0541c9853615914c4d2347d3f0e75#diff-35d7b3e1399652b7d66811ddbeffe104

And for note, the translation used in the 5.1 version are located under maintenance/gramps51 branch .

**Comment by prculley** [comment]
Regarding 'occupationplace', the CSV importer mentioned in ../gramps/plugins/importer/importcsv.py:212 has a small table which allows the CSV import headings to be in English, or in your language, with several variations allowed.  I see that the table contains an error as it is, all of the translatable values should have been done in lower case.  In this case, the variations are English "occupationplace", translated "occupationplace", and translated "Occupation place" (which should be "occupation place".  If the concatenated word makes no sense in your language, skip it.

If you want to test your particular translation, you can use `msgfmt uk.po -o gramps.mo` and then copy the gramps.mo to where the other mo files are stored on your installation.  On my Ubuntu that is at "usr/share/locale/uk/LC_MESSAGES/gramps.mo"  on Windows it ends up at "C:\Program Files\GrampsAIO64-5.1.2\share\locale\uk\LC_MESSAGES\gramps.mo"

**Comment by Fedik** [comment]
I see the master uk.po also was without `--no-wrap` :smiley: 
Please update you file with:
```
msgmerge uk-your-translation.po uk.po -o uk.po
```

So it will use the same line width, and we will see the changes.

**Comment by astappiev** [comment]
@Fedik питання до тебе. Sorry anyone else, you will not be able to help anyway.

Визначення належності місць одного до одного, в англійский використовується `Enclosed by` | `Encloses`. В українському перекладі в більшості ці терміни не мали перекладу. Але якщо і мали переклад, то скореше за все не правильний, наприклад `Places enclosed by another place` перекладено як `Місця, розташовані поруч іншого місця` або `Gramplet showing the places that the active place encloses` як `Ґрамплет показує місця поруч з якими знаходиться активне місце`

Я пропуную перекласти наступним чином:
* Enclosed by - Оточене або Належить (я спочатки використовував перше, але здається належить подходить краще)
* Encloses - Оточує або Охоплює (те ж саме, охоплює здається краще)
* Places enclosed by another place - Місця, що належать іншому місці
* Gramplet showing the places that the active place encloses - Ґрамплет показує місця які охоплює активне місце

Ще одне запитання. Gramplet ми трансліюємо як Ґрамплет, але Gramps залишається як є. Як щодо інших мов, чи роблять вони транслітерацію назви?

Дякую

**Comment by astappiev** [comment]
> msgmerge uk-your-translation.po uk.po -o uk.po

And yes, this helps, now I see only my changes. Thanks.

What about `primary[pre]`, `primary[sur]`, `primary[con]` and other with the suffixes. Do we need to translate them, if yes, how?

**Comment by ennoborg** [comment]
For Ahnentafel, please check https://en.wikipedia.org/wiki/Ahnentafel
This page has a Russian translation, but I don't know if Russian and Ukranian are close enough for that to be useful for you.

**Comment by astappiev** [comment]
The direct translation to russian is similar to original german meaning. The problem is that I'm not sure that if we translate it, in the same way, to ukrainian someone will understand what we mean.

I'm related in any way to professional genealogists (so, I may be wrong and the word may have ukrainian translation), but as for me, it is easier when such terms left untranslated. Like, will do not translate many (most) technical terms.

**Comment by ennoborg** [comment]
Same here. I'm in The Netherlands, and my Gramps speaks German for this term.

**Comment by Fedik** [comment]
Ahnentafel sounds like shorter for "Hand written family tree" :smiley: 
Just leave it untranslated, there many such terms, same for LDS.

> primary[pre], primary[sur]

It seems some technical thing, I have skipped them.

> Enclosed, Enclosed by

Your suggestion sounds good to me :wink: 

> Gramplet ми трансліюємо як Ґрамплет, але Gramps залишається як є

I have not checked other languages for this, cannot say. I have leave it untranslated because it the APP name and it is an abbreviation https://uk.wikipedia.org/wiki/Gramps , if we translate abbreviation then it will be very fun to read :smile: .
I did not thought about it, for me it is fine English version. 

I have translate Gramplet because it one of  feature.

**Comment by astappiev** [comment]
Updated. Reduced number of lines from 4k to about 800.

**Comment by Fedik** [comment]
Thanks! Looks good to me.
If you want you can add your name to a list of translators at top of the file.
And it can be merged :wink:

**Pull request merged**
