### PR TITLE
Add option to hide ages for events after death

### PR DESCRIPTION
**Pull request by Nick-Hall**
This PR adds the option to hide the age in the person editor for events after death.

Read the [Calculating age for burials](https://gramps.discourse.group/t/calculating-age-for-burials) topic for further details.

### CODE REVIEW

**Comment by DaveSch-gramps** [comment]
Installed the PR and works great.

I am wondering if the default should be "True" which is the current scenario and expected by users.

**Comment by emyoulation** [comment]
Please identify the label text of the option for those of use who have not installed. Is the 'True' for a "Hide" option or its inverse, a "Show" option.

Either way, a "show" should be the default. Otherwise newbies may never find it.

**Comment by Nick-Hall** [comment]
The option is "Display ages for events after death".  I'll change the default to True so that it matches the current behaviour.

**Comment by emyoulation** [comment]
The other 2 options (in the "display" Preferences tab) are labeled "Show", not "Display"

Maybe the code starts with "Display" but the label is consistent in the GUI with "Show"?

**Comment by DaveSch-gramps** [comment]
> The other 2 options (in the "display" Preferences tab) are labeled "Show", not "Display"
> 
> Maybe the code starts with "Display" but the GUI label is consistent in the rest in the tab with "Show"?

The display age after death option will not become available until 5.2 and will display on the Data tab of a totally reworked configure.py file.

**Comment by cdhorn** [comment]
This one worked fine for me too.

**Pull request merged**
