### PR TITLE
8200: Person Relatives Tab should use the type from the relationship

### PR DESCRIPTION
**Pull request by SNoiraud**

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
Since there are now two variables, flagged for translation, when
a gramps.pot is made a comment will be generated suggesting
that the two be named variables instead.

**Comment by sam-m888** [comment]
Worked for me.  

relatives-gramplet-patched
relatives-gramplet-patched-2

**Comment by SNoiraud** [comment]
> Since there are now two variables, flagged for translation, when
> a gramps.pot is made a comment will be generated suggesting
> that the two be named variables instead.
OK. I'll do that.

**Comment by Paul-Franklin** [comment]
Looks fine to me.  Thank you.

**Pull request merged**
