### PR TITLE
Bump required Python version to 3.3

### PR DESCRIPTION
**Pull request by prculley**
To be consistent with #787 #788

### CODE REVIEW

**Comment by QuLogic** [comment]
3.3 is EOL; is there any reason not to bump to 3.4 at least?

**Comment by Nick-Hall** [comment]
Yes.  We should move to 3.5, but not in a maintenance branch.

**Comment by sam-m888** [comment]
- [ ] Update mention in Readme

**Comment by Nick-Hall** [comment]
> 3.3 is EOL; is there any reason not to bump to 3.4 at least?

@QuLogic The problem I have at the moment is that Travis CI fails when I upgrade to xenial.  Do you have any Travis experience?

**Comment by Nick-Hall** [comment]
There are two problems:

1. Ubuntu xenial doesn't have the _python3-pyicu_ package, but I'm not sure that we need it in the unit tests.

2. We are getting the following error:

> Failed to connect to Mir: Failed to connect to server socket: No such file or directory
> Unable to init server: Could not connect: Connection refused

I attempted to fix it by setting the DISPLAY environment variable, but had no luck.

**Comment by Nick-Hall** [comment]
The build is now passing, but pyicu is not installed and we are still getting the errors.

**Pull request merged**
