### PR TITLE
Speed up Place Reference Editor and Listview for enclose place

### PR DESCRIPTION
**Pull request by prculley**
Fixes [#11531](https://gramps-project.org/bugs/view.php?id=11531)

Bug submitter noted that enclosing a place was taking a very long time (minutes in some cases), if the place being added in the PlaceRef (enclosing place) already had a lot of references/subordinate places.

There were two issues that added to the time:

I note that the adding a PlaceRef to a place with the editor should really only trigger a modify-place signal when the actual place is modified, which would normally be seldom when adding an already present place as the enclosing place. If we fix this, the specific case would finish almost instantly.

If the actual enclosing place does get edited sending the modify-place signal (or as the code is now always sending it), we end up looking at all the references attached to the newly enclosing places, and sending view row updates to the other views (Events, Families, People). If there are a lot of these (in bug submitters case 1/2 of a very large tree) this can take a LONG time to execute. If we were to just mark the view dirty, we would skip this step. Of course then the view would have to be redrawn when the user next looked at it. But that is a LOT faster than thousands of row_updates.

I decided to fix both problems in this PR.  Only commit the enclosing place if it actually changed in the PlaceRefEditor, and to mark non-active views dirty if more than a few (20) handles to update.  So for smaller updates, the non-active view still gets row updates (as it does now), but when lots of changes are forthcoming, we mark dirty, and the (Person, Family, Event) view has to be rebuilt when next made active.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
It seems that this could be a potential problem in all of the reference editors.

**Comment by prculley** [comment]
You are right of course, however the other reference editors work on objects that usually don't have hundreds or thousands of backrefs, so they don't usually see the issue.  The change in Listview helps them also if they do end up changing more than 20 rows in an view.

**Comment by prculley** [comment]
Seems bug submitter likes this too https://gramps-project.org/bugs/view.php?id=11531#c58660

**Comment by romjerome** [comment]
Thank you! It works fine.

About performances and speed up, there is maybe the same type of issue on EventRef Editor. e.g., if I understand right profile analyse, something might be also improved (even with #1003 and modified listview) around `gramps/gen/lib/eventref.py:114(unserialize)`.

> 12675221 function calls (12360603 primitive calls) in 175.669 seconds
> 
>    Ordered by: cumulative time
>    List reduced from 5153 to 50 due to restriction <50>
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.000    0.000  175.669  175.669 profile:0(<code object <module> at 0xb71500c0, file "Gramps.py", line 27>)
>    1014/1    0.038    0.000  175.668  175.668 :0(exec)
>         1    0.000    0.000  175.668  175.668 Gramps.py:27(<module>)
>         1    0.000    0.000  174.543  174.543 gramps/grampsapp.py:498(main)
>         1    0.000    0.000  174.543  174.543 gramps/grampsapp.py:422(run)
>         1    0.595    0.595  173.867  173.867 gramps/gui/grampsgui.py:668(startgramps)
>         1    0.000    0.000  171.760  171.760 gramps/gui/grampsgui.py:789(do_activate)
>         1    0.001    0.001  171.760  171.760 gramps/gui/grampsgui.py:601(__init__)
>         1    0.000    0.000  146.090  146.090 gramps/gui/viewmanager.py:542(post_init_interface)
>         1    0.000    0.000  145.949  145.949 gramps/gui/viewmanager.py:952(__open_activate)
>         1    0.000    0.000  133.697  133.697 gramps/gui/viewmanager.py:995(_post_load_newdb)
>         1    0.000    0.000  129.843  129.843 gramps/gui/viewmanager.py:1003(_post_load_newdb_gui)
>         2    3.557    1.779  128.974   64.487 gramps/gui/viewmanager.py:874(__change_page)
>       6/5    0.001    0.000  120.470   24.094 gramps/gui/displaystate.py:625(modify_statusbar)
>       8/7    0.100    0.012  119.404   17.058 gramps/gui/utils.py:453(process_pending_events)
>       4/3    0.006    0.001  119.122   39.707 gramps/gui/views/listview.py:704(row_changed)
>         3    0.001    0.000  118.072   39.357 gramps/gui/views/listview.py:858(_button_press)
>         1    0.000    0.000  117.759  117.759 gramps/plugins/lib/libpersonview.py:430(edit)
>         1    0.000    0.000  117.624  117.624 gramps/gui/editors/editperson.py:130(__init__)
>         1    0.000    0.000  117.624  117.624 gramps/gui/editors/editprimary.py:60(__init__)
>         1    0.004    0.004  116.097  116.097 gramps/gui/editors/editperson.py:451(_create_tabbed_pages)
>        11    0.002    0.000  116.076   10.552 gramps/gui/editors/displaytabs/embeddedlist.py:78(__init__)
>         2    0.000    0.000  115.889   57.945 gramps/gui/editors/displaytabs/groupembeddedlist.py:62(__init__)
>         1    0.000    0.000  115.863  115.863 gramps/gui/editors/displaytabs/personeventembedlist.py:64(__init__)
>         1    0.000    0.000  115.863  115.863 gramps/gui/editors/displaytabs/eventembedlist.py:93(__init__)
>        11    0.003    0.000  115.858   10.533 gramps/gui/editors/displaytabs/embeddedlist.py:555(rebuild)
>         2    0.000    0.000  115.835   57.917 gramps/gui/editors/displaytabs/groupembeddedlist.py:76(construct_model)
>         1    0.028    0.028  115.824  115.824 gramps/gui/editors/displaytabs/eventrefmodel.py:91(__init__)
>       670    0.090    0.000  112.656    0.168 gramps/gui/editors/displaytabs/eventrefmodel.py:122(row)
>      9965    0.494    0.000  110.888    0.011 gramps/plugins/db/bsddb/read.py:677(_get_from_handle)
>       826    0.184    0.000  104.456    0.126 gramps/plugins/db/bsddb/read.py:685(get_person_from_handle)
>       670    0.356    0.001  102.785    0.153 gramps/gui/editors/displaytabs/eventrefmodel.py:167(column_participant)
>       670    0.218    0.000  102.428    0.153 gramps/gen/utils/db.py:254(get_participant_from_event)
>       826    0.107    0.000  102.261    0.124 gramps/gen/lib/person.py:241(unserialize)
>       826    7.927    0.010  101.010    0.122 gramps/gen/lib/person.py:277(<listcomp>)
>    510044   26.431    0.000   54.991    0.000 gramps/gen/lib/eventref.py:114(unserialize)
>    510044   19.807    0.000   38.187    0.000 gramps/gen/lib/eventref.py:59(__init__)
>       238    0.005    0.000   21.254    0.089 /usr/lib/python3.4/inspect.py:1346(stack)
>       238    0.081    0.000   21.248    0.089 /usr/lib/python3.4/inspect.py:1320(getouterframes)
>      4557    0.396    0.000   21.145    0.005 /usr/lib/python3.4/inspect.py:1282(getframeinfo)
>      4557    0.612    0.000   18.574    0.004 /usr/lib/python3.4/inspect.py:647(findsource)
>   1003/59    0.051    0.000   17.447    0.296 <frozen importlib._bootstrap>:2234(_find_and_load)
>   1003/59    0.061    0.000   17.434    0.295 <frozen importlib._bootstrap>:2207(_find_and_load_unlocked)
>    987/62    0.054    0.000   17.356    0.280 <frozen importlib._bootstrap>:1186(_load_unlocked)
>    942/59    0.019    0.000   17.315    0.293 <frozen importlib._bootstrap>:1122(_exec)
>    942/59    0.027    0.000   17.313    0.293 <frozen importlib._bootstrap>:1465(exec_module)
>   1068/62    0.011    0.000   17.258    0.278 <frozen importlib._bootstrap>:313(_call_with_frames_removed)
>   1020088   11.292    0.000   16.553    0.000 gramps/gen/lib/eventroletype.py:65(__init__)
>    141/78    0.004    0.000   15.403    0.197 :0(__import__)
> 4571/4557    5.985    0.001   15.115    0.003 /usr/lib/python3.4/inspect.py:601(getmodule)

One also reported that Find Possible Duplicate People can take 4 days with 200 000 individuals, but that's something else. 

For me, the speed up on PlaceRef Editor is just fine.
If need I could investigate and provide a testcase (data set) for EventRef (above profile).

**Comment by prculley** [comment]
I really cannot tell from that profile what is the issue, although I agree that it looks like a lot of calls to create the eventref object.  As usual this will be db dependent, in my db, I have very few persons or families with more than 6 or 7 events, and little or no sharing of the events.  So I don't see any obvious delays when doing Eventref editor.  It would be pretty easy to add the same type of fix to EditEventRef as was done to EditPlaceRef (Nick even suggested it might need doing).  I did not go there initially because I did not think that events would be shared to the same degree that places are.

Or there could be a different issue.

**Comment by romjerome** [comment]
I agree. It was a specific project related to occupation events. 
I started it with gramps 3.4.8 and after an update (gramps 3.4.9),  I got some performances issues around eventref. I used [a workaround](https://gramps-project.org/bugs/view.php?id=8466#c41268), and after the end of the project, as I did not often look at this database, I just keep it in mind for such testing! Maybe it was related to https://gramps-project.org/bugs/view.php?id=7770

Yes, this should be something else or an other PR.

This one is good. Thanks! :1st_place_medal:

**Comment by prculley** [comment]
I decided to add similar speedups to the Media, Event, and Repo reference editors.  Again, this only has effect when the reference editor makes no changes the primary object, when it avoids updates of the primary object and all the associated views.

**Pull request merged**
