### PR TITLE
8702 Update Map Service links for OpenStreetMap

### PR DESCRIPTION
**Pull request by sam-m888**
Enhances the mapservice lookup and resolves the broken links.

### CODE REVIEW

**Comment by sam-m888** [comment]
Should I also do this for gramps4.1 & 4.2?

**Comment by dsblank** [comment]
You mean make PRs? You don't have to... I have been using the `git cherry-pick` command and I think it works well for applying to multiple branches.

**Comment by dsblank** [comment]
Oh, but if the code is different, yes, different PR's would be preferred. Thanks!

**Comment by sam-m888** [comment]
No code changes in this particular case only URL updates for OpenStreetMap. :+1:

**Comment by dsblank** [comment]
Committed to gramps41, gramps42, and master. Thanks!

**Comment by sam-m888** [comment]
@dsblank Thanks. 

I did work it cherry-picking this morning :)

**Pull request merged**
