### PR TITLE
Geography: better management when closing the database

### PR DESCRIPTION
**Pull request by SNoiraud**
+ Avoid to build twice the map the first time we load the view
+ Manage correctly the map creation when closing the database (avoid crashes)
+ Remove print statements.
+ Better pylint score for all geography modules

### CODE REVIEW

**Comment by SNoiraud** [comment]
new-icons

**Comment by prculley** [comment]
Just a couple of minor comments:
As I recall the GeoAncestor view is released as an addon.  Did you consider adding the appropriate icons in the addon code?  The QuiltView.gpr.py has an example of how this is done by appending to the Gtk.IconTheme search path.

A lot of this appears to be a pylint cleanup, it is difficult to see the actual significant code changes in the "better management..." commit.  Nick has been reminding me not to do this for a while now.  He says to keep the pylint changes in a separate commit.

**Comment by SNoiraud** [comment]
> The QuiltView.gpr.py has an example of how this is done by appending to the Gtk.IconTheme search path.

Yes! I was looking for seach a functionality like this and only look at in the source code, not in the gpr.py
I'll do that in the addons source.

> A lot of this appears to be a pylint cleanup, ... keep the pylint changes in a separate commit.

Yes, I know that.  It was too late to reverse the code modification.

**Comment by Nick-Hall** [comment]
I've merged the commits that add two new icons for the geography descendant and ascendant trees as commit 
557c1c724a7a58da959ac623899afef404ab42d1.

However, I couldn't merge the remaining commit because of conflicts.

@SNoiraud If you resolve the conflicts, then I'll merge the remainder of this PR.

**Comment by SNoiraud** [comment]
I need to do some more testing before you merge.

**Comment by SNoiraud** [comment]
I need to do some more testing before you merge.
I need to add a patch following merge

**Comment by Nick-Hall** [comment]
OK.  No hurry.  Let me know when you are ready.

**Comment by SNoiraud** [comment]
I need to do some more testing before you merge.
I need to add a patch following merge. Some parts of geography didn't work anymore.
better pylint score.
I pushed the patchs, but they are not visible in the PR.
I think you can merge the remainder.

**Comment by Nick-Hall** [comment]
Rebased.

**Pull request merged**
