### PR TITLE
Fix bug 12710

### PR DESCRIPTION
**Pull request by grocanar**
I guess the code was written before the obect PlaceName exists.

### CODE REVIEW

**Comment by emyoulation** [comment]
Nice addition. 

Was there a Developer article in the Gramps MediaWiki or Sphinx documentation missing the newer PlaceName object?

**Comment by grocanar** [comment]
Hi
I guess the changes was on the moe of 4.2 version. 
here is a page in mediawiki 
 https://gramps-project.org/wiki/index.php/Place_Names_and_Titles

**Comment by emyoulation** [comment]
Thank you!

**Comment by Nick-Hall** [comment]
Rebased.

**Pull request merged**
