### PR TITLE
Change Add,Remove to New,Delete

### PR DESCRIPTION
**Pull request by ewongbb**
Re: bug [9229](https://gramps-project.org/bugs/view.php?id=9229).

Work In Progress as I think I might have others to fix; but would like to have some comments on this.

### CODE REVIEW

**Comment by prculley** [comment]
Just out of curiosity, why?  I personally think the current terminology is quite clear.

**Comment by Paul-Franklin** [comment]
@ewongbb What language do you run gramps in?

**Comment by ewongbb** [comment]
@prculley : this is in re: bug 0009229, and I'm using en-US

**Comment by Nick-Hall** [comment]
@ewongbb Changing _Remove_ to _Delete_ is a good idea in this case.  We use _Remove_ in the editors when we remove an object from a list without actually deleting it.

I'm not so sure about changing _Add_ to _Create_.  The bug report suggests _New_.

I suggest that you work on these two changes separately starting with _Delete_.

**Comment by Nick-Hall** [comment]
Delete renamed to Remove in commit 22e724366039ab104f14fbfdd63ca2c8be58d3fe.

The term "Delete" should be used when an object is deleted from the database. The term "Remove" should be used when an object is removed from a list, but not actually deleted.

I don't see much point in renaming "Add" to "New". It could be confusing for users who are happy with "Add" and "Share".

**Pull request closed without merging**
