### PR TITLE
fix bug 10052, relationship calculator fails (missing uistate param)

### PR DESCRIPTION
**Pull request by prculley**
bug was a missed edit during a general fixup of treemodels to add uistate...

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
I have duplicated this bug.

I concur this is the solution.  It should be committed.

(If it were me, I'd have just committed it, but you are not me.)

**Comment by Paul-Franklin** [comment]
Remember to commit it only to maintenance/gramps50, since
the transfer to master will be done by a "senior developer."

**Comment by prculley** [comment]
@Nick-Hall Do I have to close and restart this PR, since it was originally aimed at master, and now should be aimed at gramps50?  Or is there some way to shift it to the other branch?

**Comment by Nick-Hall** [comment]
@prculley You can use the "Edit" button next to the title to change the base branch.

**Comment by Nick-Hall** [comment]
Fixed in commit 22fb1ab254819f1a3c7d098246830572c789f540.

**Comment by Paul-Franklin** [comment]
@NIck-Hall ISTM it was fixed in "5.0.0-alpha3" (and not ...2).

https://gramps-project.org/bugs/view.php?id=10052

**Comment by Nick-Hall** [comment]
@Paul-Franklin Thanks.  I have changed it to alpha3.

**Pull request closed without merging**
