### PR TITLE
Fix french translation

### PR DESCRIPTION
**Pull request by khrys63**
Fix french translation

### CODE REVIEW

**Comment by romjerome** [comment]
@sam-m888 
It sounds good.

Thank you, @khrys63 !

**Comment by Nick-Hall** [comment]
Is this really intended for _master_ instead of _gramps50_?

**Comment by romjerome** [comment]
@Nick-Hall is right.

Note, I made a pull request (quickly closed ...) which is showing a possible issue between 
_master_ and _gramps50_!

Content of '_fr.po_' file should be very close between both branches,
but the pull request #680 is maybe pointing out a possible [missing reference](https://github.com/gramps-project/gramps/pull/680/files#diff-42793ab00dcd448b33776fc86e5eaaf4R39198).

**Comment by romjerome** [comment]
Maybe we could also still try commands like :
`$ cd po`
`$ intltool-update -m`
inherited from previous GNOME ecosystem and still conform with current gramps' template for translation strings.

**Comment by Nick-Hall** [comment]
There were only 4 strings changed in the _gramps50_ branch, so I merged them manually.

**Pull request merged**
