### PR TITLE
Update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by tiansworld**
Fixed some of the fuzzy translations and wrong translations, and also translated some new strings.
Please review.

### CODE REVIEW

**Comment by tiansworld** [comment]
Hello, Gramps guys,
I am sorry that I made 2 commits in one PR. 
While the first commit is still waiting for merging, it's been very long since I committed it. Then I want to contribute more translation, also I found some apparent mistakes in the translation. So I corrected them and updated the translation and committed yesterday. I thought it would be another PR, but they are in one PR.

I hope this is OK to you.

**Comment by tiansworld** [comment]
> It's fine, amending PRs that way is routine. In fact if you want to you can squash the commits together and force-push. Then no one will know about the mistakes.

Thank you very much. 
In fact the 2nd commit contains lots of updates, it's a big update. I think those translation mistakes were made long time ago(though not by me). I came across them when I tried to export a family report.

I've considered to squash them at first, but I was afraid that something may gone wrong or too complicated to me due to my entry level git skills. So I just forced push that.

**Comment by tiansworld** [comment]
> If they're not corrections to the first commit then it's probably better to leave it as two; either way it's your choice, it makes no difference to us.

Thanks. I got it.

> 
> Note that if you're adding commits, not changing or replacing existing ones, you can just push, no `-f` needed.

I was rejected when I first did a push without -f option, then git failed to do so and the hint is:
`
#Updates were rejected because the tip of your current branch is behind its remote counterpart. 
#Integrate the remote changes (e.g. hint: 'git pull ...') before pushing again.
#See the 'Note about fast-forwards' in 'git push --help' for details.
`

I tried `git pull`, it tells me:
 "There is no tracking information for the current branch.
Please specify which branch you want to merge with".

Also I don't think the tip of my branch is behind that counterpart on my github repo is true, because I just change the translation on my local branch. The counterpart branch on github just stays on my last commit(1st). Hopefully I understand this right.

At last I use the -f option, and it worked.

**Comment by prculley** [comment]
> I was rejected when I first did a push without -f option, then git failed to do so and the hint is:
> `#Updates were rejected because the tip of your current branch is behind its remote counterpart.`
> `#Integrate the remote changes (e.g. hint: 'git pull ...') before pushing again.`
> `#See the 'Note about fast-forwards' in 'git push --help' for details. `
> 
This occurs when something is different on the remote branch than the current one, often when additional commits have been added remotely, but sometimes when the top commit has a different hash than the ones in the local.
> I tried `git pull`, it tells me:
> "There is no tracking information for the current branch.
> Please specify which branch you want to merge with".
You probably need to do a "git pull origin/workl10n"
> 
> Also I don't think the tip of my branch is behind that counterpart on my github repo is true, because I just change the translation on my local branch. The counterpart branch on github just stays on my last commit(1st). Hopefully I understand this right.
> 
> At last I used the `-f` option, and it worked.
> 
> By the way, I often do `git pull` on upstream/maintenance/gramps51 branch and `git rebase gramps51` on my working branch.
If I understand how git works (a questionable assumption), rebasing the local branch causes the commit hash on your commits to change.  So this is the reason that git would not allow 'push' without the -f flag; neither of your new local commits matched the commit on the remote branch anymore.

**Comment by jralls** [comment]
The `git pull` failed because your `workl10n` branch doesn't have a remote associated with it, so you needed to say
`git pull tiansworld workl10n`, assuming that `tiansworld` is the remote associated with your personal GitHub account. 

Paul is correct that rebasing will change the hashes of your commits and does make force-pushing the right thing to do. It's a good thing that the pull failed, it would have wanted to make a merge commit, and letting it do that would have made a mess.

**Comment by tiansworld** [comment]
Thanks to both of you.
So if I try to commit the third one with `rebase` be done first, then I will have to use `-f` again. That's OK.

**Comment by Nick-Hall** [comment]
@tiansworld Is this ready to merge?  Did you want to add anything or squash the commits first?

**Comment by tiansworld** [comment]
On 15/5/2021 12:23 am, Nick Hall wrote:
> @tiansworld Is this ready to merge?  Did you want to add anything or squash the commits first?
> 

Hi Nick,
It's ready to merge.

I wanted to add another commit, but I don't think I can do it till next
weekend. And the current two commits don't need to be squashed.


-- 
Regards,

Tiansworld
Fedora Project Contributor

**Comment by Nick-Hall** [comment]
@tiansworld Thanks. I have just merged this PR.

**Pull request merged**
