### PR TITLE
Improve progress indications for Gedcom export

### PR DESCRIPTION
**Pull request by prculley**
Several things fixed:
- export  assistant updated to show textual progress steps ('writing individuals', 'writing families' etc.)
- export assistant fixed to make popups visible (originally set for incorrect transient parent so they were behind the dialog), affects the popup progress for preview button, and an error dialog.
- updatecallback changed to show the first progress step
- updatecallback changed to allow textual progress text updates
- Gedcom export changed to give finer granularity to progress indication (originally 5 steps)

The idea was to give the user more feedback that something was actually happening on large trees.  There are still some long delays with no feedback, if filters are used; the filter prep times can be long with big trees.

### CODE REVIEW

**Comment by sam-m888** [comment]
Also see: [6958](https://gramps-project.org/bugs/view.php?id=6958) Windows flags Gramps "not responding" during large GEDCOM exports

**Comment by sam-m888** [comment]
> The idea was to give the user more feedback that something was actually happening on large trees.

Yes the feedback was reassuring as when tested  with a 10K person GEDCOM export [1]**without the patch** the main Gramps window would gray out for a while like it had hung, **were as with the patch** no graying out of the main Gramps window occurred and the same export felt quicker.  (Note: Did not test using filters, only did full export of familytree)

**Comment by sam-m888** [comment]
Thank you

**Comment by romjerome** [comment]
Note, a large change have been [commited on gramps master](https://github.com/gramps-project/gramps/commit/4c010a94e40727506fe49dc7cd4c38e500e59b61) branch!

**Comment by prculley** [comment]
@romjerome 
Seems the 'Update branch" button on Github does not do a rebase as I expected.  I had pushed it to trigger a fresh Travis build.  Did not see any obvious effect in the changed files list, so thought it was ok.

Probably would still have been ok if we had done a 'Rebase and Merge" option on the Merge" button on Github instead...

Next time I want to do a rebase, I'll do in on my machine with git and then do the forced upload.

**Comment by Nick-Hall** [comment]
@prculley Yes, a local rebase followed by a forced push would be better.

**Comment by romjerome** [comment]
Yes, it was just an observation.
I got the same problems (merge vs rebase).

No problem, just a new commit revision.


Thanks.


--------------------------------------------
En date de : Mer 25.1.17, Paul Culley <notifications@github.com> a écrit :

 Objet: Re: [gramps-project/gramps] Improve progress indications for Gedcom export (#329)
 À: "gramps-project/gramps" <gramps@noreply.github.com>
 Cc: "romjerome" <romjerome@yahoo.fr>, "Mention" <mention@noreply.github.com>
 Date: Mercredi 25 janvier 2017, 18h55
 
 @romjerome
 
 Seems the 'Update branch" button on Github does not
 do a rebase as I expected.  I had pushed it to trigger a
 fresh Travis build.  Did not see any obvious effect in the
 changed files list, so thought it was ok.
 Probably would still have been ok if we had done a
 'Rebase and Merge" option on the Merge" button
 on Github instead...
 Next time I want to do a rebase, I'll do in on my
 machine with git and then do the forced upload.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Pull request merged**
