### PR TITLE
Sort AIO prerequisites + remove unneeded

### PR DESCRIPTION
**Pull request by a-andre**
* intltool and subversion are unneeded
* mingw-w64-x86_64-osm-gps-map was there twice

### CODE REVIEW

**Comment by a-andre** [comment]
`requests` is installed once via `mingw-w64-x86_64-python-requests` and once with `pip install`. The later can probably be removed, but I wasn't sure.

**Comment by emyoulation** [comment]
Does the AIO check Windows version before attempting install? 
A user confirmed (on Discourse) the [PortableApps observation](https://portableapps.com/comment/256656#comment-256656) that [5.2.0 is incompatible with Windows 7 Pro 64bit](https://gramps.discourse.group/t/windows-7-x64-support/5108).

If that is a planned deprecation, where is the incompatibility detailed? (For linking in the Windows alternative downloads page.)

> From PortableApps [download details](https://portableapps.com/apps/education/gramps_portable#download_details):
> Windows 8, 10, 11 (64-bit Only)
     (Windows 7 64-bit: [5.1.6](https://portableapps.com/downloading/?a=GrampsPortableLegacyWin7&s=s&p=&d=pa&n=Gramps%20Portable&f=GrampsPortableLegacyWin7_5.1.6_Rev_2.paf.exe), Windows 7/8/10 32-bit: [5.1.5](https://portableapps.com/downloading/?a=GrampsPortableLegacyx86&s=s&p=&d=pa&n=Gramps%20Portable&f=GrampsPortableLegacyx86_5.1.5.paf.exe), Windows XP/Vista: [3.4.9](https://portableapps.com/downloading/?a=GrampsPortableLegacy3&s=s&p=&d=sfpa&n=Gramps%20Portable&f=GrampsPortableLegacy3_3.4.9.paf.exe))

**Comment by Nick-Hall** [comment]
> Does the AIO check Windows version before attempting install? Does it refuse to install on known incompatible OS versions?

Yes, but it's out of date.  I'll increase the minimum version requirement to Windows 8.1 64-bit.

**Comment by Nick-Hall** [comment]
Rebased.

**Pull request merged**
