### PR TITLE
DBAPI: PostgreSQL crash

### PR DESCRIPTION
**Pull request by bpisoj**
Fixes #0010071

### CODE REVIEW

**Comment by johnbickmore** [comment]
https://github.com/GenealogyCollective/gprime/commit/9f8170badb5443ed23b2cdcdbb07996e41766293

**Comment by Nick-Hall** [comment]
> Fixes #0010071.

In the commit message, leading zeros are not required in the bug number.

**Comment by prculley** [comment]
Are we allowed to merge our own PRs?

**Comment by bpisoj** [comment]
In my defence riginal author commited them in their code.

**Comment by Nick-Hall** [comment]
@prculley Would you mind letting me merge a few first to test the new Mantis source integration?

@bpisoj I doesn't really matter.  For source integration to work, please check that either your Mantis real name or email matches your git name or email.

**Pull request merged**
