### PR TITLE
Improve and correct the Simplified Chinese translation

### PR DESCRIPTION
**Pull request by tiansworld**
Hello guys,
This update contains mainly improvements and corrections to the existing translation(Correct the typos, mistakes, mix of translatable English words, also rephrase some of the sentences to make them smooth in Chinese).
Please review it.

Also please have a look at #1221, I want to know if I am right or not, so I can change the affected files too.
Thanks a lot.

For the rest 10% of the untranslated strings, I think they will spend me more time. Most of them are not easy to understand and translate without seeing them in the GUI. While finding their positions in the GUI is another challenge. But I will try my best.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Thanks.  Simplified Chinese is now 91.63% translated.

**Comment by Nick-Hall** [comment]
> For the rest 10% of the untranslated strings, I think they will spend me more time. Most of them are not easy to understand and translate without seeing them in the GUI. While finding their positions in the GUI is another challenge. But I will try my best.

@tiansworld If you let me know the strings you are having problems with, I'll create some screenshots for you.

**Comment by tiansworld** [comment]
> @tiansworld If you let me know the strings you are having problems with, I'll create some screenshots for you.

@Nick-Hall Thank you.

Take this for example, "Place %(id)s with %(id2)s", it's  in line 263 of gramps/plugins/importer/importxml.py. The comment of the source function says:"Extract info from obj about 'merge-candidate'...", so I guess it is from import and merge tool. But I couldn't find it from "Import and Merge Tool".
It's a little ambiguous to me, I can understand it as "a place ID number id, which contains the second id number id2?" or "A place, with id number id and id2?".
I need to know what is displaying around this string, or even the whole dialog, to translate it appropriately.

I will meet some other strings alike later, I will be much appreciate if you can teach me how to create a screenshot or find the desired string in GUI efficiently. I mean not the way I am currently using, by opening Gramps, then find and try through the menus/settings/views etc. So I can handle them by myself in the future.

**Comment by Nick-Hall** [comment]
@tiansworld I have uploaded a screenshot to Weblate [here](https://hosted.weblate.org/translate/gramps-project/gramps/en/?checksum=d23f12e040d05e65).

In this case you would have to look at the code and realise that the [`ImportInfo`](https://github.com/gramps-project/gramps/blob/master/gramps/plugins/importer/importxml.py#L187) class holds information about an import and the method [`info_text`](https://github.com/gramps-project/gramps/blob/master/gramps/plugins/importer/importxml.py#L277) constructs the message.  Then you would look at the references for `info_text` to find that it is called by the [`DbLoader`](https://github.com/gramps-project/gramps/blob/9c29b8e2b528a71b70f84212e6bb0ae61033d422/gramps/gui/dbloader.py#L141) and then the [`ViewManager`](https://github.com/gramps-project/gramps/blob/9c29b8e2b528a71b70f84212e6bb0ae61033d422/gramps/gui/viewmanager.py#L947).  In the GitHub editor references can be found by just clicking on the method and looking in the "References" tab.

Unfortunately, this process is made easier with some coding experience and knowledge of the Gramps codebase.  Let me know if you need help with any other strings.

**Comment by jralls** [comment]
> In this case you would have to look at the code and realise that the ImportInfo class holds information about an import and the method info_text constructs the message. Then you would look at the references for info_text to find that it is called by the DbLoader and then the ViewManager. In the GitHub editor references can be found by just clicking on the method and looking in the "References" tab.

That's too much to ask of translators, few of whom know much about programming. `xgettext` will extract comments if you tell it to, but we do so only for [glade](https://github.com/gramps-project/gramps/blob/master/po/update_po.py#L340) and bizarrely [C header](https://github.com/gramps-project/gramps/blob/master/po/update_po.py#L440) files, not [Python](https://github.com/gramps-project/gramps/blob/master/po/update_po.py#L426). Common practice is to pass something like [`--add-comments=Translators`](https://www.gnu.org/software/gettext/manual/gettext.html#index-_002d_002dadd_002dcomments_002c-xgettext-option) to xgettext and have comments like
```
# Translators: This is part of the import results report, it shows the number of places imported followed by the 
# number of references to those places in parentheses.
```
On any string that isn't obvious without examining the code or where an English word has multiple meanings and which one isn't apparent from the context of the msgid.

**Comment by Nick-Hall** [comment]
> Common practice is to pass something like --add-comments=Translators to xgettext

We specify the `-c` flag rather than `--add-comments` for the python files.  In fact, I recently moved some comments in [this commit](https://github.com/gramps-project/gramps/commit/1423662e33d9468b36ee343498bd7d986ee4a13c) beacuse they were confusing for translators.  Specifying a tag would be much better.  I'll investigate the impact.

**Comment by Nick-Hall** [comment]
A custom search in Weblate for "has:note and language:en and not note:translator" reveals that there are 335 source code comments in the po files which do not contain the word "translator".   Most of these are irrelevant to translators, but unfortunately some are intended for them.

I'll go through the search results in more detail tomorrow.

**Comment by tiansworld** [comment]
> In this case you would have to look at the code and realise that the [`ImportInfo`](https://github.com/gramps-project/gramps/blob/master/gramps/plugins/importer/importxml.py#L187) class holds information about an import and the method [`info_text`](https://github.com/gramps-project/gramps/blob/master/gramps/plugins/importer/importxml.py#L277) constructs the message. Then you would look at the references for `info_text` to find that it is called by the [`DbLoader`](https://github.com/gramps-project/gramps/blob/9c29b8e2b528a71b70f84212e6bb0ae61033d422/gramps/gui/dbloader.py#L141) and then the [`ViewManager`](https://github.com/gramps-project/gramps/blob/9c29b8e2b528a71b70f84212e6bb0ae61033d422/gramps/gui/viewmanager.py#L947). In the GitHub editor references can be found by just clicking on the method and looking in the "References" tab.
> 

Thanks, I think you provide me a new way of tracking strings. My Python knowledge is more or less like my Deutsch level, I can read and understand a few of words(variables/functions), even can guess very simple sentences(classes/methods), of course reading a passage(block) of novel(whole source file) is impossible. So the process you suggested above is worth to try. Though it's a little hard at the moment.

**Comment by tiansworld** [comment]
> In this case you would have to look at the code and realise that the [`ImportInfo`](https://github.com/gramps-project/gramps/blob/master/gramps/plugins/importer/importxml.py#L187) class holds information about an import and the method [`info_text`](https://github.com/gramps-project/gramps/blob/master/gramps/plugins/importer/importxml.py#L277) constructs the message. Then you would look at the references for `info_text` to find that it is called by the [`DbLoader`](https://github.com/gramps-project/gramps/blob/9c29b8e2b528a71b70f84212e6bb0ae61033d422/gramps/gui/dbloader.py#L141) and then the [`ViewManager`](https://github.com/gramps-project/gramps/blob/9c29b8e2b528a71b70f84212e6bb0ae61033d422/gramps/gui/viewmanager.py#L947). In the GitHub editor references can be found by just clicking on the method and looking in the "References" tab.
> 

Thanks, I think you provide me a new way of tracking strings. My Python knowledge is more or less like my Deutsch level, I can read and understand a few of words(variables/functions), even can guess very simple sentences(classes/methods), of course reading a passage(block) of novel(whole source file) is impossible. So the process you suggested above is worth to try. Though it's a little hard at the moment.

**Comment by tiansworld** [comment]
> ```
> # Translators: This is part of the import results report, it shows the number of places imported followed by the 
> # number of references to those places in parentheses.
> ```
> 
> On any string that isn't obvious without examining the code or where an English word has multiple meanings and which one isn't apparent from the context of the msgid.

Yes, I agree.
But having these kind of comment is better than having nothing in the code. They will be the second clue for experienced translators.

For weblate single string mode, it's good to include these comment in the 'String information' on the right side of the page, but they are not visible in Zen mode.

**Comment by Nick-Hall** [comment]
> Though it's a little hard at the moment.

As @jralls said, you are not expected to understand the code.  Let me know if you would like more screenshots.  They will be helpful to other translators as well.

**Pull request merged**
