### PR TITLE
Add a config.reset() to restore to factory settings

### PR DESCRIPTION
**Pull request by dsblank**
Now you can:

```python
from gramps.gen.config import config
config.reset()
```
which will reset to the defaults, ignoring all previously set values, and loaded values from config files.

### CODE REVIEW

**Comment by prculley** [comment]
Did you mean to add a second reset() routine?  There was one there just above where you added yours.

**Comment by Paul-Franklin** [comment]
Insofar as I understand it, this p.r. might satisfy
https://gramps-project.org/bugs/view.php?id=7961

**Comment by dsblank** [comment]
@prculley No, I missed that. I'll take a look. Thanks!

**Comment by dsblank** [comment]
Closing, as I already had a method named reset that did exactly this, only better.

**Pull request closed without merging**
