### PR TITLE
datehandler and relationship calculator with de_AT

### PR DESCRIPTION
**Pull request by cedecode**
- This should finally solve the datehandler issue in #1264. Thank you @prculley and @Nick-Hall!
- I also found a solution for the error mentioned in the same thread (`WARNING: relationship.py: line 2318: Family relationship translator not available for 'de_AT'. Using 'english' instead.`). New `rel_de_AT.py` contains some minor differences between de and de_AT which are commented in line #32.
- added: the current de_AT.po from weblate, which is not mandatory for there problems here.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Thanks.

Please remove the po file.  Translation changes should be made in Weblate.

You also have some trailing whitespace.

**Comment by cedecode** [comment]
I have re-pushed without the po file and removed some blanks.

**Comment by cedecode** [comment]
Dear @Nick-Hall ,
could you please check if you can remove the bug label and merge?

**Comment by Nick-Hall** [comment]
Thanks for the reminder. I don't see an issue with merging this now.

**Pull request merged**
