### PR TITLE
0008639: check buttons misaligned in remove unused objects dialog

### PR DESCRIPTION
**Pull request by ennoborg**
Hacked removeunused.glade to correct the alignment of the check buttons. Needs to be applied to 4.1 and 4.2 too, but since this is my 1st pull request, and I'm not comfortable with back porting yet, I send it for master only now.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
The halign property should be set to "start" rather than "left".  You also seem to have included a few extra commits by mistake.

**Comment by ennoborg** [comment]
Corrected halign property as asked. The other commits are the result of a merge conflict when I synced my fork. I removed all associated changes in files, but have no idea how to get rid of the commits, other than rebasing this branch, or something like that. That's beyond my capabilities right now, so I hope that the compare can convince you, or you can tell how to omit commits from the pull request. I haven't found a way to do that yet.

P.S. I made a similar change in 4.1. Wanna have that?

**Comment by Nick-Hall** [comment]
You would normally need to rebase the pull request. However, I have applied your patch to gramps42 b8b186d and master 41cfe9f.

**Comment by ennoborg** [comment]
Thanks. I will try to figure out the rebase next time. I found this:

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Pull request closed without merging**
