### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/gramps-project/gramps/) for Gramps/gramps.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by tosky — DISMISSED** [review]
I've removed this change.

**Comment by tosky** [comment]
This is not working. Changes are immediately accepted in Weblate, that's a departure from the previous model.

You may argue you can always review and change them here, but it means having two ways were to look for translations. If I mark a translations as needed changes here, I need to go back to weblate as well.

**Comment by Nick-Hall** [comment]
@tosky There were two changes to the French translation which broke the build.  I fixed them in Weblate.

The problem with making changes here is that we would need to re-synchronise Weblate afterwards.

It is disappointing that Weblate commits changes with warnings which make break the build.

**Comment by tosky** [comment]
I updated the Italian change in weblate, the last  version should be fine (basically no changes)

**Pull request merged**
