### PR TITLE
Fix typo in configure

### PR DESCRIPTION
**Pull request by SNoiraud**
Fixes #11665

### CODE REVIEW

**Comment by romjerome** [comment]
Maybe an additional [complement](https://gramps-project.org/wiki/index.php/Coding_for_translation#Changing_translated_text_message_in_the_source_code)?
`sed -i 's/specifed/specified/g' *.po`
This should also fix entry (msgid) on all translation file.

**Comment by SNoiraud** [comment]
Yes, you are right. done

**Comment by lordemannd** [comment]
maybe not important, but in most/all files this line "Specifed tag will be added on import.\n"
is changed to "specified tag will be added on import.\n"

The spelling was corrected but the upper case "S" was lost.

**Comment by prculley** [comment]
Rebased and merged manually...

**Pull request closed without merging**
