### PR TITLE
Updated swedish translation

### PR DESCRIPTION
**Pull request by pehlm**
I'm having an updated swedish translation for Gramps, that I hoping you have some interest in. It's reworked but mostly based on the earlier translator, which so sadly died last year. Over 500 untranslated strings is now translated though, some touches, spellings and grammar errors is also fixed. I've done it with the Gramps 5.0 pot-file, and I've tested it with that version, I don't see anything wrong. Hope it is useful.

### CODE REVIEW

**Comment by pehlm** [comment]
Yes I am, the translation for 5.0 is 100% and I do not think there are many errors either now, if any at all. I would actually be very pleased to be the new translator. Thanks!

**Comment by Nick-Hall** [comment]
Thanks for volunteering.  Welcome to the [Team](https://gramps-project.org/wiki/index.php/Team)!

**Comment by pehlm** [comment]
Many thanks for that. What is the preferred way to commit my changes? Should I create pull requests each time?

**Comment by Nick-Hall** [comment]
@pehlm I suggest you start by submitting pull requests.  There were a couple of unwanted merges in this PR that I had to remove.  Make sure you use the `git pull --rebase`, and check for merges using `gitk` or `git log`.  However, translators are allowed to push translation updates directly to the repository.

**Comment by pehlm** [comment]
Ok, thanks for that!

**Pull request merged**
