### PR TITLE
Added buttons for adding a new person and removing the selected person to the editpersonref dialog

### PR DESCRIPTION
**Pull request by codernarchy**
Just added two buttons to the editpersonref dialog:

grafik
grafik

### CODE REVIEW

**Comment by prculley** [comment]
You have a trailing whitespace error, found by the Travis test.

**Comment by chrmue94** [comment]
Thanks for the hint, I just removed it

**Review by Nick-Hall — CHANGES_REQUESTED** [review]
A better way to implement this would be to add a `PersonEntry` class to the [objectentries](https://github.com/gramps-project/gramps/blob/master/gramps/gui/editors/objectentries.py) module.  This would ensure a consistent interface.

Have a look at the [event editor](https://github.com/gramps-project/gramps/blob/458772d1e6eb2d04317487777a734a5f8a28c6a1/gramps/gui/editors/editevent.py#L139) to see how the `PlaceEntry` class is used.

**Comment by Nick-Hall** [comment]
Added an alternative in PR #1371.  It looks like we may have used this approach before.  I need to investigate why we may have decided on a different approach.  Until then I'll leave this PR open.

**Comment by Nick-Hall** [comment]
Closed in favour of PR #1371.

**Pull request closed without merging**
