### PR TITLE
Reformat code using the latest stable version of black

### PR DESCRIPTION
**Pull request by Nick-Hall**
Version 24.1.0 was released earlier today.

### CODE REVIEW

**Comment by jralls** [comment]
The "code quality" claim is dubious at best considering the moving around of gratuitous parentheses in long chains of `foo = bar = … = quux = None`.

**Comment by Nick-Hall** [comment]
Yes.  The main reason for the PR (and the quick merge) was to fix the failing lint check.

An alternative would be to force the action to use an older version of black as described [here](https://black.readthedocs.io/en/stable/integrations/github_actions.html) in the documentation.

It seems that they do a major upgrade like this once a year that may change some formatting.   How should we handle this now and in the future?

**Comment by jralls** [comment]
> An alternative would be to force the action to use an older version of black as described [here](https://black.readthedocs.io/en/stable/integrations/github_actions.html) in the documentation.

That's illusory: It says the version has to be on PyPi and the [PyPi](https://pypi.org/project/black/#files) has only the latest version.

> How should we handle this now and in the future?

Split up the lines so that Black doesn't want to add parentheses to make a line continuation. e.g:
```
self.begin_progress = self.end_progress = yes
self.step_progress = self._default_callback = yes
```
is clearer than either
```
    self.begin_progress = (
           self.end_progress
      ) = self.step_progress = self._default_callback = yes
```
or
```                       
self.begin_progress = self.end_progress = self.step_progress = (
       self._default_callback
) = yes
```
and will be immune to getting reformatted every time the Black team's whim changes about where the line should break.

**Comment by QuLogic** [comment]
> That's illusory: It says the version has to be on PyPi and the [PyPi](https://pypi.org/project/black/#files) has only the latest version.

I don't love black either, but there are plenty of [older releases on PyPI](https://pypi.org/project/black/#history).

**Comment by kulath** [comment]
I don’t love black either. I suppose the alternative would be (liberal) use of Pragma (pragmata?) to tell black (and if necessary lint) to ignore certain lines. TimSent from my iPhoneOn 27 Jan 2024, at 04:52, Elliott Sales de Andrade ***@***.***> wrote:﻿

That's illusory: It says the version has to be on PyPi and the PyPi has only the latest version.

I don't love black either, but there are plenty of older releases on PyPI.

**Comment by jralls** [comment]
> I don't love black either, but there are plenty of older releases on PyPI.

Ah, I stand corrected. I expected history to be a simple list, not installable links.

**Pull request merged**
