### PR TITLE
Caigner/german translation fixes

### PR DESCRIPTION
**Pull request by caigner**
fixed some more German grammar in de.po

### CODE REVIEW

**Comment by prculley** [comment]
I think you need to do a 'git fetch --all' and then a 'git rebase upstream/master' on your branch if you really want to make changes to master.  That will get the latest master changes into your work and clean up the horrible mess of commits that are appearing here, unrelated to your work.

I should note that for the moment, it would be best to make your changes to the maintenance/gramps50 branch as that is currently the most up to date and is periodically being merged into master, so any changes made there will end up in master as well.  We are not doing merges from master back to maintenance/gramps50, so any changes made to master will need to also be made manually to that branch if necessary.

**Comment by caigner** [comment]
Actually the changes should go into the maintenance/gramps50 branch.

Have I messed up again? So sorry for that. :-(

I am still a bit overwhelmed  by git and github.

What have I done wrong?

I welcome any input.

Regards,
Christian

**Comment by caigner** [comment]
Should I send another Pull Request to maintenance/gramps50?

**Comment by Nick-Hall** [comment]
Changed base branch.

**Comment by Nick-Hall** [comment]
@caigner It looks OK except for the branch merge commit.

**Comment by caigner** [comment]
@Nick-Hall Thanks!

**Comment by prculley** [comment]
> I am still a bit overwhelmed by git and github.
> What have I done wrong?
When you first use Github to start a PR, there is a block at the top that shows your 'base fork', 'base', 'head fork', and compare branch.  This defaults to a base of 'master'.  If you want to merge into 'maintenance/gramps50' or whatever, you need to use the selector to pick that branch.

If you forget, you often get a very long list of commits that are unrelated to the ones you created, or even a 'cannot merge' message.  You can edit the title even after the PR is submitted to change the base.
Nick did this for you to clean up most of the issues.

The following assumes that the main Gramps repo is named 'upstream' in your git configuration, if you named it something else, change accordingly.

At this point I think you need to do a 'git fetch --all' and then a 'git rebase upstream/maintenance/gramps50' on your branch, I think that will get rid of the extra branch merge commit.

And to merge your two commits into a single one, you could follow the previous commands with 'git rebase -i upstream/maintenance/gramps50' to let you do an interactive (-i) rebase, and then use the text editor to fix up according to the instructions.

You might want to try using the 'git gui' command and then the 'Repository/Visualize all branch' menu items to help get an idea of what your git commands are doing, just leave it open and do a 'Shift-F5' reload to see what effect each command you do with git has.

**Comment by sam-m888** [comment]
Closing as I believe they have been already merged by @Leonhaeuser 

https://github.com/gramps-project/gramps/commit/257b091cac2c1b462e5d54ece1ab174750578c32#commitcomment-32171451

**Pull request closed without merging**
