### PR TITLE
Hebrew translation ~62% done

### PR DESCRIPTION
**Pull request by avma**

### CODE REVIEW

**Comment by Nick-Hall** [comment]
@avma Thanks for the updated translation.  Would you like to be our new Hebrew translator?

**Comment by avma** [comment]
> @avma Thanks for the updated translation. Would you like to be our new Hebrew translator?

Sure (since I'm doing it anyway ;)...)

**Comment by Nick-Hall** [comment]
@avma Welcome to the team.  I have added you to our list of [translators](https://gramps-project.org/wiki/index.php/Team#Translators).

**Comment by Nick-Hall** [comment]
@avma Would it be useful to merge this into the _gramps51_ maintenance branch ready for the next release?

**Comment by Nick-Hall** [comment]
Rebased on the _gramps51_branch and merged into the latest template.

Merged in commit 1b2e91d365643e320366893d58be9d546dbc6913.

**Comment by Nick-Hall** [comment]
@avma This has been merged this but I made a mistake so that it will show as closed in GitHub.

**Comment by avma** [comment]
Sorry for not responding on time, (probably turned notification of...) anyway I created earlier today a pr with an 'almost done' he.po file.

**Comment by avma** [comment]
btw, any idea why itis still showing 41.9% coverage?
@@           Coverage Diff           @@
##           master     #880   +/-   ##
=======================================
  Coverage   41.91%   41.91%           
=======================================
  Files        1066     1066           
  Lines      144902   144902           
=======================================
  Hits        60737    60737           
  Misses      84165    84165

**Pull request closed without merging**
