### PR TITLE
Fix list size option in the top surnames gramplet

### PR DESCRIPTION
**Pull request by DaveSch-gramps**
Allow users to specify how many surnames appear in the list from 10 to 1000

from discourse

https://gramps.discourse.group/t/diversely-transliterated-sur-names-and-statistics/5768/8

### CODE REVIEW

**Comment by DaveSch-gramps** [comment]
Bug #0013448

**Comment by hgohel** [comment]
@DaveSch-gramps Do you have Black installed locally? Running that on the source file will eliminate the lint check failure.

**Comment by DaveSch-gramps** [comment]
No to Black. I am not a real coder. I modified code I found in LastModified to achieve the menu options.

I just use Github Desktop for Windows and Atom. I do understand Atom is no longer supported.

**Comment by hgohel** [comment]
> No to Black.

No worries. Looks like Black would like to see two empty lines after `NUM_SURNAMES =" and there's only one right now. Simple fix.

**Comment by DaveSch-gramps** [comment]
Line added and both checks are green!

**Pull request merged**
