### PR TITLE
add CONTRIBUTING file, enable packacking this file

### PR DESCRIPTION
**Pull request by matkoniecz**
CONTRIBUTING file is standard place for documentation how one may send patches
such documentation exists for this project so that file will be redirection to existing resources

Ref: https://gramps-project.org/bugs/view.php?id=10019

-----

Note to myself: see https://gramps-project.org/bugs/my_view_page.php for next issues to process

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
As long as you are going to be including wiki pointers on how
to help improve gramps, you might consider including the two(?)
which are for translators -- since contributions can take many
forms.  Just a thought.

**Comment by sam-m888** [comment]
Thank you

**Comment by sam-m888** [comment]
>>  you might consider including the two(?)
>> which are for translators -- since contributions can take many
>> forms. 

@Paul-Franklin Which two links are you referring to?

**Comment by Paul-Franklin** [comment]
> @Paul-Franklin Which two links are you referring to?

https://gramps-project.org/wiki/index.php?title=Translating_Gramps
https://gramps-project.org/wiki/index.php?title=Portal:Translators

**Comment by Paul-Franklin** [comment]
You asked for "two" so I supplied two.

My original suggestion was for "two(?)" and that was meant
to be "three" /if/ anybody wanted to include translating the "user
manual" also.  Though to be sure I have my own opinion on that.

**Comment by sam-m888** [comment]
@Paul-Franklin Thank you, I'll also add the user manual url also as suggested 👍 

I'll use the following wording:

> If you are interested in translating Gramps to your language see:
> https://gramps-project.org/wiki/index.php?title=Translating_Gramps
> https://gramps-project.org/wiki/index.php?title=Portal:Translators
> To translate the Gramps user manual see:
> https://gramps-project.org/wiki/index.php?title=Translating_the_Gramps_User_manual

**Pull request merged**
