### PR TITLE
Fix <ctrl>c in view to get selected item to clipboard

### PR DESCRIPTION
**Pull request by prculley**
Fixes #10682

May want to backport to gramps42 branch...

### CODE REVIEW

**Comment by Nick-Hall** [comment]
> May want to backport to gramps42 branch...

Yes.  We will do one final gramps42 release.

**Comment by sam-m888** [comment]
Was this meant to be merged and not closed?

**Comment by Nick-Hall** [comment]
When I rebased there was no change to merge.  I assume it had already been fixed. Perhaps @prculley would confirm this.

**Comment by sam-m888** [comment]
See what you mean the code has gone, when I actually go to github!

And going direct to Paul's branch for that bug shows the code change  has
gone?
https://github.com/prculley/gramps/commits/bug10682

**Comment by Nick-Hall** [comment]
After I rebased, I pushed back to Paul's branch.  This would normally ensure that the PR was marked as _Merged_ when the commit was pushed.  As there was nothing to merge, it was marked as _Closed_ instead.

**Comment by sam-m888** [comment]
https://github.com/gramps-project/gramps/pull/652

**Pull request closed without merging**
