### PR TITLE
Support XDG base directory specification

### PR DESCRIPTION
**Pull request by a-andre**
Fixes [#8025](https://gramps-project.org/bugs/view.php?id=8025)

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Are `USER_DATA`, `USER_CONFIG` and `USER_CACHE` set to sensible paths on Windows?

**Comment by QuLogic** [comment]
Since this is using the GLib functions:

data:
> On Windows it follows XDG Base Directory Specification if `XDG_DATA_HOME` is defined. If `XDG_DATA_HOME` is undefined, the folder to use for local (as opposed to roaming) application data is used instead. See the [documentation for `FOLDERID_LocalAppData`](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid). Note that in this case on Windows it will be the same as what `g_get_user_config_dir()` returns.

config:
> On Windows it follows XDG Base Directory Specification if `XDG_CONFIG_HOME` is defined. If `XDG_CONFIG_HOME` is undefined, the folder to use for local (as opposed to roaming) application data is used instead. See the [documentation for `FOLDERID_LocalAppData`](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid). Note that in this case on Windows it will be the same as what `g_get_user_data_dir()` returns.

cache:
> On Windows it follows XDG Base Directory Specification if `XDG_CACHE_HOME` is defined. If `XDG_CACHE_HOME` is undefined, the directory that serves as a common repository for temporary Internet files is used instead. A typical path is `C:\Documents and Settings\username\Local Settings\Temporary Internet Files`. See the [documentation for `FOLDERID_InternetCache`](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid).

which all seem reasonable?

**Comment by Nick-Hall** [comment]
Yes, they look reasonable.

**Comment by emyoulation** [comment]
There is a discussion about the drawbacks of using %localappdata% instead of %appdata% in started in Discourse during the Beta Test cycle:
https://gramps.discourse.group/t/aio-move-of-user-directory-from-appdata-to-localappdata/4156/9

**Pull request merged**
