### PR TITLE
Use CacheProxyDb on reports with LivingProxyDb

### PR DESCRIPTION
**Pull request by dsblank**
This PR inserts the CacheProxyDb into reports after possible proxies, targeting LivingProxyDb.

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
You could of course put a new "run" into stdoptions
(run_all_three_proxies ? run_all_proxies ?) and then
change every report which did a "run" for the privacy
and then the living proxies into a "run" of the new
(all-three) one, putting the implementation of the
cache proxy into stdoptions.

Or you could just put a "run" of the cache proxy into
stdoptions (even though it isn't technically an "option")
and then you'd only need to add the "run" line to each
report (with no "import" in each report).

Just a thought.

**Comment by Paul-Franklin** [comment]
I don't remember if I ever saved the value from the "run"
or the privacy option, but certainly I sometimes saved the
value from the "living" option, so if they were consolidated
that aspect would need paying attention to.

So "all-three" may be less obviously desirable.

**Comment by dsblank** [comment]
In Gramps 5.1, I think all of this should be re-factored for two things:

1. We need to be able to set the order of application of proxies from the command-line and GUI. 
2. We should consider making probably_alive a property of Person

**Comment by Paul-Franklin** [comment]
Upon further consideration, I think the best thing may be
to commit this p.r. now, so that its code can get into the
alpha release, since that might happen before you get
back.  ISTM that something good now is better than
something better later (especially if the "later" code
isn't really all that much "better").

**Comment by dsblank** [comment]
Sounds good to me. I wanted to at least get your initial feedback, and I think you are right.

**Pull request merged**
