### PR TITLE
Stop malformed Gramps XML creatation due to missing blank [surname] tags

### PR DESCRIPTION
**Pull request by sam-m888**
Fixes [#10078](https://gramps-project.org/bugs/view.php?id=10078)

### CODE REVIEW

**Comment by prculley** [comment]
Regarding the vcard test error; it appears that the test was creating a person with a Nickname, but no surname.  Your change seems to be creating Gramps XML with the <surname /> attribute added; presumably an empty surname as opposed to NO surname.  It is probably easiest to modify the test to add an empty surname to the nickname tests.
`self.vcard[2] = "FN:Lastname"`
I don't have time to try and debug this at the moment, maybe in a couple of days.

**Comment by sam-m888** [comment]
Thanks for the hint eg: Lastname == surname

Hopefully I'm fixing the correct issue and not hiding something!

**Comment by prculley** [comment]
See my latest note on https://gramps-project.org/bugs/view.php?id=10078

**Comment by johnbickmore** [comment]
https://github.com/gramps-project/gramps/pull/613

**Pull request closed without merging**
