### PR TITLE
Add occupation & residence events + attributes in the CSV persons importer

### PR DESCRIPTION
**Pull request by matt32106**
User can now add the following columns in the csv import file for a person:
- Occupation description
- Occupation date
- Occupation place
- Occupation source
- Residence date
- Residence place
- Residence source
- Attribute type
- Attribute value
- Attribute source
the corresponding event will be added to the person.
The user can put several lines for the same person if two occupations are known, one event per line will be created.

### CODE REVIEW

**Comment by adamvazquez82** [comment]
@matt32106  Travis-ci failed see here https://travis-ci.org/gramps-project/gramps/builds/519779821#L2817

> gramps/plugins/importer/importcsv.py:911:        # look for a match, and possible correction 
> ERROR - Trailing whitespace found in source file(s)

**Comment by matt32106** [comment]
As a newbie here, am not sure if this should have been pushed to gramps:master
Is there a policy doc somewhere?

**Comment by sam-m888** [comment]
> As a newbie here, am not sure if this should have been pushed to
> gramps:master
> Is there a policy doc somewhere?
>

Hi Matt,

Welcome and thanks for your contribution,

Your (PR) Pull request against gramps master  is correct as you have added
a feature and not fixed a bug.

This is mentioned on the "Committing policies" wiki page under "Branches"
eg; "Only new features should be committed to the master branch."
https://www.gramps-project.org/wiki/index.php/Committing_policies#Branches


Kind regards
Sam

PS: Please have a read of the semi-related feature request 5125: Expand CSV
support with AFN and REFN
https://gramps-project.org/bugs/view.php?id=5125
and PR 139
https://github.com/gramps-project/gramps/pull/139
In these it was suggested that CSV be made to handle user-defined
attributes.

**Comment by matt32106** [comment]
I planned to add code to handle residence as I did for occupation so I will also have a look at adding custom attributes in a generic way.

**Comment by matt32106** [comment]
Can you please add a WIP or ON_HOLD  tag? 
The code is not working as intended yet.

**Comment by matt32106** [comment]
am not familiar with codecov, do I have to do something?!

**Comment by matt32106** [comment]
As far as I am concerned, this one is finished, you may want to consider it for 5.1?! Please make sure to review my code, this is my first PR.

**Comment by matt32106** [comment]
Do you expect me to do something?! If yes, please explain as I don't get it.

**Comment by Nick-Hall** [comment]
@matt32106 You would normally squash your commits to remove your working with `git rebase -i` and also resolve the conflicts.  However, in this case the conflicts are trivial so I'll do it for you.

**Pull request merged**
