### PR TITLE
Progen import fixes and testing

### PR DESCRIPTION
**Pull request by prculley**
It started with fixing the progress popup...
I switched the Progen importer from a popup progress to the Gramps main screen status bar progress indicator.

To test I decided to implement the test files for import_tests module.  That module needed some work to deal with the many files in the Progen data set, and the use of config date formats in the actual data.
The test files are created by the Progen demo sw off of the Gramps master data/tests/exp_sample_ged.ged so should be free of any copyright issues.

In attempting to run the tests I found several issues in the Progen importer code:
    - Files not closed
    - Note text set to 'list' instead of 'str' types
    - Address structure elements set to 'None' instead of ''
    - Long text strings losing characters and getting corrupted

This seem ready for merge to master...

### CODE REVIEW

**Comment by vario-500** [comment]
Paul,
Thanks for all your work (progress, address, note). Intention of __create_note was a single point to save all notes ...

I've checked your fixings and also the SAMPLE files. Everything works well, I can track the Notes (especially N0001 and N0004). The Pro-Gen importer doesn't change anything on variable F16 Person Note and F17 Person Info (line 1274 ff.). In deed, this part of the code isn't changed since his introduction in Dec. 2009 (v 3.1.3). This means for the SAMPLE files that "Surname" is part of this notes, not set by the importer and not an "Alternative name". Other programs store different informations in this fields.

It make sense seeing shorter informations rather then a long text; therefore I've streamlined all fields with Note context. Highly appreciated if you process the "importprogen.py" file the standard way or is there a different route to minimize workload for the developers? I like to contribute some more features / fixes to Gramps ...

**Comment by prculley** [comment]
> Highly appreciated if you process the "importprogen.py" file the standard way or is there a different route to minimize workload for the developers? I like to contribute some more features / fixes to Gramps ...
I'm not sure exactly what you are asking here...
Since you are not yet a developer, you are unable to make direct contributions to Gramps.  However, we are always looking for any/all help and ideas.  So we can work with you, at least while you are learning.
Not knowing what your capabilities are at this point I can only give general advice; you might try reading https://gramps-project.org/wiki/index.php?title=Getting_started_with_Gramps_development and https://gramps-project.org/wiki/index.php?title=Brief_introduction_to_Git.  The latter has a fairly good description of how to submit PRs for contributions (like I did for this).

If that is too much for you we can always take a few submissions of patched modules via email or bugtracker, but if you start getting prolific, it would be better to learn git and do it the recommended way.

P.S. if you are satisfied with the PR the way it is, please make a clear comment to that effect, that way we can commit it to the master branch and it will become a part of Gramps.

**Comment by vario-500** [comment]
Paul,

My intention for you was to push it towarde the master branch - cause I'm not a Gramps developer - and to close the issue on a short way. As said, I've tested your PR and fixed some small lines. So please commit the last submitted file from me to the master branch.

 

It's a good idea for the next bug fix start with a Git PR. I'm working on #9604 'Clone Event'. I've created an addtional functionality bound into the different menus. One intention of the original submitter was NOT to clone the reference; these request I like to handle as an option. Therefore I need to know (cause the upcoming Delete Button in the event reference has to be de-/activated in different scenarios) which pressed action / button we're just running - a normal edit, a merge or a clone of an event - in some derived classes. I assume this information is deep stored someware in the 'uistate' structure, but I'm struggle to find it. Can you help me out which variable indicates with action is took to manipulate the content of a primary element?
 



Gesendet: Freitag, 20. Januar 2017 um 21:14 Uhr
Von: "Paul Culley" <notifications@github.com>
An: gramps-project/gramps <gramps@noreply.github.com>
Cc: vario-500 <alois.poettker@gmx.de>, Comment <comment@noreply.github.com>
Betreff: Re: [gramps-project/gramps] Progen import fixes and testing (#326)



Highly appreciated if you process the "importprogen.py" file the standard way or is there a different route to minimize workload for the developers? I like to contribute some more features / fixes to Gramps ...
I'm not sure exactly what you are asking here...
Since you are not yet a developer, you are unable to make direct contributions to Gramps. However, we are always looking for any/all help and ideas. So we can work with you, at least while you are learning.
Not knowing what your capabilities are at this point I can only give general advice; you might try reading https://gramps-project.org/wiki/index.php?title=Getting_started_with_Gramps_development and https://gramps-project.org/wiki/index.php?title=Brief_introduction_to_Git. The latter has a fairly good description of how to submit PRs for contributions (like I did for this).


If that is too much for you we can always take a few submissions of patched modules via email or bugtracker, but if you start getting prolific, it would be better to learn git and do it the recommended way.

P.S. if you are satisfied with the PR the way it is, please make a clear comment to that effect, that way we can commit it to the master branch and it will become a part of Gramps.

**Comment by prculley** [comment]
Normally, you would connect to the Gtk signal for each Menu item/button you have an interest in.  That connection specifies a method which is executed on activation.  In the method you do the appropriate thing; sounds like you would save some minimal state (like button type), and then go to common code.  Or something like that.  Hope this is enough of a hint...

I've downloaded your patch and integrated it into this PR on my local machine, but am holding for a bit as I added the original text progress feature back in, and that depends on my Gedcom progress PR being accepted.  If I uploaded now and it got accepted first, then it would fail...

**Comment by prculley** [comment]
Fixes integrated and ready to go...

**Comment by sam-m888** [comment]
Checked and tested.  (As well confirming that the mentioned: "depends on my Gedcom progress PR #329 being accepted"  has been accepted)

**Comment by sam-m888** [comment]
Thank you

**Comment by sam-m888** [comment]
@prculley FYI: congratulations on pushing test coverage over 40% (master is now at 40.10% ) 👍

**Pull request merged**
