### PR TITLE
Bug 8809 Multiple GEDCOM imports creates duplicate event IDs

### PR DESCRIPTION
**Pull request by prculley**

### CODE REVIEW

**Comment by dsblank** [comment]
Looks good. Will wait for Travis to green-light it. Thanks!

**Comment by dsblank** [comment]
I presume this needs to be applied to master, as well.

**Comment by prculley** [comment]
I guess it needs to be applied to master, I did no testing, as I don't have any Windows AIO for the master branch as of yet.

**Comment by dsblank** [comment]
@sam-m888 Perhaps it is time to make an alpha? We could make your private build available off a server? Or you could continue to share individually?

**Comment by sam-m888** [comment]
@dsblank @bpisoj If Josips ok with it and there are no further underlying AIO package updates required, as I recall seeing an updated launcher on one of Issues (some fix for python I believe?) that I can't find any longer!  It could be uploaded to  http://sourceforge.net/projects/gramps/files/Unstable

**Pull request merged**
