### PR TITLE
Environment variables in mediapath

### PR DESCRIPTION
**Pull request by belissent**
The mediapath could now be a relative path from database location,
or use variables ($GRAMPSHOME, $GRAMPS_RESOURCES, etc.)

### CODE REVIEW

**Comment by dsblank** [comment]
Thank for the changes! Sorry, but can you make a last adjustment: can you make the function that returns the expanded path to take just a path, not the db? That way, it can work with any path.

**Comment by belissent** [comment]
On the forums, a user wanted the ability to have media path relative to the database location.
Hence the 'db' parameter.

Do I discard this feature? (relative media paths will then be relative to the CWD)

Or do I keep it, and add another function for general paths (but not to be used for media path) ?

**Comment by belissent** [comment]
Note:
I added the "expanded_vars_path" which could partially fit the need?
I could add the "normalizing" part in the "expanded_vars_path" if you prefer?

**Comment by dsblank** [comment]
Why do we need to define and resolve these variables in the shell environment? Couldn't we do it ourselves, in a Python environment? Something like:

```python
path = expand("~/{GRAMPS_HOME}/{VARIABLE}/filename.txt")

ENV = {"GRAMPS_HOME": "/some/path", "VARIABLE": "/other"}

def expand(path):
    return path.format(**ENV)
```

**Comment by belissent** [comment]
+1 for the the double star, not so frequent to use it...
The shell environment gave the possibility to use any other variable.
I send another proposition tomorrow if it is ok for you (it's 1 am here)

**Comment by dsblank** [comment]
Thank you for this, and for working through the changes.... looks very good!

**Comment by Paul-Franklin** [comment]
Are your gramps environmental variable changes (which I think
were committed in 8/2015) known to work on Windows?

**Comment by Paul-Franklin** [comment]
More specifically, does the GRAMPS_RESOURCES envariable (which
you have put into example.gramps) exist for normal users who are not
Mac users?  (I do not include people who "python3 Gramps.py" to run
gramps as "normal users".)

Thanks.

**Comment by dsblank** [comment]
It should be the case that GRAMPS_RESOURCES exists for all users. If this is not pre-defined, then it is created.

**Comment by Paul-Franklin** [comment]
OK.  Can you tell me /where/ "it is created"?

I didn't find such a place when I looked.

(Note that is not the same thing as telling me where
it /could/ be created, which IMHO is resourcepath.py)

**Comment by dsblank** [comment]
I think that you may be right that it is only in Gramps.py. Do we need to push that down?

**Comment by sam-m888** [comment]
@dsblank Yes please. I was just about to create an issue to report that this happens on the AIO master build.

start gramps
close the "Family Trees" dialog
Preferences > Family Trees > set database backend to "DBI 2.0"  and close
create a new family tree
import example.gramps
switch to a view


Note that importing example.gramps from gramps42 works

error
--------------
on Windows:
..............
113804: ERROR: grampsapp.py: line 139: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\viewmanager.py", line 1011, in view_changed
    self.__change_page(page_num)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\viewmanager.py", line 1024, in __change_page
    self.active_page.set_active()
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\views\listview.py", line 293, in set_active
    NavigationView.set_active(self)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\views\navigationview.py", line 154, in set_active
    PageView.set_active(self)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\views\pageview.py", line 300, in set_active
    self.bottombar.set_active()
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\widgets\grampletbar.py", line 275, in set_active
    gramplet.pui.update()
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gen\plug\_gramplet.py", line 309, in update
    self._generator = self.main()
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\plugins\gramplet\persondetails.py", line 129, in main
    self.display_person(active_person)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\plugins\gramplet\persondetails.py", line 137, in display_person
    self.load_person_image(active_person)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\plugins\gramplet\persondetails.py", line 264, in load_person_image
    full_path = media_path_full(self.dbstate.db, obj.get_path())
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gen\utils\file.py", line 202, in media_path_full
    mpath = media_path(db)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gen\utils\file.py", line 170, in media_path
    return expand_media_path(mpath, db)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gen\utils\file.py", line 184, in expand_media_path
    mpath = expand_path(mpath, False)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gen\utils\file.py", line 160, in expand_path
    path = path.format(**environment)
KeyError: 'GRAMPS_RESOURCES'

----------------

61366: ERROR: grampsapp.py: line 139: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\viewmanager.py", line 1099, in __open_activate
    self._post_load_newdb(filename, 'x-directory/normal', title)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\viewmanager.py", line 1133, in _post_load_newdb
    self._post_load_newdb_gui(filename, filetype, title)
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\viewmanager.py", line 1156, in _post_load_newdb_gui
    self.__change_page(self.notebook.get_current_page())
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\viewmanager.py", line 1021, in __change_page
    self.__disconnect_previous_page()
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\viewmanager.py", line 1051, in __disconnect_previous_page
    self.active_page.set_inactive()
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\views\listview.py", line 304, in set_inactive
    self.uistate.viewmanager.tags.tag_disable()
  File "C:\Program Files\GrampsAIO64-4.9.9\lib\python3.5\site-packages\gramps\gui\views\tags.py", line 131, in tag_disable
    self.uistate.uimanager.remove_ui(self.tag_id)
TypeError: Argument 1 does not allow None as a value

**Comment by dsblank** [comment]
@sam-m888 Should be fixed by d71f949.

**Pull request merged**
