### PR TITLE
Update polish tanslation

### PR DESCRIPTION
**Pull request by izikeros**
Fixed wrong translation of gender - user reported it directly to me. Updated multiple strings.

### CODE REVIEW

**Comment by izikeros** [comment]
Changed base for merge for this PR from `master` to `maintenance/gramps51`.

**Comment by mefistotelis** [comment]
It's a pain to review this. It is too long for one change. It would get better review if divided. I gave up at circa 2/3 of changes.

**Comment by izikeros** [comment]
@mefistotelis thank you for approaching review of this PR changes. 
How we can proceed with that? I can try to artificially divide changes into several commits or several PRs. In such case, reviewer can allocate smaller chunks of time and review it part by part. Not sure how easy will be splitting changes from one .po file into several commits/PRs.
Any better idea on how to proceed?

**Comment by mefistotelis** [comment]
It would be far easier to review if the changes were categorized in a way which allows to describe each chunk with descriptive commit message, while at the same time separating changes which affect a lot of lines, ie:

1. Change polish translation of the word 'repository'
2. Change polish translation of the word 'tag'
3. Other/miscellaneous changes, preferably also divided into several commits

Note that I don't have any ownership/privileges in the Gramps project, so I can't tell exactly what the project owners require. If I was in such position, I would require the commit messages to be more descriptive than "update polish translation".

To divide the existing commits, I would generate `.patch` files and copy/paste chunks of them into separate files to group the messages. Not sure how skilled you are in handling patches - doing it this way requires you to understand how the changes are stored within patches. Though it isn't hard to figure out by just looking at the content.

On a separate note, I've noticed some of the short strings lack proper context, which makes the translation harder. I started some discussion about that, here:
https://gramps.discourse.group/t/translations-gettext-make-context-the-norm/2133

**Comment by Nick-Hall** [comment]
We probably need someone to co-ordinate the Polish translation.  We currently have a vacancy on the [team](https://gramps-project.org/wiki/index.php/Team#Translators).

I also see that Michał Stojek has made quite a number of recent translations on Weblate.  These are automatically merged in the _master_ branch.

I am happy to merge this PR when ready.

**Comment by izikeros** [comment]
> We probably need someone to co-ordinate the Polish translation. We currently have a vacancy on the [team](https://gramps-project.org/wiki/index.php/Team#Translators).
> 
> I also see that Michał Stojek has made quite a number of recent translations on Weblate. These are automatically merged in the _master_ branch.
> 
> I am happy to merge this PR when ready.

I'm in contact with Michał Stojek and he generously agreed to review the changes proposed by this PR.

**Comment by Nick-Hall** [comment]
@izikeros Is this likely to be ready soon?  I am thinking of releasing v5.1.5 this weekend.

**Comment by stojex** [comment]
I'll check the translation today.

**Review by stojex — APPROVED** [review]

**Review by stojex — APPROVED** [review]

**Review by stojex — APPROVED** [review]

**Review by stojex — APPROVED** [review]

**Comment by izikeros** [comment]
Thank you Michał (@stojex) for reviewing the changes. @Nick-Hall Thrilled to see v5.1.5!

**Review by stojex — APPROVED** [review]

**Review by stojex — APPROVED** [review]

**Review by stojex — APPROVED** [review]

**Review by stojex — APPROVED** [review]

**Pull request merged**
