### PR TITLE
Expand exmaple.gramps for testing DynamicWeb report

### PR DESCRIPTION
**Pull request by belissent**
Modification for example.gramps database
(custom parent relationship, notes)

### CODE REVIEW

**Comment by dsblank** [comment]
I don't think we want to add test stuff to gramps40, which is old and in maintenance mode.

Perhaps you should add such a import file to the addon? addons-source will now look for and run tests after commits:

https://travis-ci.org/gramps-project/addons-source

except that DynamicWeb is being excluded...because it doesn't pass?

**Comment by belissent** [comment]
I have never used Travis or nosetest before.
The test script for the DynamicWeb report is a standalone script and only generates the report with several configurations. I use it to generate the examples:
http://belissent.github.io/GrampsDynamicWebReport/

I suppose that it is excluded because it conflicts with nosetests.
I will look at how to make the CI tests work for the DynamicWeb report on the master branch.

**Comment by dsblank** [comment]
@belissent Ok, both of those ideas (updating example.gramps on master, and making tests work with Travis) sound like great ideas. Thanks!

(DynamicWeb is looking great!)

**Comment by belissent** [comment]
Cancelling pull request.

**Pull request closed without merging**
