### PR TITLE
Fix German localization.

### PR DESCRIPTION
**Pull request by bmendl**
- Fix typos.
- Fix missing spaces.
- Fix missing commas.
- Use https instead of http in URLs (if available).

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Thanks for your contribution.  I'll leave @Leonhaeuser to check the typos.

The urls should be changed in all languages.  I'll investigate further.

**Comment by Leonhaeuser** [comment]
Hello,

will have a look at it today on the weekend.
Then I will also check that I can include the changes in the current 5.0 branch because this is for me the current living branch for translation since release of 5.0.

Regards
Mirko

Von meinem iPhone gesendet

**Comment by bmendl** [comment]
Actually, I did not review the _complete_ translation. There is more to come … ;)

**Comment by Leonhaeuser** [comment]
At the moment my review for 5.0 is ongoing. Found many other things like using the same words in translation. Will update here when finished.

**Comment by Leonhaeuser** [comment]
Hello,
I reviewed the gramps 50 de.po file and take over nearly all changes of this commit (except 2 or 3) in this reviewed file.
So this file can be merged into master.
@bmendl 
please have a look at the reviewed file from gramps50 branch and if you want continue your review there.
I made there many additional changes to your changes.

**Comment by bmendl** [comment]
Thanks for reviewing and accepting my modifications, @Leonhaeuser.
I commited some more changes based on the gramps50 branch.

**Comment by sam-m888** [comment]
Please resubmit if still required.

**Pull request closed without merging**
