### PR TITLE
3068: Wrong reference number for "same person as" in detdescendantreport

### PR DESCRIPTION
**Pull request by SNoiraud**
I tried this on several databases. It works for me.
I have only one question : Is the henry notation always correct with this patch ?

### CODE REVIEW

**Comment by dsblank** [comment]
This looks like a good change. Any way to add a test that fails before change, and then passes after change?

**Comment by SNoiraud** [comment]
Sorry, I don't understand the following : 
add a test that fails before change, and then passes after change ?
What test are you talking about ?

**Comment by dsblank** [comment]
I'm suggesting to add a file, say "gramps/plugins/test/test_detdescendantreport.py", that contains a unittest that would fail before you add this code, and would pass afterwards. 

Actually, let me add some infrastructure for making this easier...

**Comment by dsblank** [comment]
I've got some code, but it is based on the test framework in #95. I'll need to merge that first.

**Comment by dsblank** [comment]
I've added the test framework now. See an example of running a report here: https://github.com/gramps-project/gramps/blob/master/gramps/plugins/test/test_reports.py#L122

**Comment by sam-m888** [comment]
@eno93 Did you test that this works as expected?

**Comment by eno93** [comment]
@sam-m888 Only that the henry notation was working and not that it was always correct. Test would prove this one way or the other as mentioned by @dsblank

**Comment by dsblank** [comment]
Let's go ahead and merge this, and check for correctness with a test later.

**Pull request merged**
