### PR TITLE
Add compression option on XML export

### PR DESCRIPTION
**Pull request by dsblank**
The write options needed to include "binary" to allow the system to write to the stream.

### CODE REVIEW

**Comment by dsblank** [comment]
See https://gramps-project.org/bugs/view.php?id=9394 for details.

**Comment by Paul-Franklin** [comment]
Yes, like you said on 9394 I don't think this should be committed
until it's checked on all three platforms.

**Comment by dsblank** [comment]
I should also note that if one doesn't have the gzip Python library, the old module would crash with the same error that this fixes. That is, if this doesn't work, then we would have to create a different way of making .gramps files with no compression.

**Comment by sam-m888** [comment]
Worked on Windows 7 Pro 64bit using Gramps 5.0.0 [13b4f93 + pr121] AIO 64 bit(Personal Testing version)

*Exported uncompressed
*Imported uncompressed 

checkbox-selection-uncompressed-xml-pr121-b9394-win764bit

**Comment by dsblank** [comment]
Applied this, as we need it for further development. If there are issues on Mac, we will need to fix them.

**Pull request merged**
