### PR TITLE
Fix interface problems with dark themes

### PR DESCRIPTION
**Pull request by Nick-Hall**
* List views now use the default foreground colour from the theme rather than using black.
* Find the link colour from the theme.  Changing the theme will still require a restart.
* Change the shading in the relationship view to use black for dark themes and white for light themes.  I use the amount of red to distinguish a light theme from a dark theme.  There may be a better way to do this.

### CODE REVIEW

**Comment by vantu5z** [comment]
Relationship view is not good. Color is very contrast, we should get some color from theme (that used for Gtk.TextView for example).

For information: Vertex-dark theme don't have this bug as Adwaita-dark.

**Comment by Nick-Hall** [comment]
@vantu5z Thanks for the feedback.  Updated to use the background colour of a TextView for shading in the relationship view.  Unfortunately, I can't see an alternative to using the deprecated `get_background_color` method.

I haven't tested a dark theme with Gtk 3.10 yet.

**Comment by vantu5z** [comment]
Now looks good.
Maybe don't look color and replace it. But use some container with native color that make shading effect?

**Comment by vantu5z** [comment]
Read docs tell that `override_background_color` deprecated too. We should use `Gtk.render_background` to change background color theme. Internet give some example:
```
context = my_entry.get_style_context()
context.save()
context.add_class('warning')
Gtk.render_background(context, blah, blah, blah)
context.restore()
```
How I can understand we should found class name for TextView and we can replace rendering of widget background.

**Comment by Nick-Hall** [comment]
@vantu5z I have created a new widget with a shaded background.

**Comment by vantu5z** [comment]
It works for me! Good job 👍

**Pull request merged**
