### PR TITLE
Remove hidden character from front of shebang line

### PR DESCRIPTION
**Pull request by sam-m888**
Found by [pycycle --verbose --source gramps]

Once corrected pycycle reports:

Project successfully transformed to AST, checking imports for cycles..

No worries, no cycles here!

https://github.com/bndr/pycycle

### CODE REVIEW

**Comment by sam-m888** [comment]
Full error message:

```
Trying to parse file: /home/grampsdev/aaSandbox/gramps/gramps/plugins/test/test_reports.py
Parsing of file failed: /home/grampsdev/aaSandbox/gramps/gramps/plugins/test/test_imports.py
Traceback (most recent call last):
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/pycycle/utils.py", line 66, in read_project
    tree = ast.parse(f.read())
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ﻿#! /usr/bin/env python3
    ^
SyntaxError: invalid character in identifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grampsdev/.virtualenvs/xgrampspy3/bin/pycycle", line 11, in <module>
    sys.exit(cli())
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/pycycle/cli.py", line 70, in cli
    root_node = read_project(source, verbose=verbose, ignore=ignore.split(','), encoding=encoding)
  File "/home/grampsdev/.virtualenvs/xgrampspy3/lib/python3.5/site-packages/pycycle/utils.py", line 113, in read_project
    click.echo(crayons.red(traceback.format_exc(e)))
  File "/usr/lib/python3.5/traceback.py", line 163, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.5/traceback.py", line 117, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib/python3.5/traceback.py", line 474, in __init__
    capture_locals=capture_locals)
  File "/usr/lib/python3.5/traceback.py", line 332, in extract
    if limit >= 0:
TypeError: unorderable types: SyntaxError() >= int()
```

**Comment by sam-m888** [comment]
git diff shows the actual character as **<U+FEFF>**  which is reported to be the:
* Unicode Character 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF)

```
diff --git a/gramps/plugins/test/test_imports.py b/gramps/plugins/test/test_imports.py
index 5060960..52094de 100644
--- a/gramps/plugins/test/test_imports.py
+++ b/gramps/plugins/test/test_imports.py
@@ -1,4 +1,4 @@
-<U+FEFF>#! /usr/bin/env python3
+#! /usr/bin/env python3
 """ Test program for import modules
 """
 #

```

**Comment by prculley** [comment]
The character you found is the BOM (Byte Order Marker) which can be used to positively identify utf-8 encoded files.  Since that is one of the earliest files I created, and I understood that all our python files were to be encoded utf-8, and I am a Windows user, I probably saved it with the BOM attached (or used an editor which did that for me).  I now routinely use Notepad++ which has the standard encoding for python files set to utf-8 with no BOM.  So this is unlikely to occur again.

**Comment by sam-m888** [comment]
Hi Paul,

Thank you for the explanation.

-
Sam

**Pull request merged**
