### PR TITLE
Remove Python2.5 Zipfile duplicate

### PR DESCRIPTION
**Pull request by sam-m888**
Not imported anywhere in the Gramps code I could find.

### CODE REVIEW

**Comment by dsblank** [comment]
It is used here:

https://github.com/sam-m888/gramps/blob/RemoveUnusedZipfileCodePython25/gramps/gen/plug/utils.py#L234

**Comment by sam-m888** [comment]
Well that was obvious! :( Not having a good week!

**Comment by QuLogic** [comment]
Why not just replace that usage with the correct standard library version?

**Comment by sam-m888** [comment]
@QuLogic I'll take a look again, later.

**Pull request closed without merging**
