### PR TITLE
Improvement: Add citation_list to event references

### PR DESCRIPTION
**Pull request by cdhorn**
This takes a pass at extending eventref.py to add citation_list support since the event reference contains the role of the participant and not the event itself.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Adding a citation list to event references seems like a reasonable request to me.  It would give a mechanism to cite evidence for a person's participation in an event, rather than just for the event itself.

**Comment by Nick-Hall** [comment]
The database schema files `grampsxml.rng` and `grampsxml.dtd` will also need updating.

We should also update the examples files with some relevant data.

**Comment by cdhorn** [comment]
Ah yes, okay.

Is this something you want to fold into 5.2?  I am not sure it makes sense to do a database update for something this minor if it is the only thing, maybe it should wait for the next release?

**Comment by Nick-Hall** [comment]
> Is this something you want to fold into 5.2?

I don't see a problem with putting this in.  Sometimes we don't want to make a schema change when we are making other large changes.  When we upgrade from Gtk3 to Gtk4 we probably won't make schema changes.

**Comment by Nick-Hall** [comment]
Rebased.

**Comment by Nick-Hall** [comment]
Updated the schema definitions and examples file.

**Comment by cdhorn** [comment]
Thank you Nick!

**Pull request merged**
