### PR TITLE
German translation corrections

### PR DESCRIPTION
**Pull request by caigner**
Changed several occurrences of "wurde geboren am ____" to "wurde am ____ geboren".

### CODE REVIEW

**Comment by Nick-Hall** [comment]
@Leonhaeuser Are you aware of this?

**Comment by Leonhaeuser** [comment]
All changes approved.
Please make German translation changes in the current Branch

**Comment by Leonhaeuser** [comment]
Nick can you please merge this changes into 5.0.
I have no experience how to.

**Comment by Nick-Hall** [comment]
@caigner @Leonhaeuser I changed the base of the branch and did ran the `msgmerge` command to merge the translations.  Please check to see if the result is as expected.

**Comment by caigner** [comment]
Thank you both for your support.
Have a great New Year!

**Comment by Nick-Hall** [comment]
@caigner Thanks for your contribution.  A Happy New Year to you too.

**Pull request merged**
