### PR TITLE
7004: Only Event and Family Editors are checking if data_has_changed

### PR DESCRIPTION
**Pull request by romjerome**
tidy up and consistency between editors on save()

### CODE REVIEW

**Comment by eno93** [comment]
You may want to re-push this as https://github.com/gramps-project/gramps/pull/312 has been fixed.

**Comment by Nick-Hall** [comment]
Rebased.

**Comment by Nick-Hall** [comment]
In testing this, I found that making changes to a note and then clicking "Cancel" does not warn that the data has changed.

**Comment by romjerome** [comment]
Filled a new bug report (9878).
Did not find the right solution for Note, just a dirty workaround:
```diff
diff --git a/gramps/gui/editors/editnote.py b/gramps/gui/editors/editnote.py
index 37ade77..d4e9919 100644
--- a/gramps/gui/editors/editnote.py
+++ b/gramps/gui/editors/editnote.py
@@ -301,6 +301,11 @@ class EditNote(EditPrimary):
             self.obj.set_styledtext(text)
             _LOG.debug(str(text))
 
+    def data_has_changed(self):
+        if self.db.readonly:
+            return False
+        return True
+
     def save(self, *obj):
         """Save the data."""
         self.ok_button.set_sensitive(False)```

**Comment by Nick-Hall** [comment]
Bug #9878 has been fixed in commit 49321133e0057bda8741b6f2d0eebef3aa87b644.

**Pull request merged**
