### PR TITLE
GraphViz arrow ports

### PR DESCRIPTION
**Pull request by azrdev**
GraphViz reports: connect arrows to side of nodes instead of anywhere

This sets the headport and tailport attributes to all edges in the
graphviz file. Their default value makes the arrows between persons
and/or family nodes attach their ends to the respective node at any
position. With this change, the position facing the node on the other
side of the arrow is chosen.

This PR supersedes #449

### CODE REVIEW

**Comment by azrdev** [comment]
@Paul-Franklin you wrote in the original PR
> Also, if you decide it belongs in the "backend," I suggest you make it an option so users can choose. Do a recursive grep for "DocOptions" to see what I mean. The ASCII and SVG backends currently each have one, but I assume the Graphviz backend could be done also.

I looked at that, but it seems these (SvgDraw)DocOptions are not used by the GraphViz reports at all: the SVG option (background color) appears in "graphical reports" when selecting SVG, but not in Graph reports. I'm a bit lost how to introduce some `GraphVizDocOptions` here

**Comment by Paul-Franklin** [comment]
Yes, I didn't mean for you to actually use those existing DocOptions
classes.  I meant for you to use them as a model to introduce a new
class.  However I forgot that Graphviz isn't using our DrawDoc and
TextDoc classes (or gpr.py files).

I will think about adding that capability to the Graphviz backend
(docgen options), but it might take a while since I have lots of
things on my list.  But also it might not really be needed.

But I still think it should be optional, so the user can choose.  There
are lots of other Graphviz options however.  Maybe you can find an
appropriate tab and add it that way?  If it really is just a yes/no, then
a BooleanOption would be fine.  If there are four choices, then
put them in an EnumeratedListOption.  Add it to add_menu_options
then use it where it is appropriate.

**Comment by azrdev** [comment]
> Yes, I didn't mean for you to actually use those existing DocOptions
> classes. I meant for you to use them as a model to introduce a new
> class. 

That's how I understood you in the first place, however, I struggled to understand how to integrate my own model based on how they do it.

> I will think about adding that capability to the Graphviz backend
> (docgen options), but it might take a while since I have lots of
> things on my list. But also it might not really be needed.

That would be great, but no hurry.

> But I still think it should be optional, so the user can choose. There
> are lots of other Graphviz options however. Maybe you can find an
> appropriate tab and add it that way? If it really is just a yes/no, then
> a BooleanOption would be fine. […] Add it to add_menu_options
> then use it where it is appropriate.

I'll do that.

Thx for looking after this!

**Comment by Paul-Franklin** [comment]
I have committed a slightly-modified version of your patch to master.

https://github.com/gramps-project/gramps/commit/f31caf1ea4df40d000e2669b2655e5de40a9e495

As far as I am concerned this p.r. may be closed now.

Thank you for helping to make gramps better.

**Comment by azrdev** [comment]
thank you!

**Pull request closed without merging**
