### PR TITLE
Galician gl translation

### PR DESCRIPTION
**Pull request by naciohr**
Hello.

Creating gl.po with translation into Galician.

Thanks

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Rebased.

**Comment by Nick-Hall** [comment]
This translation is only 1.5% complete.

@naciohr Are you planning to translate any more?

**Comment by naciohr** [comment]
Hi.

Yes. Sorry I wanted to make sure I was proceeding correctly with the pull request.

I will continue translating.

Thanks and regards.

**Comment by Nick-Hall** [comment]
@naciohr We now use [Weblate](https://hosted.weblate.org/projects/gramps-project/gramps/) for translations.

If you are still interested in translating Gramps, I'll add Galician.

I'll close this PR now though.

**Pull request closed without merging**
