### PR TITLE
familygroup.py:  Rename husband/wife

### PR DESCRIPTION
**Pull request by Mattkmmr**
- Rename husband/wife to father/mother
- Fixes [#11199](https://gramps-project.org/bugs/view.php?id=11199)

### CODE REVIEW

**Comment by Nick-Hall** [comment]
I notice that the original reporter of the bug disagrees with this solution.

Also, @romjerome proposed something similar in PR #347.

Related bug reports:  [#3146](https://gramps-project.org/bugs/view.php?id=3146) and [#9899](https://gramps-project.org/bugs/view.php?id=9899).

This probably need to be discussed on the mailing list.

**Comment by Mattkmmr** [comment]
@Nick-Hall This pull is just intended to be a small fix to remove some confusion by renaming. Showing the right relationship role is the better solution, but I'm currently too busy to work on it.

**Comment by Nick-Hall** [comment]
Why don't we just remove these labels?  They don't seem to add much to the report.

This would avoid complications with relationship types, same-sex relationships and couples without children.

**Comment by romjerome** [comment]
> Why don't we just remove these labels? They don't seem to add much to the report.
>
>This would avoid complications with relationship types, 
> same-sex relationships and couples without children.

:+1:

**Comment by Nick-Hall** [comment]
Replaced by PR #935.

**Pull request closed without merging**
