### PR TITLE
Adds link to issue tracker

### PR DESCRIPTION
**Pull request by brejoc**
Since people might come to this project via GitHub, it could be beneficial to link the issue tracker here. Used the word bug and issue for better discoverability via text search on the README page.

### CODE REVIEW

**Comment by brejoc** [comment]
I'm closing this PR, since nobody is interested in it.

**Comment by prculley** [comment]
You are probably being a bit too early on your close.  The developers are pretty quiet lately, not doing much at all on the 5.2 release.  So since you put this up for master (5.2), we haven't really looked at it yet.  When we get more serious about 5.2, we will look over all the PRs that are tagged for 5.2 or are aimed at master branch and deal with them at that time.

**Comment by Nick-Hall** [comment]
> When we get more serious about 5.2, we will look over all the PRs that are tagged for 5.2 or are aimed at master branch and deal with them at that time.

I'll try to find some time to do that soon.  This year has been somewhat unusual.

**Comment by brejoc** [comment]
Happy to hear. Then let's leave it open of course. I was just cleaning up my PRs a little bit.

**Pull request merged**
