### PR TITLE
Fix place format option in place report

### PR DESCRIPTION
**Pull request by Nick-Hall**
Resolves [#10467.](https://gramps-project.org/bugs/view.php?id=10467)

### CODE REVIEW

**Comment by lordemannd** [comment]
looks good to me on Windows

**Comment by lordemannd** [comment]
Fails if you add Place Report to a Book.

2018-02-28 13:35:11.176: ERROR: grampsapp.py: line 143: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\gramps\gui\plug\report\_bookdialog.py", line 495, in on_add_clicked
    data[2] = item.option_class.get_subject()
  File "C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\gramps\plugins\textreport\placereport.py", line 431, in get_subject
    self.place_format)
AttributeError: 'PlaceOptions' object has no attribute 'place_format'

**Comment by prculley** [comment]
Forgot to add the place report format option to placereport.py on or about line 464
`        stdoptions.add_place_format_option(menu, category_name)`

**Comment by lordemannd** [comment]
@prculley, maybe I misunderstand, but the line you mention at about line 464 is there. In the case of building a Book, is it possible that the add_menu_options function is never called?

**Comment by Nick-Hall** [comment]
@prculley Yes.  This PR adds it.

**Comment by sam-m888** [comment]
New **Place format:** option on the "[Report Options (2)](https://gramps-project.org/wiki/index.php?title=Gramps_5.0_Wiki_Manual_-_Reports_-_part_6#Place_Report)" tab
placereport-new-option50

**Comment by sam-m888** [comment]
Thank you

 - [x] Image for User documentation [updated](https://gramps-project.org/wiki/index.php?title=Gramps_5.0_Wiki_Manual_-_Reports_-_part_6#Report_Options_.282.29_9)

**Pull request merged**
