### PR TITLE
Create readme with existing instructions.

### PR DESCRIPTION
**Pull request by daleathan**
Copied from http://sourceforge.net/projects/gramps/files/Unstable/readme.rst

Have not managed to get this running yet.

### CODE REVIEW

**Comment by dsblank** [comment]
Very useful! This is the year of the webapp... other devs have asked for docs like this so that they can join in on working on this, so this is perfect timing. Do you have particular interest in this part of gramps?

**Comment by dsblank** [comment]
Can you rename the file to README.md? That would be more standard, I think and will stand out.

**Comment by daleathan** [comment]
Yes, I'm interested in the webapp as I really don't want to use a commercial website if I have to.

Doug, am I right in guessing that because gramps master is now solely python 3 that the django 1.7 and 1.8 (LTS) and higher versions are only supported? 

https://docs.djangoproject.com/en/1.8/faq/install/#what-python-version-can-i-use-with-django

**Comment by dsblank** [comment]
The webapp code hasn't been brought up to date with the latest django, nor the latest gramps database changes (or codebase changes). I'll see what needs to make it functional, as it currently exists. Then some work needs to be done to make it 100%.

**Comment by daleathan** [comment]
That would be great, thank you

**Pull request merged**
