### PR TITLE
Add option to change the date error color

### PR DESCRIPTION
**Pull request by SNoiraud**
Fixes [#11046](https://gramps-project.org/bugs/view.php?id=11046)

PR 775 must be applied first.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
We should use the standard Gtk functionality as I mention in the bug report.

**Comment by SNoiraud** [comment]
I tried, but it doesn't work. The Gtk documentation is insufficient: 
"GtkEntry has a main node with the name entry. Depending on the properties of the entry, the style classes .read-only and .flat may appear. The style classes .warning and .error may also be used with entries."
I am trying to find some examples, but nothing, so I am looking in the gtk source code...

**Comment by Nick-Hall** [comment]
@SNoiraud Thanks for looking at this.  I have created PR #796. There is also some same CSS in a comment explaining how users can customise the appearance to suit their own preferences.

**Comment by prculley** [comment]
Nicks suggestion in the bug report worked fine for me on Windows Gtk 3.24 and 3.18.

I just replaced the 'fade' with 'error' in the set_valid and set_invalid routines, and it used the css entry.error definition (which on Adwaita is #cc0000, which is darn red, also made the entry box outline red as well).  Looked OK in both light and dark variants of the Adwaita theme.

If we want to be fancy, I'll bet we could do some css trick to fade in the 'error' color instead, got some reading to do to make that happen though...

**Comment by SNoiraud** [comment]
OK. I close this PR.
The same changes didn't work for me. I suppose I forgotten something.
I remove the patch on PR775

**Pull request closed without merging**
