### PR TITLE
Fix black background on ValidatableMaskedEntry

### PR DESCRIPTION
**Pull request by romjerome**
Force white background as fallback and default color for some gtk3 themes

### CODE REVIEW

**Comment by romjerome** [comment]
> gdk_color_parse has been deprecated since version 3.14 and should not be used in newly-written code.
> 
> Use GdkRGBA

> GdkRGBA
> 
> typedef struct {
>   gdouble red;
>   gdouble green;
>   gdouble blue;
>   gdouble alpha;
> } GdkRGBA;
> 
> A GdkRGBA is used to represent a (possibly translucent) color, in a way that is compatible with cairos notion of color.
> 
>  gdouble red; The intensity of the red channel from 0.0 to 1.0 inclusive
>  gdouble green;The intensity of the green channel from 0.0 to 1.0 inclusive
>  gdouble blue; The intensity of the blue channel from 0.0 to 1.0 inclusive
>  gdouble alpha; The opacity of the color from 0.0 for completely translucent to 1.0 for opaque
> 

Maybe need to provide an alternate patch for the widget.

**Comment by dsblank** [comment]
Not maybe, but definitely. Yes, we should not use deprecated functions in new code. You can either close this and open a new PR, or just commit new changes on this branch. Thanks!

**Comment by romjerome** [comment]
@dsblank,

I was not able to either use 'rgba' or 'override_background_color'.
I suppose that something goes really wrong on get_background()!

e.g.,
```<bound method ValidatableMaskedEntry.get_background of <ValidatableMaskedEntry object at 0xafee3644 (ValidatableMaskedEntry at 0x9399ad0)>>
<bound method ValidatableMaskedEntry.get_background of <ValidatableMaskedEntry object at 0xafe3d9b4 (UndoableEntry at 0x9b041d8)>>
gramps/gui/grampsgui.py:339: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
  Gtk.main()
2016-04-26 15:40:20.428: ERROR: grampsapp.py: line 139: Unhandled exception
Traceback (most recent call last):
  File "gramps/gui/widgets/validatedmaskedentry.py", line 101, in _merge_colors
    rs, gs, bs = src_color.red, src_color.green, src_color.blue
AttributeError: 'function' object has no attribute 'red'
```
Maybe to use GdkRGBA on get_background()?

**Comment by romjerome** [comment]
It can take a while (_thank you internet_), but I suppose that for using hexa color and rgba in python/gdk, we need to make a conversion?

```
color = Gdk.RGBA()
color.parse('#FFF')
color.to_string()
```

**Comment by dsblank** [comment]
Why not just use the RGBA constructor:

```python
self._fade.start(Gdk.RGBA(1.0, 0.0, 0.0))
```

**Comment by romjerome** [comment]
Ah, it works like that!!!
It was not clear for me on API...
http://lazka.github.io/pgi-docs/#Gdk-3.0/structs/RGBA.html#Gdk.RGBA

Also, what should be done for:
```
def get_background(self):
        backcol = self.get_style_context().get_background_color(Gtk.StateType.NORMAL)
        bcol= Gdk.Color.parse('#fff')[1]
        bcol.red = int(backcol.red * 65535)
        bcol.green = int(backcol.green * 65535)
        bcol.blue = int(backcol.blue * 65535)
        return bcol
```

**Comment by dsblank** [comment]
That code doesn't look right. I think red, blue, and green should be between 0.0 and 1.0. Perhaps this should be rewritten for the latest Gtk... maybe those were all work-arounds from earlier versions.

**Comment by dsblank** [comment]
Oh, I see... there is Gdk.Color and Gdk.RGBA... ok, never mind. Code still looks really complicated, with lots of workarounds.

**Comment by dsblank** [comment]
This looks like it is converting an RGBA into a Color. Which can probably be done more directly:

```python
def get_background(self):
        rgba = self.get_style_context().get_background_color(Gtk.StateType.NORMAL)
        return Gdk.Color(int(rgba.red * Gdk.Color.MAX_VALUE), 
                                   int(rgba.green * Gdk.Color.MAX_VALUE), 
                                   int(rgba.blue * Gdk.Color.MAX_VALUE))
```
but maybe there is even a better way.

**Comment by QuLogic** [comment]
There's a `to_color` method on the `Gdk.RGBA` instance.

**Comment by romjerome** [comment]
Looking at some [samples](http://www.programcreek.com/python/example/79692/gi.repository.Gdk.RGBA), saw some additionnal comments, like:
 ```
# Adwaita and some others show big area of black without this, does not bother Ambient on Ubuntu
    editor_window.tline_pane.override_background_color(Gtk.StateFlags.NORMAL, get_bg_color())
    editor_window.media_panel.override_background_color(Gtk.StateFlags.NORMAL, get_bg_color())
    editor_window.mm_paned.override_background_color(Gtk.StateFlags.NORMAL, get_bg_color())
```

**Comment by romjerome** [comment]
We are close to a [patch](https://github.com/romjerome/gramps/commit/e58554ad084d7a956e2a096a89ec8762cd4c0e43).
I am not certain of the best methods, but by trying to move code from Gdk.Color to Gdk.RGBA, it raised some possible cause of the error for handling fade color.

```diff
 gramps/gui/widgets/validatedmaskedentry.py
@@ -74,7 +74,7 @@ class FadeOut(GObject.GObject):
                  ()),
         'color-changed': (GObject.SignalFlags.RUN_FIRST,
                           None,
-                          (Gdk.Color, )),
+                          (Gdk.RGBA(), )),
     }
 
     # How long time it'll take before we start (in ms)
@@ -84,7 +84,8 @@ class FadeOut(GObject.GObject):
 
     def __init__(self, widget, err_color = "#ffd5d5"):
         GObject.GObject.__init__(self)
-        self.ERROR_COLOR = err_color
+        self.ERROR_COLOR = Gdk.RGBA()
+        self.ERROR_COLOR.parse(err_color)
         self._widget = widget
         self._start_color = None
         self._background_timeout_id = -1
@@ -107,10 +108,13 @@ def _merge_colors(self, src_color, dst_color, steps=10):
             rs += rinc
             gs += ginc
             bs += binc
-            col = Gdk.color_parse("#%02X%02X%02X" % (int(rs) >> 8,
+            step = Gdk.RGBA()
+            step.parse("#%02X%02X%02X" % (int(rs) >> 8,
                                                          int(gs) >> 8,
                                                          int(bs) >> 8))
-            self.emit('color-changed', col)
+            step.to_color()
+
+            self.emit('color-changed', step)
             yield True
 
         self.emit('done')
@@ -126,7 +130,7 @@ def _start_merging(self):
 
         ##_LOG.debug('_start_merging: Starting')
         generator = self._merge_colors(self._start_color,
-                                  Gdk.color_parse(self.ERROR_COLOR))
+                                  self.ERROR_COLOR)
         self._background_timeout_id = (
             GLib.timeout_add(FadeOut.MERGE_COLORS_DELAY, generator.__next__))
         self._countdown_timeout_id = -1
@@ -1014,13 +1018,8 @@ def set_stock(self, icon_name):
         self.set_icon_from_icon_name(Gtk.EntryIconPosition.SECONDARY, icon_name)
 
     def update_background(self, color, unset=False):
-        maxvalcol = 65535.
         if color:
-            red = int(color.red/ maxvalcol*255)
-            green = int(color.green/ maxvalcol*255)
-            blue = int(color.blue/ maxvalcol*255)
-            rgba = Gdk.RGBA()
-            Gdk.RGBA.parse(rgba, 'rgb(%f,%f,%f)'%(red, green, blue))
+            rgba = color
             self.override_background_color(Gtk.StateFlags.NORMAL |
                 Gtk.StateFlags.ACTIVE | Gtk.StateFlags.SELECTED |
                 Gtk.StateFlags.FOCUSED, rgba)
@@ -1053,11 +1052,7 @@ def update_background(self, color, unset=False):
 
     def get_background(self):
         backcol = self.get_style_context().get_background_color(Gtk.StateType.NORMAL)
-        bcol= Gdk.Color.parse('#fff')[1]
-        bcol.red = int(backcol.red * 65535)
-        bcol.green = int(backcol.green * 65535)
-        bcol.blue = int(backcol.blue * 65535)
-        return bcol
+        return backcol
 
     # Gtk.EntryCompletion convenience function
 
@@ -1143,6 +1138,7 @@ def __init__(self, data_type=None, err_color = "#ffd5d5", error_icon=ERROR_ICON)
         self._valid = True
         self._def_error_msg = None
         self._fade = FadeOut(self, err_color)
+        # FIXME: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
         self._fade.connect('color-changed', self._on_fadeout__color_changed)
 
         # FIXME put data type support back
@@ -1309,7 +1305,7 @@ def set_invalid(self, text=None, fade=True):
         if not fade:
             if self.error_icon:
                 self.set_stock(self.error_icon)
-            self.update_background(Gdk.color_parse(self._fade.ERROR_COLOR))
+            self.update_background(self._fade.ERROR_COLOR)
             return
 
         # When the fading animation is finished, set the error icon
@@ -1380,7 +1376,9 @@ def _set_valid_state(self, state):
     # Callbacks
 
     def _on_fadeout__color_changed(self, fadeout, color):
-        self.update_background(color)
+        rgb = Gdk.RGBA()
+      rgb.parse("#ffd5d5")
+        self.update_background(rgb)
 
 
 def main(args):
```
The strange behavior is fixed with this [change](https://github.com/romjerome/gramps/commit/e58554ad084d7a956e2a096a89ec8762cd4c0e43), but some issues are still pending. Some sections were unclear for me. i.e., what should be the value of 'color-changed' on
_merge_colors():
```
self.emit('color-changed', value)
```
Also, fade signal on _init_ might be incomplete
```
# FIXME: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
self._fade.connect('color-changed', self._on_fadeout__color_changed)
```
generating a workaround on _set_valid_state():
```diff
-        self.update_background(color)
+        rgb = Gdk.RGBA()
+        rgb.parse("#ffd5d5")
+        self.update_background(rgb)
```
I suppose we should pass arguments (fadeout, color)
on signal connection?
```
self._fade.connect('color-changed', self._on_fadeout__color_changed(fadeout, color))
```

Anyway, for me, the above [top change](https://github.com/romjerome/gramps/commit/e58554ad084d7a956e2a096a89ec8762cd4c0e43) fixes the wrong fade color but I know that it should be polished and I am far away to be a Gdk/GOBject and python expert.

I tried to keep the original logic, but I do not feel comfortable for making proper and complete review/refactoring or working with current API (C, gi). Any advice?

**Comment by romjerome** [comment]
It sounds like a joke (_thank you [Gtk3](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-override-background-color)_!).  :-1: 
It seems that I will have to make the large review ...

> gtk_widget_override_background_color has been deprecated since version 3.16 and should not be used in newly-written code.

> This function is not useful in the context of CSS-based rendering. If you wish to change the way a widget renders its background you should use a custom CSS style, through an application-specific GtkStyleProvider and a CSS style class. You can also override the default drawing of a widget through the “draw” signal, and use Cairo to draw a specific color, regardless of the CSS style.

**Comment by romjerome** [comment]
If need, I have a [small standalone script](https://sourceforge.net/p/gramps/mailman/message/35038915/) for testing the widget (_do not need to launch GUI_).

**Comment by romjerome** [comment]
Maybe, also make hexa color more "clearer"?

```
rgba = Gdk.RGBA()
rgba.parse("pink") # error color
rgba.parse("white") # background
etc ...
```

**Comment by dsblank** [comment]
@romjerome Do you want to close this, and propose a better fix later?

**Comment by QuLogic** [comment]
Oh sorry, I never realized what this code was trying to do. [Here is an example](https://bitbucket.org/pidgin/main/commits/788678d2e035926b1aa39ec4badb1637d8c25521) of using CSS to style the background of an entry.

However, I think most of this widget's code can be cut down and replaced with CSS animation instead of manually timing & changing the background. But I can't seem to run the file as itself to check it out.

**Comment by Nick-Hall** [comment]
@QuLogic Yes.  Using CSS styles is the best approach.  They can handle fading a background colour.

**Comment by Nick-Hall** [comment]
Fixed in gramps42 5cec72ed049881a501326a9d614eb658aa8b2b2e and master e2a5fe8e1243afdc58cdd2d81cdb7dc093f78ee0.

**Pull request closed without merging**
