### PR TITLE
Issue > blank box with an error message when attempting to use pedigr…

### PR DESCRIPTION
**Pull request by fxtmtrsine**
…ee view

@SNoiraud Hmm tried master and tried a to use a Chart view (Pedigree) but only get a blank box with an error message, looking at git blame brings me to this pr, does it work for you?

> 
> ./Gramps.py 
> 2019-06-11 16:50:56.309: WARNING: viewmanager.py: line 812: View 'pedigreeview' failed to load.
> Traceback (most recent call last):
>   File "/home/fxtmtrsine/gramps/gramps/gui/viewmanager.py", line 809, in __create_page
>     page = page_def(pdata, self.dbstate, self.uistate)
>   File "/home/fxtmtrsine/gramps/gramps/plugins/view/pedigreeview.py", line 574, in __init__
>     self.func_list.update({
> AttributeError: 'PedigreeView' object has no attribute 'func_list'
> 

https://github.com/gramps-project/gramps/blob/cd092897bcc93bba29673356918ba7579023a796/gramps/plugins/view/pedigreeview.py#L574

If it matters my git revision is :

```
git rev-parse --short HEAD
7b3c86a

```

Apologies but I was not able to raise an issue here as they don't seem to be an option , so I created a false pull request to mention the issue!

As requested by @SNoiraud

### CODE REVIEW

**Comment by Mattkmmr** [comment]
@fxtmtrsine: Usual way to submit issues is the [Gramps Bugtracker](https://gramps-project.org/bugs/)
Other ways to contact/discuss: https://gramps-project.org/introduction-WP/contact/

**Comment by SNoiraud** [comment]
Should be solved with commit 1ef467c

**Comment by fxtmtrsine** [comment]
> Should be solved with commit 1ef467c

Still unable to view any charts building from new (wiped everything from previous session) and using you example.gramps file I get the following errors
error

when i close I get another box that has the following

> 49121: ERROR: grampsapp.py: line 157: Unhandled exception
> Traceback (most recent call last):
>   File "/home/fxtmtrsine/gramps/gramps/gui/viewmanager.py", line 871, in view_changed
>     self.__change_page(page_num)
>   File "/home/fxtmtrsine/gramps/gramps/gui/viewmanager.py", line 885, in __change_page
>     self.active_page.set_active()
>   File "/home/fxtmtrsine/gramps/gramps/gui/views/navigationview.py", line 161, in set_active
>     self.goto_active(None)
>   File "/home/fxtmtrsine/gramps/gramps/gui/views/navigationview.py", line 196, in goto_active
>     self.goto_handle(active_handle)
>   File "/home/fxtmtrsine/gramps/gramps/plugins/view/pedigreeview.py", line 834, in goto_handle
>     self.rebuild_trees(handle)
>   File "/home/fxtmtrsine/gramps/gramps/plugins/view/pedigreeview.py", line 951, in rebuild_trees
>     self.rebuild(self.table, pos, lst, self.force_size)
>   File "/home/fxtmtrsine/gramps/gramps/plugins/view/pedigreeview.py", line 1045, in rebuild
>     tags=self.show_tag_color)
>   File "/home/fxtmtrsine/gramps/gramps/plugins/view/pedigreeview.py", line 191, in __init__
>     self.maxlines, True)
>   File "/home/fxtmtrsine/gramps/gramps/gen/utils/libformatting.py", line 198, in format_person
>     text = "%s\n%s %s\n%s %s" % (name, self.bth, bdate,
> AttributeError: 'FormattingHelper' object has no attribute 'bth'
> 

Then gramps became very weird not displaying any list etc .  I gather gramps master is not meant to be broken and not tested very well, felt I needed to mention the issue.

For now I'm returning to Gramps 5.0.2.

thanks for trying 👍 

@Mattkmmr will do next time. thanks

**Comment by daleathan** [comment]
@Nick-Hall @sam-m888 @Paul-Franklin Good reason to have at least one release candidate.

**Comment by SNoiraud** [comment]
It should be solved. One line disappeared during merge!

commit: 2c15e38

**Comment by SNoiraud** [comment]
> For now I'm returning to Gramps 5.0.2.

5.0.2 is not the last available release. it will be the next one.
5.1 is in development state and is not safe for deployment in a production environment.

**Comment by fxtmtrsine** [comment]
@SNoiraud that seems to only getting warning in the terminal 👍 

> 
> 2019-06-13 08:35:51.105: WARNING: uimanager.py: line 375: **Duplicate Accelerator <PRIMARY>P
> 2019-06-13 08:35:57.161: WARNING: uimanager.py: line 375: **Duplicate Accelerator <PRIMARY>P
> 2019-06-13 08:36:00.771: WARNING: uimanager.py: line 375: **Duplicate Accelerator <PRIMARY>P
> 2019-06-13 08:36:03.801: WARNING: uimanager.py: line 375: **Duplicate Accelerator <PRIMARY>P
> 2019-06-13 08:36:07.365: WARNING: uimanager.py: line 375: **Duplicate Accelerator <PRIMARY>P

**Comment by fxtmtrsine** [comment]
related to my previous message pressing "control + p" (for previous) causes an error when you get to the "Sources category"

> 18119: ERROR: grampsapp.py: line 157: Unhandled exception
> Traceback (most recent call last):
>   File "/home/fxtmtrsine/gramps/gui/viewmanager.py", line 505, in __prev_view
>     self.goto_page(cat_num-1, None)
>   File "/home/fxtmtrsine/gramps/gui/viewmanager.py", line 787, in goto_page
>     return self.pages[page_num]
> IndexError: list index out of range
>

**Comment by SNoiraud** [comment]
> 2019-06-13 08:35:51.105: WARNING: uimanager.py: line 375: **Duplicate Accelerator P

That seems to be related to the new UI manager.
In the source, we have:
```
                        # diagnostic printout; a duplicate accelerator may be
                        # a problem if both are valid for the same window at
                        # the same time.  If the actions are for a different
                        # window, this is not an error.  Here we assume a
                        # different prefix is used for different windows.
                        for accel in accels:
                            if group.prefix in accel:
                                LOG.warning('**Duplicate Accelerator %s',
                                            item[ACTION_ACC])
```

**Comment by SNoiraud** [comment]
> related to my previous message pressing "control + p" (for previous) causes an error when you get to the "Sources category"

Cannot reproduce this.

**Comment by sam-m888** [comment]
> related to my previous message pressing "control + p" (for previous) causes an error when you get to the "Sources category"

@fxtmtrsine Also unable to reproduce, can you provide any more details please?

**Comment by Nick-Hall** [comment]
> @Nick-Hall @sam-m888 @Paul-Franklin Good reason to have at least one release candidate.

I'll suggest this on the _gramps-devel_ list.  I'm not sure how much testing has been done.

**Comment by Nick-Hall** [comment]
@fxtmtrsine What is the status of this PR?  I can't see any useful code in your patch.

**Comment by Nick-Hall** [comment]
Created bug [#11186](https://gramps-project.org/bugs/view.php?id=11186) for the remaining bug and added it to the roadmap.

I'll close this PR now.

**Comment by sam-m888** [comment]
@fxtmtrsine fix raised for duplicate accelerators as #831

**Comment by fxtmtrsine** [comment]
Thanks everyone.

**Pull request closed without merging**
