### PR TITLE
Debugging coverage .travis.yml

### PR DESCRIPTION
**Pull request by stevepeak**
> RE https://github.com/codecov/support/issues/205

Please do not merge, debugging missing coverage reports.

### CODE REVIEW

**Comment by stevepeak** [comment]
Is there a reason why no coverage reports were created? https://travis-ci.org/gramps-project/gramps#L1700

**Comment by dsblank** [comment]
Yes. None of the pip installed things are recognized by nosetests, and there is no coverage via apt. There are notes about this in the issue tracker if you want more info.

**Comment by dsblank** [comment]
https://gramps-project.org/bugs/view.php?id=9391

**Comment by stevepeak** [comment]
@uxcq I believe this is your answer above.

**Pull request closed without merging**
