### PR TITLE
Localization: toolsdebug.gpr.py

### PR DESCRIPTION
**Pull request by PushKK**
1. Add localization,
2. Code formatted for PEP8.

### CODE REVIEW

**Comment by Nick-Hall** [comment]
Please put the PEP8 changes in a separate commit.   It's difficult to see what changes you have made.

**Comment by Fedik** [comment]
I would not translate Dev and Debug tools

**Comment by PushKK** [comment]
See please https://github.com/gramps-project/gramps/pull/1253

P.S. Do you know about problem in travis-ci.com? After PR Travis can't connect to 
```
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(nosetests3:5848): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
```

**Comment by PushKK** [comment]
> I would not translate Dev and Debug tools
1. This tool have 4 functions.
1 - translated before, 3 - not translated.
I add translation for this 3 functions.
2. Debug function check localization function ('Check Localized Date Displayer and Parser').
And this function work with non-localizated string and date. It's not right.

**Comment by Nick-Hall** [comment]
These tools are only visible to developers.  Translating them adds work for the translators with very little benefit.

**Pull request closed without merging**
