### PR TITLE
Add toolbar icons for Preferences and Plugin Manager

### PR DESCRIPTION
**Pull request by DaveSch-gramps**
Add Icons to open Preferences and the Plugin Manager

Feature Request [#12030](https://gramps-project.org/bugs/view.php?id=12030)

### CODE REVIEW

**Comment by Nick-Hall** [comment]
These new icons don't appear to conform to the Tango icon guidelines.  See our [Gramps icon set](https://gramps-project.org/wiki/index.php/Gramps_icon_set) wiki page for further details.

The jigsaw piece is a good choice for addons.  There should be a free Tango style icon available.

For preferences, I think that Tango uses a spanner and screwdriver rather than a cog.  However, I believe that there is a cog in the standard Tango library.

**Comment by DaveSch-gramps** [comment]
I'll substitute the [Screwdriver/Spanner icon](https://commons.wikimedia.org/wiki/Tango_icons#Categories) for the Preferences icon.

I like the idea of the Puzzle piece and had found a black icon that I colored in the gramps program folder \share\icons\adwaita

No puzzle piece in the Tango folder or the associated [GNOME folder](https://commons.wikimedia.org/wiki/Tango_icons#Categories).

Does this puzzle icon fit in with the theme from [SVG Repo](https://www.svgrepo.com/svg/51960/puzzle)?

**Comment by DaveSch-gramps** [comment]
A closer inspection of existing icons shows that the Screwdriver/Spanner is already superimposed on the generic gramps-view icon to configure views, gramps-config.

Will switch to the [cog from the Tango Categories](https://commons.wikimedia.org/wiki/Tango_icons#Categories).

**Comment by DaveSch-gramps** [comment]
My brain worked overtime last night and now realize the puzzle icon I recommended from SVG Repo above is not appropriate.

Recommending [Gnome-preferences-other.svg](https://commons.wikimedia.org/wiki/File:Gnome-preferences-other.svg)

**Comment by prculley** [comment]
I'm not sure why you don't think the puzzle piece for addons is 'not appropriate'; when I look up addons icon in Google, I see a large preponderance of puzzle icons...  Gnome-preferences-other.svg doesn't seem to be a good choice.

**Comment by DaveSch-gramps** [comment]
The puzzle piece I was suggesting as the alternative to the one I had originally proposed (and Nick H said was not up to standards) was of [two colored puzzle pieces](https://www.svgrepo.com/svg/51960/puzzle). This is the icon that I was deeming "not appropriate". 

An alternative that I was exploring is this [single golden yellow puzzle piece icon](https://www.svgrepo.com/svg/113436/puzzle). It has extra lines at the top and left which I removed.

The [Gnome-preferences-other.svg](https://commons.wikimedia.org/wiki/File:Gnome-preferences-other.svg) was a "safe" stock alternative.

I am open to your (and others) input.

**Comment by Nick-Hall** [comment]
I quite like the [mozilla puzzle icon](https://addons.cdn.mozilla.net/static/img/addon-icons/default-64.png).  It has highlighting which gives it a slight 3D effect.

**Comment by DaveSch-gramps** [comment]
adwaita dark

adwaita light

So these icons are good?

**Comment by Nick-Hall** [comment]
Yes.  They look good.

**Comment by Nick-Hall** [comment]
Added a commit to make changes immediate.

Perhaps we could make a few other icons configurable?  The clipboard, tools dialog and reports dialog would appear to be candidates.

**Comment by cdhorn** [comment]
This looks good to me.

**Comment by emyoulation** [comment]
The .SVG green puzzle piece posted to the "scalable" folder is NOT scalable. It is a 64x64 bitmap layer in the .svg file.

Scalable needs one that doesn't blur when scaled up.  

https://github.com/gramps-project/gramps/blob/a3122df673249b0f486c3b6f9909a9449a6f2b8b/images/hicolor/scalable/actions/gramps-plugin-manager.svg

**Pull request merged**
