### PR TITLE
5357 Add window position config keys for Clipboard & main window(with editorial changes removed)

### PR DESCRIPTION
**Pull request by sam-m888**
Changes:
- [x] Clipboard window remembers its previous position
- [x] Main Window starts in center of screen and when moved and Gramps restarted remembers  previous positions

Please test on:
- [ ] Apple Mac
- [ ] MS-Windows

Tested on
- [x] Linux (Ubuntu 14.04.3)

**To do**
*Main Window*
- [x] Record window sizes and positions at the end of the session and restoring them when the program is next launched.
- [ ] Remove hard-coded values 
- [x] Setting window manager hints for initial startup of Gramps ( Gtk.WindowPosition.CENTER )

*Clipboard*
- [x] Record window sizes and positions at the end of the session and restoring them when the program is next launched.
- [ ] Remove hard-coded values 
- [ ] Setting window manager hints for 1st use of clipboard ( Gtk.WindowPosition.CENTER_ON_PARENT ) https://github.com/gramps-project/gramps/blob/master/gramps/gui/clipboard.py#L1390

Any feedback welcomed.

https://gramps-project.org/bugs/view.php?id=5357

Was:
https://github.com/gramps-project/gramps/pull/58

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
I tried a version of your earlier pull request.  Just the main
window stuff and not the clipboard (which I don't use).  But
the main window remembering its position is something I
have wanted since I first started using gramps (so for five
years now).  My window manager (twm) doesn't have the
ability (I believe) to have me tell it to restore the window to
its previous position, which was why I was eager to try your
code.  It worked flawlessly!  I will be very happy to vote for
it to be included into gramps!  "+1" isn't strong enough.

But I can imagine that others might feel differently, and
so I suppose this new feature could be made optional, by
checking a box (default=off) in Edit=>Preferences say.

Thank you!

**Comment by sam-m888** [comment]
@Paul-Franklin Excellent good to hear it worked for you :+1:  Should the behavior of both be optional or just the main window and leave any window that inherits from ManagedWindow class like the clipboard?

**Comment by Paul-Franklin** [comment]
I am not a UI person but if it were me I'd have the Edit=>Preferences
option be a general one, that covered all windows (somehow), a way
to have the present behavior (the default) or to have the previous
position of any window be remembered.  I could imagine starting with
the two you have done and then seeing which ones users ask for, but
I am just guessing, how to proceed.

**Comment by sam-m888** [comment]
I'll be splitting this into two separate PR's one for

* Only Issue: 5357 Clipboard window dont remember its previous position (only its size)
https://gramps-project.org/bugs/view.php?id=5357

* make Gramps Main Windows remember its position.

**Comment by daleathan** [comment]
Will the clipboard bit be in the next release?

**Comment by sam-m888** [comment]
I don't believe so.

**Comment by uxcq** [comment]
:+1:  Clipboard staying where I place it would be great! more so with the Gramps window!!

**Comment by uxcq** [comment]
@sam-m888  Has this been abandoned

**Comment by dsblank** [comment]
Still working on this? Thanks!

**Comment by sam-m888** [comment]
Yes, haven't forgotten, just lacking time to split and resubmit :)

**Comment by Paul-Franklin** [comment]
I'd still love to see it!  8-)

**Comment by uxcq** [comment]
:(

**Pull request closed without merging**
