### PR TITLE
Add Turkish Relationship Calculator

### PR DESCRIPTION
**Pull request by BorATICI**

### CODE REVIEW

**Comment by Nick-Hall** [comment]
@BorATICI Do you need any help with this?

**Comment by BorATICI** [comment]
The code works on my computer but I couldn't fix the "Trailing whitespace" error. Do I have to create a new PR to fix it?

**Comment by Nick-Hall** [comment]
I've removed the trailing whitespace for you.

I'll merge it when you are ready.

**Comment by BorATICI** [comment]
I need to learn more about github.
Thanks a lot.

**Comment by Nick-Hall** [comment]
Need to remove a line in [`_datehandler.py`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/datehandler/_datehandler.py#L95), and add a line to the `POTFILES.skip` file.

**Comment by Nick-Hall** [comment]
Added entry in `POTFILES.skip` file.

**Pull request merged**
