### PR TITLE
review french translation

### PR DESCRIPTION
**Pull request by romjerome**
author: Patrick Gerlier (github?)

### CODE REVIEW

**Comment by romjerome** [comment]
Some returns from a [french forum](https://www.geneanet.org/forum/viewtopic.php?p=1715989). I will try to report them via the review functions.

**Comment by romjerome** [comment]
Reviews and contributions by Patrick, Jean-Marc, Patrice and others.

**Comment by SNoiraud** [comment]
I don't agree with the following translations (narrative web)
msgid "New and updated objects"
msgstr "Les greffons mis à jour et les nouveaux"

The objects used here are people, families, notes, ... not plugins

**Comment by romjerome** [comment]
> I don't agree with the following translations (narrative web)
> msgid "New and updated objects"
> msgstr "Les greffons mis à jour et les nouveaux"
:+1

**Pull request merged**
