### PR TITLE
Allow user format option

### PR DESCRIPTION
**Pull request by DaveSch-gramps**
Allows all place names to reflect the format created by the user. The fmt=0 was forcing all place names to utilize the default "Full" option.

Bug Report [#13058](https://gramps-project.org/bugs/view.php?id=13058).

### CODE REVIEW

**Comment by SNoiraud** [comment]
This was done to resolve the 12821 bug request.
So your proposal broke that solution.
I think we need to add an option for what you want to do

**Comment by Nick-Hall** [comment]
See commit [35f20a8](https://github.com/gramps-project/gramps/commit/35f20a8893599710f0cfb49685249759cdada6db).

**Comment by emyoulation** [comment]
It would be very nice to have the Researcher and Owner enhanced to use the Place Tree and Person Address.  Then have Places relative to the "Home Place" for one of those.  

e.g., if the Home Place of the Researcher was something broad like "USA, North America, Terra, Sol system, Milky Way galaxy" then "Paris, Île-de-France, France, Europe, Terra, Sol system, Milky Way galaxy" would be cropped to "Paris, Île-de-France, France, Europe". And "Houston, Harris county, Texas, USA, North America, Terra, Sol system, Milky Way galaxy" would show "Houston, Harris county, Texas"

**Comment by DaveSch-gramps** [comment]
In reading [0012821](https://gramps-project.org/bugs/view.php?id=12821) the issue I took away from it was how a place record is displayed in the narrative web's Place listing. Not how it is displayed within a person/family's event listing.

And that is a function of building the place hierarchy not the fine tuning of how the end results are displayed using the Place Formater.

In the database, places attached to a date show the name as it existed at that time. But in the Place view, the place displays at it does today. Do the same when building the Narrative Web. Have the Place list and the individual Place record display their main place name as it exists on the day the narrweb was built. I can see these place list/records reverting to the default "Full" formatting.

How a user chooses to fine tune the format in the final displayed place name will only become more important if/when GEP045 is implemented.

**Comment by Nick-Hall** [comment]
> It would be very nice to have the Researcher and Owner enhanced to use the Place Tree and Person Address.

In Gedcom 7.0 there is now a top-level submitter record.  This is used for researcher/owner information as well as for 
recording who submitted particular records.

**Comment by DaveSch-gramps** [comment]
The new commit solves the place name attached to events.

> Have the Place list and the individual Place record display their main place name as it exists on the day the narrweb was built. 

I really think this is the ultimate way to solve which place name is displayed on the Place list and in the individual Place records. Unfortunately it is beyond my hacking skill set. It was confusing enough determining which of the place lines was doing what. Some I could not determine what they did.

**Comment by Nick-Hall** [comment]
I'll close this because it breaks a previous fix.

**Pull request closed without merging**
