### PR TITLE
Add new Indonesian translation

### PR DESCRIPTION
**Pull request by Nick-Hall**
I have already added an Indonesian translation on Weblate in response to a request.  We can merge this once the translation has been started.

@jralls @prculley How do I find the correct locale code for Indonesian?  Should it be "Indonesian" or "Indonesian_Indonesia"?

### CODE REVIEW

**Comment by Nick-Hall** [comment]
We have one translator working on this, but the progress is slow.  Only about 1% of strings have been translated so far.

I'll put an entry in the `_LOCALE_NAMES` list, but won't make the translation active yet.

**Comment by emyoulation** [comment]
Can you make the Irish inactive too? We don't have a translator list and it's been sitting at zero for quite a long while.

**Comment by Nick-Hall** [comment]
@emyoulation Irish is already inactive.

**Comment by emyoulation** [comment]
That's odd. It still shows on the Weblate bar chart progress gadget. 


Is there an extra step that is required to stop Weblate from reporting it there?

**Comment by Nick-Hall** [comment]
Weblate widgets include all languages with translations.  Read the [widgets](https://hosted.weblate.org/widgets/gramps-project/) page for details.

**Pull request merged**
