### PR TITLE
Update agestats.py

### PR DESCRIPTION
**Pull request by romjerome**
Woman can have a baby after 40 years old ...

### CODE REVIEW

**Comment by sam-m888** [comment]
Do any of the other genealogy programs set the age to 55 years old ?

**Comment by romjerome** [comment]
@sam-m888 

I set 55 years old as default because it was matching on my data!
It does not really match 55, but rather 51 or 52 years old...
'55' is rather for the step range (0-5, 5-10, etc ...)

Note, the 'check data' utility (verify.py) sets 48 years old:
`'oldmom'       : 48,`

**Comment by romjerome** [comment]
Oh, there is a bug on the age stats gramplet!
We cannot set 42, 43, 44, 46, 47 or 48 years for 
the mother age calculation...

> 2019-09-11 10:39:02.034: WARNING: _gramplet.py: line 342: Gramplet gave an error: Âge statistiques
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/gramps/gen/plug/_gramplet.py", line 326, in _updater
>     retval = next(self._generator)
>   File "/usr/lib/python3/dist-packages/gramps/plugins/gramplet/agestats.py", line 178, in main
>     self.create_bargraph(mother_dict, mother_handles, _("Mother - Child Age Diff Distribution"), _("Diff"), graph_width, 5, self.max_mother_diff)
>   File "/usr/lib/python3/dist-packages/gramps/plugins/gramplet/agestats.py", line 262, in create_bargraph
>     bin[int(value/bin_size)] += hash_value
> IndexError: list index out of range
> Continuing after gramplet error...

**Comment by romjerome** [comment]
A design issue ...

> 2019-09-11 10:42:59.725: WARNING: _gramplet.py: line 342: Gramplet gave an error: Âge statistiques
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/gramps/gen/plug/_gramplet.py", line 326, in _updater
>     retval = next(self._generator)
>   File "/usr/lib/python3/dist-packages/gramps/plugins/gramplet/agestats.py", line 177, in main
>     self.create_bargraph(father_dict, father_handles, _("Father - Child Age Diff Distribution"), _("Diff"), graph_width, 5, self.max_father_diff)
>   File "/usr/lib/python3/dist-packages/gramps/plugins/gramplet/agestats.py", line 262, in create_bargraph
>     bin[int(value/bin_size)] += hash_value
> IndexError: list index out of range
> Continuing after gramplet error...
>

**Comment by romjerome** [comment]
Github has build the 'romjerome-patch-1' branch during the pull request generation,
asking me if I want to commit or to generate a patch... Feel free to close or remove 
this 'romjerome-patch-1' branch. It was an online edition then a pull request. Maybe a proper new commit could be a better solution?

About statistics, just looking at current gramplets after reading :
https://www.geneanet.org/blog/post/2019/08/les-statistiques-illustrees-4

The proposal for an update on age statistics is just for having a defaut value more inclusive.

**Comment by Nick-Hall** [comment]
@romjerome Should we also increase the father age?

**Comment by romjerome** [comment]
@Nick-Hall 
Do you mean increase age father because of the design issue?
It seems a common issue whatever status (father or mother)...
```
**File "/usr/lib/python3/dist-packages/gramps/plugins/gramplet/agestats.py", line 262, in create_bargraph
bin[int(value/bin_size)] += hash_value**
IndexError: list index out of range
Continuing after gramplet error...
```
if I understand right the max age set will be used for generating the graph 
(_size relation_). So, we should only use 0,5,10,15,20,25,30,35,40,45,50,55...
The step should be +5 and not +1!

Anyway, this seems cosmetic as there is the workaround 
=> `Continuing after gramplet error...`

Just to set '40' for default as max age for a mother is too restrictive.
'45' or '50' (45-50 range) makes 'mother' graph more close to 
data and woman fertility.

**Comment by Nick-Hall** [comment]
I did some testing with the example database which contains mothers over 40 years old and fathers over 60 years old.

Increasing the max mother age to 55 and max father age to 70 using the configuration dialog increased the size of the bar chart to show the older parents.  Whilst the defaults may not be ideal, the user is able to change them.

However, I noticed three issues:
* Setting any of the max ages to a value not divisible by 5 (e.g. 47) caused a "IndexError: list index out of range" error.
* Setting the width to 30 caused a "ZeroDivisionError: float division by zero" error.
* The statistics only includes people under the max age limits which may be misleading.

**Comment by Nick-Hall** [comment]
Opened PR #936 to fix bugs.

**Comment by Nick-Hall** [comment]
See improved Age Stats gramplet in PR #941.

**Pull request closed without merging**
