### PR TITLE
Add call to ManagedWindow.close() to dbman

### PR DESCRIPTION
**Pull request by prculley**
This is an update to "bug 8128; Fix 'Info' popup from Manage Family
Trees' dialog for parent"

I missed calling the 'close' and was getting unexpected 'Window' menu entries (and probably a memory leak).

### CODE REVIEW

**Comment by Paul-Franklin** [comment]
I haven't tried downloading your code and testing it (as
I don't know how to get it), but from past experience
it may be be the case that the "destroy" a few lines
earlier deletes the size or position (I forget) of the
ManagedWindow, which is saved in the config
variables in the ManagedWindow.close() call.

**Comment by Nick-Hall** [comment]
@prculley The `close` method is being redefined as a button.  I would rename all the buttons by adding __btn_ to the variable names.  Then you can simply call `self.close()` to close the window.  The `destroy` is no longer necessary as Paul has pointed out.

**Comment by Nick-Hall** [comment]
@Paul-Franklin Click on the "command line instructions" link next to the merge button for details of how to download and test this PR.

**Comment by Paul-Franklin** [comment]
@Nick-Hall Clicking on that pseudo-link evidently
requires Javascript to be enabled on my browser.

Ever since Javascript was invented I have been
reluctant to hand over the power to any unknown
site (like github) to run programs on my computer.

**Comment by Nick-Hall** [comment]
@Paul-Franklin To checkout and test the changes it suggests:
```
git checkout -b prculley-bug8128_ftm master
git pull git://github.com/prculley/gramps.git bug8128_ftm
```

**Comment by sam-m888** [comment]
As Pull Request are special branches,  a while back I modified my `.git/config`  and added the additional line `fetch = +refs/pull/*/head:refs/remotes/origin/pr/*`  then PR's can be listed (by number) and checked out from the command line and tested

As mentioned on the following link 
https://github.com/tiimgreen/github-cheat-sheet#checking-out-pull-requests

**Comment by Paul-Franklin** [comment]
@Nick-Hall @sam-m888 Thank you both.

**Comment by prculley** [comment]
Thanks Paul, Nick.  I've updated the PR to your suggestions; a lot more lines of diff, but no danger of confusion between a button and 'close()' method (or others).

It does not appear that the 'Manage Family Trees' dialog ever had a position/size settings for configuration in the past.  It's easy to add one, but if you think this is worth it, I can submit another PR...

**Comment by enlite93** [comment]
@Paul-Franklin re javascript on github

> We have no plans to release github.com’s JavaScript as free software at this time, nor do we have plans to remove the site’s dependence on JavaScript. Thanks for the interest.
> https://mikegerwitz.com/about/githubbub

**Pull request merged**
