### PR TITLE
sqlite3.OperationalError: database or disk is full

### PR DESCRIPTION
**Pull request by PushKK**
For https://gramps-project.org/bugs/view.php?id=12306

### CODE REVIEW

**Comment by tosky** [comment]
There are 5 commits in this pull request, all unrelated:

You need to use different branches in your local checkout and only apply the correct commits to each of them, and then create the pull requests from them.

**Comment by PushKK** [comment]
Yes, I have 4 additional branches - one branch for one change operation.
But GitHub join all files in one PR...

**Comment by tosky** [comment]
No, github doesn't aggregate them. Your SQL3Error branch contains 5 commits, not just one. Please recheck your commits in your local branches and rewrite them.

**Comment by Nick-Hall** [comment]
How does this differ from #1212?

**Comment by PushKK** [comment]
Sorry, I can't create one PR with one task.
New PR join all previous commits from all branch...
For rule "One PR - One branch - One commit" I delete my fork, then create fork your project again.

**Comment by Nick-Hall** [comment]
@PushKK Just rebase your branches on master.

**Comment by PushKK** [comment]
> No, github doesn't aggregate them. Your SQL3Error branch contains 5 commits, not just one. Please recheck your commits in your local branches and rewrite them.

**Pull request closed without merging**
