### PR TITLE
relview doesn't follow the background theme.

### PR DESCRIPTION
**Pull request by SNoiraud**
Fix #010360

### CODE REVIEW

**Comment by Nick-Hall** [comment]
We already have a proposed solution for this in PR #506.

**Comment by SNoiraud** [comment]
Yes, but this is not the same problem. Perhaps we need to merge the two PRs.
The PR #506 solves the foreground colors for tags in listview

**Comment by Nick-Hall** [comment]
PR #506 solves three issues with dark themes:  the background colour in list views, the colour of links and the shading in the relationship view.

The proposed solution of a new ShadeBox widget reacts to a change of theme without the need to restart Gramps.  It also removes some deprecated methods.

**Comment by SNoiraud** [comment]
I remove this PR. It's a duplicate of  PR #506

**Pull request closed without merging**
