### PR TITLE
Correct and update Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by tiansworld**
Hello, 
I correct and update the Simplified Chinese translation 
Please review the translation.
This is my first pull request, I hope everything works smoothly.

### CODE REVIEW

**Comment by tiansworld** [comment]
Hi guys,
After days of learning, I figured out that I didn't sync my fork with the upstream. 
Now it's synced, however I've made more commits here.
I hope everything is OK.

Will anyone please tell me what else should I do to make my commits accepted, if they are all checked without problem.
If I broke any rule or guide, please tell me too. I will try my best to follow them.

Thank you.

**Comment by prculley** [comment]
First are you sure that you want to be working off of master branch?  If the gramps51 branch is not complete, you would be better to do your work there first.  We will be merging changes in gramps51 to master periodically.  And master branch will also be seeing more changes due to new and revised code as time goes by, so we would appreciate another translation pass when we announce the code freeze for that branch.

I note that you seem to have a lot of commits that have come from other people in here, this is usually not intended.  You should do a 'git pull' while checked out on the branch you are basing on (master or maintenance/gramps51).  Then checkout your branch and rebase off of the base again.

I like to use 'gitk-all' to visualize my branch before pushing and creating a PR; this makes sure it is nice and clean, with only your commits.  You may also want to use "git rebase -i basebranch" as that allows you to merge your own commits together if necessary.

When you think you have it right, 'git push -f  I10n' to update the PR here.

**Comment by tiansworld** [comment]
> First are you sure that you want to be working off of master branch? If the gramps51 branch is not complete, you would be better to do your work there first. We will be merging changes in gramps51 to master periodically. And master branch will also be seeing more changes due to new and revised code as time goes by, so we would appreciate another translation pass when we announce the code freeze for that branch.
> 
Thank you for your kind information.
Sorry, I didn't know I was working off the master branch. I saw the branch name gramps51 is maintenance/gramps51, so I guessed I should work on master branch instead. Therefore I forked the Gramp project, and created l10n branch based on master branch on my fork. I think I can keep up with the master branch this way.

> I note that you seem to have a lot of commits that have come from other people in here, this is usually not intended. You should do a 'git pull' while checked out on the branch you are basing on (master or maintenance/gramps51). Then checkout your branch and rebase off of the base again.
> 

I am really sorry for this inconvenience, I didn't intend to do so.
I followed wiki guide at here: https://gramps-project.org/wiki/index.php/A_Translators_Guide_to_Git#Creating_a_pull_request,  to make changes and commit and push.  The only different is my branch(l10n) is based on master, not gramps51.

I think the reason it contains so many other people's commits is because the fork I created is not syncing with your upstream repo at first. 
Every time I did git pull on master, and rebase master from my l10n branch', there was nothing new.
Until yesterday, I opened github and found my repo was several commits behind upstream(gramp-project).
I searched the github help, and figured out the way to sync. After synced successfully, I made the last push in my l10n branch, which contains lots of commits that includes other people's work, as you see it now. 
I just didn't know that it will include other people's commits when I do the last push. 

> I like to use 'gitk-all' to visualize my branch before pushing and creating a PR; this makes sure it is nice and clean, with only your commits. You may also want to use "git rebase -i basebranch" as that allows you to merge your own commits together if necessary.
> 
> When you think you have it right, 'git push -f I10n' to update the PR here.

As you suggest, I switch to my local work branch 'l10n', then use 'git rebase -i master' to merge my own commits together without others' included. I see my commits are listed on top of the log, but not sure if they are right. 

gtk --all output:
Screenshot 2020-05-07 at 3 05 06 PM

Beside sync with the upstream every time, I guess I can use this command every time before I want to push my commits, so it won't includes other people's commits. Am i right?


By the way, is it possible if I use following commands to start work based on gramps51 branch next time?
1. git checkout -b my_gramps51 l10n # Create a new branch 'my_gramps51' based on my current work branch l10n, so my current changes to the po file won't be lost.
2. git rebase gramps51 
3. git fetch upstream #fetch updates from upstream
4. git merge upstream/gramps51 #merge with upstream gramps51
5. start translate, and commit and push

Thank you very much.

**Comment by prculley** [comment]
So your questions caused me to download your branch and try to clean it up.  I don't know how you got to where you are, but the two sets of commits with the same name appear to be conflicting with each other.  This makes if difficult to collapse the commits into a simple result.

What I would do:
If you are happy with the final result, save that po file elsewhere temporarily.  Rename the old branch I10n to something else to preserve it in case...
Create a new branch off of master "git checkout -b I10n master"
copy in your saved version of the po file to the correct place.
git commit -a -m "Correct and update Simplified Chinese Translation"
git push -f origin I10n

To move your work to the gramps51 branch is not quite that easy.  Git doesn't merge po files very well; it is likely that some of the translations will be lost, particularly if any of the order of the translations changed in your editing process.
    Save a copy of the master version of your po file.
    git checkout maintenance/gramps51 #fetch updates from upstream
    git pull
    git checkout -b my_gramps51 l10n # Create a new branch 'my_gramps51'
I would use the gettext tools to merge po file from gramps51 branch and master branch together.  This will preserve all the translated messages, even those that are not used in master or gramps51.  Then I would update with the pot file for gramps51.  Then edit as necessary, commit, push, and make a new PR.

**Comment by tiansworld** [comment]
> So your questions caused me to download your branch and try to clean it up. I don't know how you got to where you are, but the two sets of commits with the same name appear to be conflicting with each other. This makes if difficult to collapse the commits into a simple result.
> 
It's so kind of you. It must take you a lot of time.  
I checked every git history I did yesterday, since I knew that my fork is not syncing.

  391  git remote get-url
  392  git remote get-url --all
  393  git remote get-url --all translation (translation is 'origin')
  394  git remote get-url --push
  395  git remote get-url --push translation
  396  git pull
  397  git remote -v
  398  git remote add upstream git@github.com:gramps-project/gramps.git
Above I added the upstream

  399  git remote -v
  400  git fetch upstream
  401  git checkout master
  402  git merge upstream/master
  403  git checkout l10n
  404  git rebase master
Above I fetched and merge my fork's master to upstream, and rebased l10n branch 

  405  git diff
  409  git diff
  410  git add po/zh_CN.po 
  411  git commit -m "Synced with upstream/master branch, updated few strings."
  412  git status
Updated the po file after sync, and made the commit.

  413  git checkout master
  414  git pull
  415  git fetch upstream/master
  416  git fetch upstream
  417  git checkout master
  418  git merge upstream/master
To keep my fork tightly in sync, I did fetch and merge again 

  419  git status
  420  git remote -v
  421  git push
  422  git push --help
I made the push, but failed. Saying there were conflicts needs to be solved.

  423  git pull translation master ('translation' is my local name to 'origin')
  424  git checkout l10n
  425  git status
  426  git checkout master
  427  git status
  428  git checkout l10n
  429  git diff
  430  git log
  431  git push
  432  git pull translation l10n
  433  git diff
  437  git add po/zh_CN.po 
  438  git commit -m 'Solve the confilict.'
Above I tried to solve the conflict

  439  git push
I finally pushed the commit.

Today I did:
... fetched and merged upstream first.
 468  git rebase -i master
rebase generated errors, reminds me to fix them manually. They was one error in three previous commits respectively.

  471  git add po/zh_CN.po 
  472  git rebase --continue
  474  git add po/zh_CN.po 
  475  git rebase --continue
  477  git add po/zh_CN.po 
  478  git rebase --continue
I fixed them manually, only 1 or 2 strings starts with 'HEAD >>>' and ends with 'commit ID <<<'.

  479  git diff
  480  git log
  488  gitk --all
Generated the image I posted here. Commits became duplicated. I didn't push.

> What I would do:
> If you are happy with the final result, save that po file elsewhere temporarily. Rename the old branch I10n to something else to preserve it in case...
> Create a new branch off of master "git checkout -b I10n master"
> copy in your saved version of the po file to the correct place.
> git commit -a -m "Correct and update Simplified Chinese Translation"
> git push -f origin I10n
> 
Thank you. 
I followed the steps you suggested. Please review the new commit, 57a8057.

> To move your work to the gramps51 branch is not quite that easy. Git doesn't merge po files very well; it is likely that some of the translations will be lost, particularly if any of the order of the translations changed in your editing process.
> Save a copy of the master version of your po file.
Because the po file in master branch is untouched, I guess you mean the file that I updated, in my l10n branch?

> git checkout maintenance/gramps51 #fetch updates from upstream
> git pull
> git checkout -b my_gramps51 l10n # Create a new branch 'my_gramps51'
> I would use the gettext tools to merge po file from gramps51 branch and master branch together. This will preserve all the translated messages, even those that are not used in master or gramps51. Then I would update with the pot file for gramps51. Then edit as necessary, commit, push, and make a new PR.
So I will try this after you update the pot file.

**Comment by tiansworld** [comment]
@prculley 
Mr Crulley,
I read the guide https://gramps-project.org/wiki/index.php/A_Translators_Guide_to_Git for the 2nd time, and I think I know the reason why my fork won't sync and I bring so many troubles when I make pull request. 
 
At first, I didn't start from the clone section on the guide. 
Rather, I started directly from the Create the pull request section. So my local branch didn't track upstream, it tracks my fork only. So my fork will never get synced with upstream when I push my works to my fork. And when I checked out and pulled master, it never fetched from upstream, it just fetched from my own fork. 

It's my careless mistake to skip the Clone section on the guide. But it taught me a lot on using git.

Please let me focus on the last part of your reply.
I used the following commands to create a local branch to work on gramps51
1. git checkout -b gramps51 upstream/maintenance/gramps51 #this will make gramps51 keep track on upstream, not my fork
2. git checkout -b workl10n gramps51 #so I can edit files without any trouble, and keep it tracking to the upstream too

I think from now on, if I pull from gramps51 and rebase workl10n, then make a push, my remote fork on github will receive my translation change as well as other peoples' commits, so sync is done without conflict and will not include other commits beside mine.   

For the po files itself, I tried to using following steps to merge them.
1. copy my recent work zh_CN.po from l10n branch to tmp directory into zh_CN_master.po
2. switch to gramps51 branch, and copy zh_CN.po to tmp dir into zh_CN_gramps51.po
3. Then I use the command:
 `msgmerge zh_CN_master.po zh_CN_gramps51.po -o zh_CN_merged.po`
to merge them together. 
 `colordiff zh_CN_merged.po zh_CN_master.po` generates nothing.
 `colordiff zh_CN_merged.po zh_CN_gramps51.po` lists the translation changes I've made.
Is this what you mean to preserve all the translated messages?

**Comment by tiansworld** [comment]
Hello again,

> For the po files itself, I tried to using following steps to merge them.
> 
> 1. copy my recent work zh_CN.po from l10n branch to tmp directory into zh_CN_master.po
> 2. switch to gramps51 branch, and copy zh_CN.po to tmp dir into zh_CN_gramps51.po
> 3. Then I use the command:
>    `msgmerge zh_CN_master.po zh_CN_gramps51.po -o zh_CN_merged.po`
>    to merge them together.
>    `colordiff zh_CN_merged.po zh_CN_master.po` generates nothing.
>    `colordiff zh_CN_merged.po zh_CN_gramps51.po` lists the translation changes I've made.
>    Is this what you mean to preserve all the translated messages?
Is this merged po file(zh_CN_merged.po) can be used to translate gramps51 branch? 

Sorry, I don't know what should I do now, continue waiting for your merged file or just start all over again from gramps51 branch?

**Pull request merged**
